### ISSUE TITLE
Ubuntu 18.04 Support

### ISSUE THREAD

**Issue by MOVZX** [no-fee-ethereum-mining/nsfminer#1]
The app can't run on Ubuntu 18.04 (Hive OS).

./nsfminer: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./nsfminer)

./nsfminer: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./nsfminer)

**Comment by jean-m-cyr** [comment]
My miner only miner runs Ubuntu 20.04, an I need CUDA 11. I'd love to accommodate but I don't have 18.04 build platform. Building from source on 18.04 is the only option at this time. If I have the time I'll figure out how to run an 18.04 docker.

**Comment by jean-m-cyr** [comment]
@MOVZX Ubuntu 18.04 is now included in the releases
