### ISSUE TITLE
CUDA 11.2 Support for Ubuntu 18.04

### ISSUE THREAD

**Issue by MOVZX** [no-fee-ethereum-mining/nsfminer#10]
Currently, only CUDA 10.2 available for Ubuntu 18.04 release which makes mining with RTX 3000 impossible. RTX 3000 requires CUDA 11.2 to able to mine properly.

When forced to mine with OpenCL, it works but CPU goes 100% and produces lower hashrate.

**Comment by jean-m-cyr** [comment]
Ok, I'll update the cuda version for the builds.

**Comment by jean-m-cyr** [comment]
Done
