### ISSUE TITLE
Infinite loop after "miner No response received in 2 seconds"

### ISSUE THREAD

**Issue by flex-lab** [no-fee-ethereum-mining/nsfminer#101]
**Describe the bug**
No more shares are submitted after log message "miner No response received in 2 seconds." the program enters an infinite loop:
 cl-0  Job: bd1f61ed Solution: 0x42a628e76bbd53d4
 miner No response received in 2 seconds.
 cl-0  Job: bd1f61ed Solution: 0x42a628e822edb107
 cl-0  Job: bd1f61ed Solution: 0x42a628e84540a86d
 cl-0  Job: bd1f61ed Solution: 0x42a628e8936d2d7c
 cl-0  Job: bd1f61ed Solution: 0x42a628e910196ab4
 cl-0  Job: bd1f61ed Solution: 0x42a628e92f8878e3
 cl-0  Job: bd1f61ed Solution: 0x42a628e957c285eb
 cl-0  Job: bd1f61ed Solution: 0x42a628e9e296f1d7
 cl-0  Job: bd1f61ed Solution: 0x42a628ec3782cee4
 cl-0  Job: bd1f61ed Solution: 0x42a628ed3af4fbfe
 cl-0  Job: bd1f61ed Solution: 0x42a628ed80ae0fb2
 cl-0  Job: bd1f61ed Solution: 0x42a628f0a8185b22

I'm sceptical about deletion of return statement in a95c6937be4b746bab7c31d8c58600b153a7575a.
I believe that without return statement the recursion 

> m_workloop_timer.async_wait(m_io_strand.wrap(boost::bind(
>         &EthStratumClient::workloop_timer_elapsed, this, boost::asio::placeholders::error)));

at the end of method "workloop_timer_elapsed" creates an infinite loop.

**To Reproduce**
1. Build with 
cmake .. -DUSE_SYS_OPENCL=ON -DETHASHCUDA=OFF -DAPICORE=OFF -DBINKERN=OFF -DETHDBUS=OFF -DDEVBUILD=ON -DHUNTER_ENABLED=ON -DUSE_SYS_OPENCL=ON
cmake --build . --config debug --target nsfminer -j12
2. Start with
nsfminer --nocolor --HWMON 2 --verbosity 7 -G -P stratum1+ssl://<address>@eu1.ethermine.org:5555
3. Wait for responsetimeout from connection. In my case this occurs mostly once a day.

**Expected behavior**
Miner runs stable. It recovers from connection timeout and reestablishes connection.

**Environment (please complete the following information):**
- Operating System: Linux
- Hardware MSI RX5700
- Ethminer Version v1.3.5 (e5b6bcf83)

**Additional context**
[build.log](https://github.com/no-fee-ethereum-mining/nsfminer/files/6012686/build.log)

**Workaround**
As workaround I commented out the recursion in workloop_timer_elapsed:
[0001-workaround-workloop_timer_elapsed.patch.txt](https://github.com/no-fee-ethereum-mining/nsfminer/files/6012700/0001-workaround-workloop_timer_elapsed.patch.txt)

**Comment by jean-m-cyr** [comment]
I suspect you're right, but I've no way of easily simulating this type of timeout. Added the missing return, let me know how it goes.

**Comment by flex-lab** [comment]
The issue still exists. I could simulate timeout by reconnecting router. 
One would have to repeat a few times, because there is a chance that mining resumes. 

I wonder if anyone can confirm.

**Comment by RadoZvolensky** [comment]
Yes I can confirm that something is going on when the pool disconnects! See #110 
I don't know if it enters an infinite loop but I see the same "miner No response received in 2 seconds." and then a SIGSEGV in the logs and the whole process hangs (so it can't be restarted by the script).

**Comment by flex-lab** [comment]
On f0b77350d I have not encountered it in 10 days of testing. Moreover the previous commit has this issue. So I believe that f0b77350d fixed it.
