### ISSUE TITLE
Feature Request: add argument for max gpu utilization

### ISSUE THREAD

**Issue by Titaniumtown** [no-fee-ethereum-mining/nsfminer#102]
**Is your feature request related to a problem? Please describe.**
I want to be able to use my computer while mining, because while I'm mining the screen can lag and freeze sometimes which is very annoying.

**Describe the solution you'd like**
A argument like `--max-utilization` that is, by default, set to 100, but if you set it to 50, it'll only use 50% of the gpu's power.

**Describe alternatives you've considered**
I tried changing the `cu-streams` and `cu-block` arguments to the lowest they would go, made no difference.

**Comment by jean-m-cyr** [comment]
Won't implement. This is targeted to dedicated mining rigs
