### ISSUE TITLE
Pascal gpus hash rate performance in half

### ISSUE THREAD

**Issue by danielocdh** [no-fee-ethereum-mining/nsfminer#103]
**Describe the bug**
Pascal GPUs hash rate seems to be half than with other miners

**To Reproduce**
1. Start mining
2. Wait a bit for the hash rate to stabilize
3. See the hash rate being around half of what it should be

**Expected behavior**
Have similar hash rate of that from other miners

**Environment (please complete the following information):**
- Operating System: Windows 10 20H2 19042.804
- Driver: 456.71
- Hardware: GTX 1060(6gb) and GTX 1070
- nsfminer Version: released 1.3.5 and self built master e5b6bcf835a3ce2a45534202341ac6ac1dbb5b8a
- nsfminer options used: -P stratum+ssl://address.worker:x@us1.ethermine.org:5555

**Additional context**
The GPU usage and power usage seem to be the same as with other miners.
The halved hash rate(from nfsminer) matches what is reported  on ethminer website after 2~ hour test.
I'm comparing the hashrate against the hashrate of ethminer and phoenix miner

**Comment by jean-m-cyr** [comment]
Not seen in Linux

**Comment by SpeedeMiner** [comment]
Kill process Desktop Window Manager dwm.exe

**Comment by danielocdh** [comment]
I was sure I tested with drivers 461.40 and had the same issue before but maybe I was wrong. I had to install 461.40 on another machine and there was no issue there, so I tested some of the 1060, 1070 and 1080 ti with 461.40 and again no issue. 456.71 is supposed to be recommended for Pascal but I didn't see any obvious performance change with 461.40

**Comment by grenelt** [comment]
i had to put blocks and streams to maximum to fix this hashrate issue for my pascal-gpus: --cu-block 256 --cu-streams 4

**Comment by FrogsLegs** [comment]
Seeing the same issue. NSFMiner on my personal PC with 1x 3070 running smooth at 62 MH/s. On my mining rig 4x 3070, the hash rate is exactly as you describe, cut in half to around 30-31 MH/s. @grenelt any idea what those settings translate into on a 30 series (Ampere) GFX?

**Comment by grenelt** [comment]
@FrogsLegs The  `--cu-block 256 --cu-streams 4` parameters are the maximum the code allows. The second option may be the hardware accelerated gpu switching: [https://www.gamersnexus.net/guides/3599-windows-10-hardware-accelerated-gpu-scheduling-benchmarks](url)
If this doesn't work for you i don't have any further clues...

Which driver do you have? Maybe the newer nvidia drivers start to block mining like for the 3060s - now that we now the driver can switch the block on and off?

**Comment by FrogsLegs** [comment]
@grenelt Thanks for the response, link in your comment is dead. Not driver related as OP states mining on Claymore / Phoenix shows full 63 MH/s even with 4x 3070s. Seems to be config related to NSFMiner on Windows in particular. My guess would be parameters require setting correctly :( 

Thanks for the update 👍

**Comment by danielocdh** [comment]
> @grenelt Thanks for the response, link in your comment is dead. Not driver related as OP states mining on Claymore / Phoenix shows full 63 MH/s even with 4x 3070s. Seems to be config related to NSFMiner on Windows in particular. My guess would be parameters require setting correctly :(
> 
> Thanks for the update 👍

copy and paste as if it was text for the link, also did you try the mentioned driver and reboot? 461.40 driver fixed it for me on all machines with fully updated windows 10
