### ISSUE TITLE
After requesting restart, the number of devices increases

### ISSUE THREAD

**Issue by gap370** [no-fee-ethereum-mining/nsfminer#104]
**Describe the bug**
I wrote a script to monitor the mining using provided api. After each time I call restart, the number of devices increases.

**To Reproduce**
echo '{"id":0,"jsonrpc":"2.0","method":"miner_restart"}' | netcat 127.0.0.1 7777

**Expected behavior**
the number of devices should remain the same.

**Screenshots (Optional)**
<img width="672" alt="Screen Shot 2021-02-19 at 17 08 00" src="https://user-images.githubusercontent.com/14858037/108571287-7a46e880-72d5-11eb-97c3-2a5d15c5e5bc.png">

**Environment (please complete the following information):**
- Operating System: Ubuntu 20.04
- Hardware: GTX 1080ti
- Ethminer Version: latest
- Ethminer options used: nsfminer -P stratum2+tcp://XXX.XXX@daggerhashimoto.usa.nicehash.com:3353 -U --cu-block 256 --cu-streams 4 -R --HWMON 2 --api-bind 127.0.0.1:7777

**Comment by gap370** [comment]
also, is this a good way to keep the miner running? thanks!

**Comment by jean-m-cyr** [comment]
Indeed, it should stay the same. Let me see what is going on.

**Comment by jean-m-cyr** [comment]
Fixed by PT #105
