### ISSUE TITLE
Hash rate not reporting to pool

### ISSUE THREAD

**Issue by willis936** [no-fee-ethereum-mining/nsfminer#106]
**Describe the bug**
Ethermine does not show reported hash rates with nsfminer 1.3.5 (or ethminer 0.18).  Reporting works with t-rex.

**To Reproduce**
1. Start nsfminer with the “-R” flag enabled and an ethermine pool.
2. Observe that the worker never has a reported hashrate on the pool’s interface.

**Expected behavior**
The console reported hashrate should be making it to the pool.

**Environment (please complete the following information):**
- Operating System: Windows 10
- Hardware GTX 1070, 1080
- Ethminer Version nsfminer 1.3.5, ethminer 0.18, 0.19a1
- Ethminer options used --HWMON 2 -R -U

**Additional context**
I have tried making firewall exceptions and running the miners as admin.  I have also tried stratum (port 4444) straums and stratum2+ssl (port 5555) protocols.  This did not affect behavior.

**Comment by jean-m-cyr** [comment]
I'd need your pool URL to try and reproduce it. I can only try under Linux though!

**Comment by willis936** [comment]
I mine on us2.ethermine.org, thought I have the same observed behavior on us1.ethermine.org.

ethermine has a wonderfully helpful article on this issue.  I think it’s been around ethminer specifically for a while.

https://support.bitfly.at/support/solutions/articles/8000053685-my-mining-program-is-not-reporting-its-hashrate-to-the-pool

**Comment by SpeedeMiner** [comment]
It work great stratum+ssl or stratum+tcp.
https://ethermine.org/miners/cc30bfd43bb622063b1f2e1a663b086b54b4c7b7/dashboard

**Comment by willis936** [comment]
So it does!  Reported hashrate works for me on ethermine with stratum+ssl as well.  stratum, stratums, and stratum+ssl do not work for me on ethermine.

**Comment by jean-m-cyr** [comment]
To be clear... does stratum+ssl:// report gash rate or not when the -R option is specified?

**Comment by willis936** [comment]
stratum+ssl:// does report hash rate when the -R option is specified on windows 10 with a GTX 1070 and GTX 1080 on us1.ethermine.org.
