### ISSUE TITLE
Error while ruing cmake

### ISSUE THREAD

**Issue by Diego-mp-5** [no-fee-ethereum-mining/nsfminer#107]
I was following the instructions but when I ran CMake I got a message saying errors had occurred and to looking in the error log. I read the log but can't seem to find what is the problem.

Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /home/unsername/Downloads/nsfminer/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_4efb6/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_4efb6.dir/build.make CMakeFiles/cmTC_4efb6.dir/build
gmake[1]: Entering directory '/home/unsername/Downloads/nsfminer/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_4efb6.dir/src.c.o
/usr/bin/cc -DCMAKE_HAVE_LIBC_PTHREAD   -o CMakeFiles/cmTC_4efb6.dir/src.c.o -c /home/unsername/Downloads/nsfminer/build/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_4efb6
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_4efb6.dir/link.txt --verbose=1
/usr/bin/cc CMakeFiles/cmTC_4efb6.dir/src.c.o -o cmTC_4efb6 
/usr/bin/ld: CMakeFiles/cmTC_4efb6.dir/src.c.o: in function `main':
src.c:(.text+0x2b): undefined reference to `pthread_create'
/usr/bin/ld: src.c:(.text+0x34): undefined reference to `pthread_detach'
/usr/bin/ld: src.c:(.text+0x3d): undefined reference to `pthread_cancel'
/usr/bin/ld: src.c:(.text+0x4b): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
gmake[1]: *** [CMakeFiles/cmTC_4efb6.dir/build.make:106: cmTC_4efb6] Error 1
gmake[1]: Leaving directory '/home/unsername/Downloads/nsfminer/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:140: cmTC_4efb6/fast] Error 2

Source file was:
#include <pthread.h>

static void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_cancel(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/unsername/Downloads/nsfminer/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_34ed7/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_34ed7.dir/build.make CMakeFiles/cmTC_34ed7.dir/build
gmake[1]: Entering directory '/home/unsername/Downloads/nsfminer/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_34ed7.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create -o CMakeFiles/cmTC_34ed7.dir/CheckFunctionExists.c.o -c /usr/share/cmake-3.19/Modules/CheckFunctionExists.c
Linking C executable cmTC_34ed7
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_34ed7.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create CMakeFiles/cmTC_34ed7.dir/CheckFunctionExists.c.o -o cmTC_34ed7  -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
gmake[1]: *** [CMakeFiles/cmTC_34ed7.dir/build.make:106: cmTC_34ed7] Error 1
gmake[1]: Leaving directory '/home/unsername/Downloads/nsfminer/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:140: cmTC_34ed7/fast] Error 2

**Comment by martinbrose** [comment]
On first glance it looks like you're missing a dependency.
I think pthreads is part of libc6. Maybe try to install libc6 and / or libc6-dev and try again?

**Comment by Diego-mp-5** [comment]
I run solus and could not find libc6 in the repo, I am trying to find if I can libc6 as my fired also uses solus and was able to install  nsfminer.

**Comment by Diego-mp-5** [comment]
I posted my problems on the solus forum and got the proper packages installed.

I linked the solus forum for anyone in the future with the same problem.
https://discuss.getsol.us/d/6380-installing-libc6
