### ISSUE TITLE
How to start and add my eth wallet?

### ISSUE THREAD

**Issue by Diego-mp-5** [no-fee-ethereum-mining/nsfminer#108]
I just finished installing and have gone through all the options given under --help flag but can not find where to link my wallet or how to actually start mining.

**Comment by gap370** [comment]
If you are mining with pools, follow instructions here[https://github.com/no-fee-ethereum-mining/nsfminer/blob/master/docs/POOL_EXAMPLES_ETH.md](url)

**Comment by Diego-mp-5** [comment]
I got to that but now it says Error: No usable mining devices found, I have an Nvidia GPU but don't have CUDA as it is not available for my distro.

**Comment by Diego-mp-5** [comment]
I have mesa and OpenCL installed but I still got this error:

 miner nsfminer 1.3.5+commit.4f0387c8 (No stinkin' fees edition)
 miner Copyright 2021 Jean M. Cyr, Licensed under the terms
 miner  of the GNU General Public License Version 3
 miner https://github.com/no-fee-ethereum-mining/nsfminer
 miner Build: linux/release/gnu
 miner 3rd Party: GCC 10.2.0, Boost 1.75.0
 miner 3rd Party: OpenSSL 1.1.1i, Ethash 0.5.0
No OpenCL platforms found

Error: No usable mining devices found

**Comment by neuralsandwich** [comment]
You would get better performance out of your card using CUDA on an Nvidia card compared to OpenCL, I would presume anyway.

To find your OpenCL devices you can use [`clinfo`](https://github.com/Oblomov/clinfo). If that shows no devices then you will need to look into installing the OpenCL Nivdia drivers on your platform.

**Comment by jean-m-cyr** [comment]
Not an nsfminer issue.
