### ISSUE TITLE
list-devices report "Ellesmere" as card name for AMD

### ISSUE THREAD

**Issue by zxfrank** [no-fee-ethereum-mining/nsfminer#111]
`nsfminer --list-devices` reports all amd cards as ellesmere instead of clinfo's "Device Board Name (AMD)" `Radeon RX 570 Series`

ubuntu server 20.04 kernel 5.6.0

**Comment by jean-m-cyr** [comment]
Yes, it also reports Vega and Navi as gfx900 and gfx1010. I suppose that is for historical reasons in EThminer. These were used to select AMD binary kernels which depend on architecture rather than precise model.

**Comment by jean-m-cyr** [comment]
Fixed by PR #115
