### ISSUE TITLE
nVidia GeForce GTX 650 0.0 H/s

### ISSUE THREAD

**Issue by RallyTuning** [no-fee-ethereum-mining/nsfminer#113]
The software is running but it show 0.0 H/s. This card is not supported? I know is a poor GPU, but can be added or is worthless? Thanks!

**Comment by jean-m-cyr** [comment]
No idea! You'd need to provide a copy of the console log at startup.

**Comment by RallyTuning** [comment]
Here we go... Let me know!

 miner nsfminer 1.3.5+commit.811f00e5 (No stinkin' fees edition)
 miner Copyright 2021 Jean M. Cyr, Licensed under the terms
 miner  of the GNU General Public License Version 3
 miner https://github.com/no-fee-ethereum-mining/nsfminer
 miner Build: windows/release/msvc
 miner 3rd Party: MSVC 19.16.27045.0, CUDA 11.2, Boost 1.75.0
 miner 3rd Party: OpenSSL 1.1.1i, Ethash 0.5.0
No OpenCL platforms found
 miner Configured pool eth-eu.sparkpool.com:3333
 miner Api server listening on port 3333. Authentication needed.
 <unknown> Selected pool eth-eu.sparkpool.com:3333
 <unknown> Stratum mode : Eth-Proxy compatible
 <unknown> Established connection to eth-eu.sparkpool.com:3333
 <unknown> Spinning up miners...
 cu-0  Using Pci 0000:01:00.0: GeForce GTX 650 (Compute 3.0) Memory : 1024.00 MB
 <unknown> Epoch : 397 Difficulty : 4.00 Gh
 <unknown> Job: c92aa2e3 eth-eu.sparkpool.com:3333
 <unknown> Job: c92aa2e3 eth-eu.sparkpool.com:3333
 <unknown> Job: a084eb1d eth-eu.sparkpool.com:3333
 <unknown> Job: d9a2307d eth-eu.sparkpool.com:3333
 <unknown> 0:00 A0 0.00 h - cu0 0.00
 cu-0  Required GPU mem: Total 4.17 GB, Cache 65.62 MB, DAG 4.10 GB, Miscellaneous 56.00 B
 cu-0  Epoch 397 requires 4.17 GB of required memory from total of 1024.00 MB available on device.
 <unknown> Job: ea03ddf5 eth-eu.sparkpool.com:3333
 <unknown> 0:00 A0 0.00 h - cu0 0.00
 <unknown> Job: 32a7fd1b eth-eu.sparkpool.com:3333
 <unknown> Job: 32bc2b93 eth-eu.sparkpool.com:3333
 <unknown> Job: 7eba8f86 eth-eu.sparkpool.com:3333
 <unknown> 0:00 A0 0.00 h - cu0 0.00
 <unknown> Job: a32e84ca eth-eu.sparkpool.com:3333
 <unknown> Job: 5b2cd2c9 eth-eu.sparkpool.com:3333
 <unknown> 0:00 A0 0.00 h - cu0 0.00
 <unknown> Job: 3d4d8d20 eth-eu.sparkpool.com:3333
 <unknown> Job: b43995fb eth-eu.sparkpool.com:3333
 <unknown> Job: cfc99272 eth-eu.sparkpool.com:3333
 <unknown> Job: 2d460669 eth-eu.sparkpool.com:3333
 <unknown> 0:00 A0 0.00 h - cu0 0.00
 <unknown> Job: 4f2bedb2 eth-eu.sparkpool.com:3333
 <unknown> Job: cdefcad6 eth-eu.sparkpool.com:3333
 <unknown> 0:00 A0 0.00 h - cu0 0.00
 <unknown> Job: e757611a eth-eu.sparkpool.com:3333
 <unknown> Job: c09545a7 eth-eu.sparkpool.com:3333
 <unknown> 0:00 A0 0.00 h - cu0 0.00
 <unknown> Job: e455bbb6 eth-eu.sparkpool.com:3333
 <unknown> Job: 97e1a531 eth-eu.sparkpool.com:3333
 <unknown> Job: ba954ff4 eth-eu.sparkpool.com:3333
 <unknown> 0:00 A0 0.00 h - cu0 0.00
 <unknown> Job: 562a3ac5 eth-eu.sparkpool.com:3333
 <unknown> Job: 3ebffa77 eth-eu.sparkpool.com:3333
 <unknown> Job: 38ba4a5c eth-eu.sparkpool.com:3333
 <unknown> 0:00 A0 0.00 h - cu0 0.00
 <unknown> Job: 7e3a168c eth-eu.sparkpool.com:3333
 <unknown> Job: 516200e0 eth-eu.sparkpool.com:3333
 <unknown> Job: d3056f9a eth-eu.sparkpool.com:3333
 <unknown> Job: cd35a314 eth-eu.sparkpool.com:3333
 <unknown> Job: 963e3d5a eth-eu.sparkpool.com:3333
 <unknown> 0:00 A0 0.00 h - cu0 0.00
 <unknown> Job: 6de3c6aa eth-eu.sparkpool.com:3333
 <unknown> Job: 68e57d85 eth-eu.sparkpool.com:3333
 <unknown> Job: 4fb0b7b2 eth-eu.sparkpool.com:3333
 <unknown> 0:00 A0 0.00 h - cu0 0.00
 <unknown> Job: 69eed584 eth-eu.sparkpool.com:3333
 <unknown> Job: f46ede9d eth-eu.sparkpool.com:3333
 <unknown> Job: fff5fb15 eth-eu.sparkpool.com:3333
 <unknown> Job: 8f5fcf2b eth-eu.sparkpool.com:3333
 <unknown> Job: eae75543 eth-eu.sparkpool.com:3333
 <unknown> Job: 17980015 eth-eu.sparkpool.com:3333
 <unknown> Job: 426b9067 eth-eu.sparkpool.com:3333
 <unknown> 0:01 A0 0.00 h - cu0 0.00
 <unknown> Job: 65a025d1 eth-eu.sparkpool.com:3333
 <unknown> Job: 8886610f eth-eu.sparkpool.com:3333
 <unknown> Job: fc62502e eth-eu.sparkpool.com:3333
 <unknown> Job: 8235f271 eth-eu.sparkpool.com:3333
 <unknown> 0:01 A0 0.00 h - cu0 0.00
 <unknown> Job: 80076b0d eth-eu.sparkpool.com:3333
 <unknown> Job: 6e93691e eth-eu.sparkpool.com:3333
 <unknown> Job: e3cb25e7 eth-eu.sparkpool.com:3333
 <unknown> Job: 3abf0924 eth-eu.sparkpool.com:3333
 <unknown> 0:01 A0 0.00 h - cu0 0.00
 <unknown> Job: 6375a5d9 eth-eu.sparkpool.com:3333
 <unknown> Job: 948d4b4f eth-eu.sparkpool.com:3333
 <unknown> Job: ce0c41ad eth-eu.sparkpool.com:3333
 <unknown> Job: ce6e1fb7 eth-eu.sparkpool.com:3333
 <unknown> Job: cc9ad515 eth-eu.sparkpool.com:3333
 <unknown> 0:01 A0 0.00 h - cu0 0.00
 <unknown> Job: 06f38611 eth-eu.sparkpool.com:3333
 <unknown> Job: 8fa5cd67 eth-eu.sparkpool.com:3333
 <unknown> Job: 7cb0a407 eth-eu.sparkpool.com:3333
 <unknown> 0:01 A0 0.00 h - cu0 0.00
 <unknown> Job: 27c75b5d eth-eu.sparkpool.com:3333
 <unknown> Job: f5b0f23b eth-eu.sparkpool.com:3333
 <unknown> Job: 5baad656 eth-eu.sparkpool.com:3333
 <unknown> Job: 2ed6893d eth-eu.sparkpool.com:3333
 <unknown> 0:01 A0 0.00 h - cu0 0.00
 <unknown> Job: 933b2469 eth-eu.sparkpool.com:3333
 <unknown> Job: 3399ba2b eth-eu.sparkpool.com:3333
 <unknown> Job: f2e04fe6 eth-eu.sparkpool.com:3333
 <unknown> Job: 557248d6 eth-eu.sparkpool.com:3333
 <unknown> Job: 276f7f3d eth-eu.sparkpool.com:3333
 <unknown> 0:01 A0 0.00 h - cu0 0.00
 <unknown> Job: 1b8b33fe eth-eu.sparkpool.com:3333
 <unknown> Job: 7ec88c3d eth-eu.sparkpool.com:3333
 <unknown> 0:01 A0 0.00 h - cu0 0.00
 <unknown> Job: 2af3d2ca eth-eu.sparkpool.com:3333
 <unknown> Job: 8b6c8c6e eth-eu.sparkpool.com:3333
 <unknown> Job: b7183327 eth-eu.sparkpool.com:3333
 <unknown> 0:01 A0 0.00 h - cu0 0.00
 <unknown> Job: 5bdfc7c3 eth-eu.sparkpool.com:3333
 <unknown> Job: 13da85f8 eth-eu.sparkpool.com:3333
 <unknown> Job: 2d371fd7 eth-eu.sparkpool.com:3333
 <unknown> 0:01 A0 0.00 h - cu0 0.00
 <unknown> Job: d0b53e1e eth-eu.sparkpool.com:3333
 <unknown> 0:01 A0 0.00 h - cu0 0.00
 <unknown> Job: be42543e eth-eu.sparkpool.com:3333
 <unknown> Job: bf158b06 eth-eu.sparkpool.com:3333
 <unknown> Job: a05e3b6a eth-eu.sparkpool.com:3333
 <unknown> Job: 69b00cf3 eth-eu.sparkpool.com:3333
 <unknown> 0:01 A0 0.00 h - cu0 0.00
 <unknown> Job: 868355ac eth-eu.sparkpool.com:3333
 <unknown> Job: 84e9688d eth-eu.sparkpool.com:3333
 <unknown> 0:02 A0 0.00 h - cu0 0.00
 <unknown> Job: bc4dfb64 eth-eu.sparkpool.com:3333
 <unknown> Job: 0a380592 eth-eu.sparkpool.com:3333
 <unknown> Job: fbe17f3f eth-eu.sparkpool.com:3333
 <unknown> Job: 706dff67 eth-eu.sparkpool.com:3333
 <unknown> Job: 99112a1b eth-eu.sparkpool.com:3333
 <unknown> Job: 4722641f eth-eu.sparkpool.com:3333
 <unknown> 0:02 A0 0.00 h - cu0 0.00
 <unknown> Job: 3615cc37 eth-eu.sparkpool.com:3333
 <unknown> Job: 9aabcb3d eth-eu.sparkpool.com:3333
 <unknown> Job: 6b8b478a eth-eu.sparkpool.com:3333
 <unknown> Job: 6871eff3 eth-eu.sparkpool.com:3333
 <unknown> 0:02 A0 0.00 h - cu0 0.00
 <unknown> Job: 3d6a05be eth-eu.sparkpool.com:3333
 <unknown> Job: adc0d6fc eth-eu.sparkpool.com:3333
 <unknown> Job: 2b6c3817 eth-eu.sparkpool.com:3333
 <unknown> Job: 07c3da8c eth-eu.sparkpool.com:3333
 <unknown> 0:02 A0 0.00 h - cu0 0.00
 <unknown> Job: fc7387e1 eth-eu.sparkpool.com:3333
 <unknown> Job: 1bc5e8a7 eth-eu.sparkpool.com:3333
 <unknown> 0:02 A0 0.00 h - cu0 0.00
 <unknown> Job: e2e02839 eth-eu.sparkpool.com:3333
 <unknown> Job: e558713d eth-eu.sparkpool.com:3333
 <unknown> 0:02 A0 0.00 h - cu0 0.00
 <unknown> Job: 18de6671 eth-eu.sparkpool.com:3333
 <unknown> Job: 84f42996 eth-eu.sparkpool.com:3333
 <unknown> Job: db7cf472 eth-eu.sparkpool.com:3333
 <unknown> Job: 365c3310 eth-eu.sparkpool.com:3333
 <unknown> Job: 82984e3d eth-eu.sparkpool.com:3333
 <unknown> 0:02 A0 0.00 h - cu0 0.00
 <unknown> Job: 14df2824 eth-eu.sparkpool.com:3333
 <unknown> Job: 58ef4f19 eth-eu.sparkpool.com:3333
 <unknown> Job: 3c6a93c7 eth-eu.sparkpool.com:3333
 <unknown> Job: 385eedf5 eth-eu.sparkpool.com:3333
 <unknown> Job: 2b2e4249 eth-eu.sparkpool.com:3333
 <unknown> 0:02 A0 0.00 h - cu0 0.00
 <unknown> Job: affe911a eth-eu.sparkpool.com:3333
 <unknown> Job: 61aa56fa eth-eu.sparkpool.com:3333
 <unknown> Job: 46b3e5f9 eth-eu.sparkpool.com:3333
 <unknown> Job: b975fb9c eth-eu.sparkpool.com:3333
 <unknown> Job: 20f8798a eth-eu.sparkpool.com:3333
 <unknown> 0:02 A0 0.00 h - cu0 0.00
 <unknown> Job: b212fada eth-eu.sparkpool.com:3333
 <unknown> Job: dffdc9b9 eth-eu.sparkpool.com:3333
 <unknown> Job: a53e4b22 eth-eu.sparkpool.com:3333
 <unknown> Job: 81a84157 eth-eu.sparkpool.com:3333
 <unknown> Job: ad936d06 eth-eu.sparkpool.com:3333
 <unknown> 0:02 A0 0.00 h - cu0 0.00
 <unknown> Job: 115b3d70 eth-eu.sparkpool.com:3333
 <unknown> Job: 31468740 eth-eu.sparkpool.com:3333
 <unknown> Job: 2608d9ee eth-eu.sparkpool.com:3333
 <unknown> Job: 8327a601 eth-eu.sparkpool.com:3333
 <unknown> Job: 1d290522 eth-eu.sparkpool.com:3333
 <unknown> Job: 5899db82 eth-eu.sparkpool.com:3333
 <unknown> 0:02 A0 0.00 h - cu0 0.00
 <unknown> Job: 606137d8 eth-eu.sparkpool.com:3333
 <unknown> Job: bb8f11a1 eth-eu.sparkpool.com:3333
 <unknown> Job: 166ebea4 eth-eu.sparkpool.com:3333
 <unknown> Job: 9f712a96 eth-eu.sparkpool.com:3333
 <unknown> 0:02 A0 0.00 h - cu0 0.00
 <unknown> Job: 34a45982 eth-eu.sparkpool.com:3333
 <unknown> Job: 721a3c93 eth-eu.sparkpool.com:3333
 <unknown> Job: cf614eea eth-eu.sparkpool.com:3333
 <unknown> Job: 0cc0eb4d eth-eu.sparkpool.com:3333
 <unknown> 0:03 A0 0.00 h - cu0 0.00
 <unknown> Job: 5531dade eth-eu.sparkpool.com:3333
 <unknown> Job: a31e18fc eth-eu.sparkpool.com:3333
 <unknown> Job: 70480eb9 eth-eu.sparkpool.com:3333
 <unknown> Job: 8271289a eth-eu.sparkpool.com:3333
 <unknown> 0:03 A0 0.00 h - cu0 0.00
 <unknown> Job: c6d0740d eth-eu.sparkpool.com:3333
 <unknown> Job: 29cfdc38 eth-eu.sparkpool.com:3333
 <unknown> Job: 4d1ef48a eth-eu.sparkpool.com:3333
 <unknown> Job: 1b36857d eth-eu.sparkpool.com:3333
 <unknown> Job: ffd78910 eth-eu.sparkpool.com:3333
 <unknown> Job: 34479430 eth-eu.sparkpool.com:3333
 <unknown> Job: e662d61e eth-eu.sparkpool.com:3333
 <unknown> 0:03 A0 0.00 h - cu0 0.00
 <unknown> Job: a055e2ba eth-eu.sparkpool.com:3333
 <unknown> Job: 529151c4 eth-eu.sparkpool.com:3333
 <unknown> Job: 5ec8e3c4 eth-eu.sparkpool.com:3333
 <unknown> Job: 2f8b1463 eth-eu.sparkpool.com:3333
 <unknown> Job: 5ce76021 eth-eu.sparkpool.com:3333
 <unknown> Job: afe85e40 eth-eu.sparkpool.com:3333
 <unknown> 0:03 A0 0.00 h - cu0 0.00
 <unknown> Job: 8fa90aa0 eth-eu.sparkpool.com:3333
 <unknown> Job: 509b8322 eth-eu.sparkpool.com:3333
 <unknown> Job: 01f829b1 eth-eu.sparkpool.com:3333
 <unknown> Job: 2b5c0cf8 eth-eu.sparkpool.com:3333
 <unknown> 0:03 A0 0.00 h - cu0 0.00
 <unknown> Job: 454ae38d eth-eu.sparkpool.com:3333
 <unknown> Job: d9e13d2a eth-eu.sparkpool.com:3333
 <unknown> Job: 56097d38 eth-eu.sparkpool.com:3333
 <unknown> Job: ebe1cc96 eth-eu.sparkpool.com:3333
 <unknown> Job: 9b0823ed eth-eu.sparkpool.com:3333
 <unknown> 0:03 A0 0.00 h - cu0 0.00
 <unknown> Job: 29d6ad46 eth-eu.sparkpool.com:3333
 <unknown> Job: 9250eb91 eth-eu.sparkpool.com:3333
 <unknown> Job: 69a715a4 eth-eu.sparkpool.com:3333
 <unknown> Job: f73a36c1 eth-eu.sparkpool.com:3333
 <unknown> Job: 6aabf1ed eth-eu.sparkpool.com:3333
 <unknown> 0:03 A0 0.00 h - cu0 0.00
 <unknown> Job: b3e6003b eth-eu.sparkpool.com:3333
 <unknown> Job: 5114d250 eth-eu.sparkpool.com:3333
 <unknown> Job: a4c9867c eth-eu.sparkpool.com:3333
 <unknown> Job: 5fcc205f eth-eu.sparkpool.com:3333
 <unknown> Job: 52e1a7fd eth-eu.sparkpool.com:3333
 <unknown> 0:03 A0 0.00 h - cu0 0.00
 <unknown> Job: 25200918 eth-eu.sparkpool.com:3333
 <unknown> Job: 301630cd eth-eu.sparkpool.com:3333
 <unknown> Job: 9b4558f3 eth-eu.sparkpool.com:3333
 <unknown> Job: 36d8bac2 eth-eu.sparkpool.com:3333
 <unknown> 0:03 A0 0.00 h - cu0 0.00
 <unknown> Job: 6df0b4e5 eth-eu.sparkpool.com:3333
 <unknown> Job: fe0c4e65 eth-eu.sparkpool.com:3333
 <unknown> Job: 7736bbc5 eth-eu.sparkpool.com:3333
 <unknown> Job: d0a9fe4e eth-eu.sparkpool.com:3333
 <unknown> 0:03 A0 0.00 h - cu0 0.00
 <unknown> Job: 08c38be4 eth-eu.sparkpool.com:3333
 <unknown> Job: 6ff35561 eth-eu.sparkpool.com:3333
 <unknown> Job: acdcaba0 eth-eu.sparkpool.com:3333
 <unknown> Job: 000f722f eth-eu.sparkpool.com:3333
 <unknown> 0:03 A0 0.00 h - cu0 0.00
 <unknown> Job: 9d46b21c eth-eu.sparkpool.com:3333
 <unknown> Job: f61c6e5a eth-eu.sparkpool.com:3333
 <unknown> Job: ee2270b1 eth-eu.sparkpool.com:3333
 <unknown> 0:03 A0 0.00 h - cu0 0.00
 <unknown> Job: b06658c1 eth-eu.sparkpool.com:3333
 <unknown> Job: 3fb7df2f eth-eu.sparkpool.com:3333
 <unknown> 0:04 A0 0.00 h - cu0 0.00
 <unknown> Job: 7f226490 eth-eu.sparkpool.com:3333
 <unknown> Job: 83cb23a1 eth-eu.sparkpool.com:3333
 <unknown> 0:04 A0 0.00 h - cu0 0.00
 <unknown> Job: a0dfae76 eth-eu.sparkpool.com:3333
 <unknown> Job: 9397e130 eth-eu.sparkpool.com:3333
 <unknown> Job: c6738c45 eth-eu.sparkpool.com:3333
 <unknown> Job: 107c26fe eth-eu.sparkpool.com:3333
 <unknown> Job: d1eb391b eth-eu.sparkpool.com:3333
 <unknown> 0:04 A0 0.00 h - cu0 0.00
 <unknown> Job: 5c237e3b eth-eu.sparkpool.com:3333
 <unknown> Job: 50666d9d eth-eu.sparkpool.com:3333
 <unknown> Job: 0b8ed544 eth-eu.sparkpool.com:3333
 <unknown> 0:04 A0 0.00 h - cu0 0.00
 <unknown> Job: 7d317fdc eth-eu.sparkpool.com:3333
 <unknown> Job: 8d356b55 eth-eu.sparkpool.com:3333
 <unknown> Job: 7b3b3ca3 eth-eu.sparkpool.com:3333
 <unknown> 0:04 A0 0.00 h - cu0 0.00
 <unknown> Job: 6941ee6a eth-eu.sparkpool.com:3333
 <unknown> Job: 4c9c8b5c eth-eu.sparkpool.com:3333
 <unknown> 0:04 A0 0.00 h - cu0 0.00
 <unknown> Job: 73d67f7b eth-eu.sparkpool.com:3333

**Comment by 80917663** [comment]
look at this line:
cu-0 Using Pci 0000:01:00.0: GeForce GTX 650 (Compute 3.0) Memory : 1024.00 MB
Epoch : 397 Difficulty : 4.00 Gh
GeForce GTX 650 has only 1024.00 MB Memory , but u need at least 4.17 GB.
So,it can't work.

**Comment by RallyTuning** [comment]
Oh crap, thank you! :)
