### ISSUE TITLE
miner CUDA Error : unknown error

### ISSUE THREAD

**Issue by codegastudio** [no-fee-ethereum-mining/nsfminer#117]
On jetson xavier nx, try to run nfsminer with command 
```
nsfminer -U -P stratum+tcp://<walletid>@<pool>:<port>
```
and get following error
```
miner nsfminer 1.3.7 (No stinkin' fees edition)
 miner Copyright 2021 Jean M. Cyr, Licensed under the terms
 miner  of the GNU General Public License Version 3
 miner https://github.com/no-fee-ethereum-mining/nsfminer
 miner Build: linux/release/gnu
 miner 3rd Party: GCC 7.5.0, Boost 1.75.0
 miner 3rd Party: OpenSSL 1.1.1i, Ethash 0.5.0
 miner CUDA Error : unknown error

Error: No usable mining devices found
```

**To Reproduce**
- install last jetson pack 4.5 with cuda 10
- update cmake to the latest version `cmake --version`
 ```
 cmake version 3.20.0-rc1
```
- update cuda to version 11 `/usr/local/cuda/bin/nvcc --version`
 ```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Thu_Jun_11_22:26:42_PDT_2020
Cuda compilation tools, release 11.0, V11.0.194
Build cuda_11.0_bu.TC445_37.28540450_0
```
- apt install libdbus-1-dev libssl-dev
- git clone nfsminer project 
- follow [installation instructions](https://github.com/no-fee-ethereum-mining/nsfminer/blob/master/docs/BUILD.md#instructions) => compilation successful
- run nfsminer and get error

Try to run `nsfminer --list-devices` and get following message 
```
No OpenCL platforms found
 miner CUDA Error : unknown error

Error: No usable mining devices found
```

regards

**Comment by jean-m-cyr** [comment]
Platform not supported.

**Comment by codegastudio** [comment]
Ok, after a discussion on the [nvidia forum](https://forums.developer.nvidia.com/t/nvidia-driver-460-not-running/170369), we cannot upgrade the cuda version on jetson cards as we can do on classic hardware.
So i had a new question about it :
Do you think it's possible to have a version of your miner for cuda 10 plz ?
