### ISSUE TITLE
miner_getscramblerinfo

### ISSUE THREAD

**Issue by zxfrank** [no-fee-ethereum-mining/nsfminer#120]
Just wondering what appened to api methods get and set scramblerinfo..?

**Comment by jean-m-cyr** [comment]
The only reason I could think of for these API calls was to make sure multiple miners don't overlap their search ranges.

You can achieve the same goal using the --nonce parameter of the miner_setnonce API. There isn't a miner_getnonce API.

**Comment by jean-m-cyr** [comment]
miner_getnonce API implemented in master
