### ISSUE TITLE
v1.3.7 - Fan/temp and powerlimit infos missing

### ISSUE THREAD

**Issue by omega180984** [no-fee-ethereum-mining/nsfminer#122]
**Describe the bug**
With the new version v1.3.7 the FAN/Temp and Powerlimit Information from our gpus is not shown (only 0 is visible for all values)

**To Reproduce**
1. Start miner v1.3.7 on windows with parameter HWMON 2
4. See error/Missing information about all installed GPU

**Expected behavior**
It should show the information about the GPU's FAN/Temp and Powerlimit

**Environment (please complete the following information):**
- Operating System: [Windows 10]
- Hardware [2 x RTX 3070 and 1 RTX 3060 Ti]
- Ethminer Version [v1.3.7]
- Ethminer options used: HWMON 2 / CUDA

**Comment by jean-m-cyr** [comment]
Since different versions of the Nvidia drivers install the nvml.dll file at different locations, the folder that contains the dll must be included in your library search path. Under Windows I believe that is specified via the PATH environment variable.

**Comment by omega180984** [comment]
Ok Thanks a lot for this info, i will try it :)

**Comment by jean-m-cyr** [comment]
If implemented a backwards compatible nvml.dll search, so this should no longer be an issue.

**Comment by omega180984** [comment]
Thank you very much for the fix in the last version :)
