### ISSUE TITLE
Why don‘t work when i have succeed compiled these dll.

### ISSUE THREAD

**Issue by wwzh2015** [no-fee-ethereum-mining/nsfminer#123]
The mistake tips:
![image](https://user-images.githubusercontent.com/14988958/109182015-86481400-77c7-11eb-8f31-45fc08af996f.png)

I have compiled these dll:
![image](https://user-images.githubusercontent.com/14988958/109181968-792b2500-77c7-11eb-8a26-6fda9c66084b.png)

**Comment by jean-m-cyr** [comment]
You can't mine BTC with this miner.

**Comment by wwzh2015** [comment]
> You can't mine BTC with this miner.

This is a ETH

Please tips me How to exactly  mine format
