### ISSUE TITLE
computing power a bit lower then ethminer

### ISSUE THREAD

**Issue by 80917663** [no-fee-ethereum-mining/nsfminer#125]
When looking at cuda11 errors, I found that your program works normally. It's really great.

After testing nsfminer and ethminer, it is found that the computing power of nsfminer is lower than that of ethminer on my computer.

The image above is ethminer with CUDA utilization rate of 95% - 100%, and the image below is nsfminer with CUDA utilization rate of 85% - 100%. In the same way, the computing power is reduced.

I would like to ask what is the reason for the reduction of computing power and whether it can be improved.

Finally, thank you for your efforts.
![新建位图图像 (2)](https://user-images.githubusercontent.com/60637541/109277314-25195280-7852-11eb-8a1c-cc56c627d998.jpg)

**Comment by jean-m-cyr** [comment]
Windows or Linux?

**Comment by 80917663** [comment]
windows10 64bit

**Comment by 80917663** [comment]
> When looking at cuda11 errors, I found that your program works normally. It's really great.
> 
> After testing nsfminer and ethminer, it is found that the computing power of nsfminer is lower than that of ethminer on my computer.
> 
> The image above is ethminer with CUDA utilization rate of 95% - 100%, and the image below is nsfminer with CUDA utilization rate of 85% - 100%. In the same way, the computing power is reduced.
> 
> I would like to ask what is the reason for the reduction of computing power and whether it can be improved.
> 
> Finally, thank you for your efforts.
> ![新建位图图像 (2)](https://user-images.githubusercontent.com/60637541/109277314-25195280-7852-11eb-8a1c-cc56c627d998.jpg)

**Comment by MikeF-** [comment]
![image](https://user-images.githubusercontent.com/6849877/109383244-edf87f00-78ed-11eb-9dc8-e3367c3b7382.png)
Similar behavior here with RTX 3070.

Looks like this on nsfminer log
![image](https://user-images.githubusercontent.com/6849877/109383264-12545b80-78ee-11eb-8ace-77bba201a7f3.png)

I'm running Windows 10 64bit with nsfminer_1.3.7-windows_10-cuda_11.2-opencl

**Comment by jean-m-cyr** [comment]
I don't run Windows. Let me know if anyone figures this out.

**Comment by igoralebar** [comment]
And I'm actually getting slightly higher MH/s on GTX 1080 with CUDA 11.2 build, compared to ethminer with CUDA 11.1.
This is on Windows 10. Ethminer CUDA 11.1 ~0.1 MH/s slower
![](https://i.imgur.com/zmZqsLg.png)

**Comment by igoralebar** [comment]
Try enabling Hardware Accelerated GPU Scheduling. Reboot.
I noticed that when I have it turned off, my hashrate starts jumping around.

**Comment by MikeF-** [comment]
> 
> 
> Try enabling Hardware Accelerated GPU Scheduling. Reboot.
> I noticed that when I have it turned off, my hashrate starts jumping around.

Thanks for the tip, this solved the issue for me at least.

![image](https://user-images.githubusercontent.com/6849877/109457054-c1b23f00-7a62-11eb-8749-4967e65e4709.png)

**Comment by igoralebar** [comment]
> Thanks for the tip, this solved the issue for me at least.
> 
overclock that VRAM, my brother is getting 59.5 MH/s at just 120W with 3060 Ti, with core locked at 945 MHz at 750mV in AfterBurner

**Comment by omega180984** [comment]
Maybe someone have an idea why in my setup on lastest Windows 10 with 3 rtx 3070 and intel HD 530 used for Minitor output and enabled "Hardware Accelerated GPU Scheduling" my hashrate drop to arround 0? all 3 RTX Cards are connected over an PCIE ryzer 16x to 1x. Without this option enabled i get around 60mh/s for one card but its constantly changing (50 - 65).

Thanks in advance

**Comment by grenelt** [comment]
I have 3 GTX1660 (1 Super, 2 TI) - all way slower than with ethminer - about 24 mh/s instead of 28 mh/s for the tis, about 20 mh/s instead of 23 mh/s. To get this i had to raise blocks to 256 and streams to 4. With default settings hashrate was only halved to14 and 10 mh/s.

I'm on Windows 10x64 with the latest nsfminer release.

Funny thing is: There is a GTX1660 in my desktop which doesn't suffer from this drop and works fine with ethminer and nsfminer. On both machines same Windows, same Nvidia drivers...

The only differences are the count of videocards and two additional RX5700 in the mining rig with the GTXs.
So maybe it's an issue with mixed setups.

**Comment by wwzh2015** [comment]
I guess the reason is your graphic card output Windows UI，you should use mainboard output video signal.

**Comment by jean-m-cyr** [comment]
Where is this "Hardware Accelerated GPU Scheduling" option set in Windows. Perhaps it could be enabled automatically by the miner? Might be in the Win Registry somewhere?

**Comment by igoralebar** [comment]
" In Registry editor, navigate to ‘HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers’.
Locate DWORD tiled “HwSchMode”. Use value 2 to turn it On and 1 to turn it Off "
Though, you have to reboot PC for it to come into effect.

**Comment by jean-m-cyr** [comment]
If it needs a reboot then no point in doing it in the miner.

**Comment by grenelt** [comment]
@jean-m-cyr Yes, it needs reboot afaik.
