### ISSUE TITLE
Unable to start .bat file

### ISSUE THREAD

**Issue by axumius** [no-fee-ethereum-mining/nsfminer#126]
Was using ethminer and now trying to get nsfminer working. I have a 3080 hence the reason for the switch. I followed steps to attach to pool (ethermine) but I keep getting same error when launching .bat file.  It is not recognizing a the command starting with -P. I have no idea how to build the .bat file for nsfminer. I have the pool line made and the .bat file made but I am lost here. 
-P stratum1+tcp://(WALLET).miner1@us1.ethermine.org:4444
PAUSE
The pause is due to the cmd closing before being able to see what the error was.

**Comment by SpeedeMiner** [comment]
nsfminer.exe -R -U -P stratum+ssl://*@eu1.ethermine.org:5555 --exit --HWMON 2 --api-bind 192.168.1.15:3333 --retry-delay 5 --retry-max 0 --verbosity 4

**Comment by axumius** [comment]
not recognized as a internal or external command. Is there a file that this .bat has to be located in within the nsfminer-master folder?

**Comment by SpeedeMiner** [comment]
Bat and nsfminer.exe in one folder

**Comment by axumius** [comment]
Okay not to be rude but could you explain in more detail? I dont understand what I need to do different here. I renamed the .bat to nsfminer.exe and now it just spams the same command over and over in cmd. I wish  there was Prebuilt files already in there showing how the .bat needs to be made in order to work. nsfminer seems way too complicated for the beginner miner compared to any other mining software I have tried over the past year. could you explain why my .bat is now just repeating the same command over and over now that it is named nsfminer.exe? when its not named that it goes back to closing the cmd immediately again.

**Comment by jean-m-cyr** [comment]
You don't rename the .bat file. You place it in the same folder as the nfsminer.exe file.

**Comment by axumius** [comment]
[miner screenshot.pdf](https://github.com/no-fee-ethereum-mining/nsfminer/files/6055378/miner.screenshot.pdf)
what am I doing wrong here?
