### ISSUE TITLE
Hi, How I setting wallet and pool address in cpp? 

### ISSUE THREAD

**Issue by wwzh2015** [no-fee-ethereum-mining/nsfminer#128]
I want to set wallet and pool address  in cpp, where is the API? 

Thanks!

**Comment by lesjokolat** [comment]
https://github.com/no-fee-ethereum-mining/nsfminer/blob/master/docs/POOL_EXAMPLES_ETH.md

**Comment by wwzh2015** [comment]
But i want to set my account and pool address in the cpp, don't use command line!
