### ISSUE TITLE
Round 2 of the same issue with .bat

### ISSUE THREAD

**Issue by axumius** [no-fee-ethereum-mining/nsfminer#129]
I have done all steps as stated previously even though it didnt work the ticket was still closed???? It is not recognizing anything as a command. Setting up the command line to connect to a pool just gives me a error stating "'nsfminer.exe' is not recognized as an internal or external command, operable program or batch file." Removing the "nsfminer.exe" from the beginning and starting with -P still says "'-P' is not recognized as an internal or external command, operable program or batch file." I dont understand why nsfminer is so much more difficult to start a .bat for mining compared to any other mining programs.

**Comment by jean-m-cyr** [comment]
Please explain your problem in a comprehensible form. For example, the purpose of the .bat file in question and it's contents.

**Comment by axumius** [comment]
Moved to phoenix miner. .bat for mining was already made in designated folder and all you had to do was replace the wallet address. Im sure your program runs well but it isn't working for me. Thank you for responding.
