### ISSUE TITLE
floating hash rate

### ISSUE THREAD

**Issue by angelir1** [no-fee-ethereum-mining/nsfminer#131]
Hello, please tell me why in ethminer the hashrate is stable, but in nsfminer the hashrate is constantly changing?
I use:
nsfminer version 1.3.7
-U -P stratum1+tcp://valet-addres.MyMiner@eu1.ethermine.org:4444 -v 2
OS-Windows 10

![floating hash rate](https://user-images.githubusercontent.com/36644127/109552763-40e75780-7ae3-11eb-96fa-497fb8bf6c14.jpg)

**Comment by jean-m-cyr** [comment]
No idea. I can't really support Windows. I don't use it.

**Comment by Minerx117** [comment]
Try enabling Hardware Accelerated GPU Scheduling. Reboot.
I noticed that when I have it turned off, my hashrate starts jumping around.

**Comment by angelir1** [comment]
> Try enabling Hardware Accelerated GPU Scheduling. Reboot.
> I noticed that when I have it turned off, my hashrate starts jumping around.
Thank you very much, I have enabled Hardware Accelerated GPU Scheduling and, indeed, while the hash rate is stable, the truth was to update Windows 10 to version 20H2. There is no such switch in previous versions.

> No idea. I can't really support Windows. I don't use it.
Thank you very much for supporting nsfminer!

**Comment by igoralebar** [comment]
> the truth was to update Windows 10 to version 20H2.
20H1 had HAGS switch too
and if you looked at previous issue, you could see that previous guy answer is copy pasted

**Comment by angelir1** [comment]
Thank you all, the main thing is the result is positive

**Comment by omega180984** [comment]
Maybe someone have an idea why in my setup on lastest Windows 10 with 3 rtx 3070 and intel HD 530 used for Minitor output and enabled "Hardware Accelerated GPU Scheduling" my hashrate drop to arround? all 3 RTX Cards are connected over an PCIE ryzer 16x to 1x. Without this option i get around 60mh/s for one card.

Thanks in advance
