### ISSUE TITLE
Error GPU

### ISSUE THREAD

**Issue by angelir1** [no-fee-ethereum-mining/nsfminer#133]
Good day! An error occurs. After that, nsfminer continues to work, but the power consumption of the GPU drops sharply
nsfminer V 1.3.7-9 comits
OS -Windows 10
GPU0 -RTX3080
GPU1-RTX2080
GPU2-RTX2080
GPU3-GTX1080
The Scheduling Hardware Accelerated GPU option is enabled.
If the parameter "Scheduling a GPU with hardware acceleration" is turned off, then the miner works without errors, but the hash rate starts to float

![error](https://user-images.githubusercontent.com/36644127/109980348-dd427180-7d10-11eb-9fe2-1b9e1fe604c9.jpg)

![power](https://user-images.githubusercontent.com/36644127/109981739-4080d380-7d12-11eb-9904-a6286976df7b.jpg)

**Comment by grenelt** [comment]
I have: GTX1060, GTX1080, GTX1660 (plain/TI/Super), RTX3060.. with Windows 10 and the 641 driver.

I observe, that mixing up generations leads to problems - but also ethminer (and kawpowminer) have the same problems. I can mix two generations of gpus - pascal with ampere or pascal with turing or turing with ampere. A third generation leads instantly to different and hard to spot errors.

Maybe a hint is: A disfunctional setup also shows wrong memory sizes - i.e. if there is a rtx 3060, all gpus are reported to have 12 gb of ram. Some combinations shows the memory error, but work like GTX1080 (8 gb) and GTX1650 (4 gb) - where both cards are reported to have 4 gb.

I can't decide if this is just a visual problem or if the misinterpretation leads to wrong memory allocations - which seams to be likely thinking of the "out of memory" errors.

It's maybe more a Nvidia driver issue - but it's quite annoying.

**Comment by taliesins** [comment]
I have "GeForce RTX 2070 with Max-Q Design" with NVidia Driver 461.72 and experince the same problem. It appears that the machine is still mining but pool does not see it as online and does not credit you with any mining.

I suspect its related to messing around with core clock and memory clock speeds and the laptop overheating. So its probably VRAM overheating. I had core clock set to -502 and memory clock to 745. My approach is to drop memory clock until its stable and hope that works.

**Comment by jean-m-cyr** [comment]
Not sure why the hang detector popped here, but it has no effect is neither --exit or reboot script is provided.
