### ISSUE TITLE
How do I enable the log file?

### ISSUE THREAD

**Issue by Alekseisu** [no-fee-ethereum-mining/nsfminer#135]
How do I enable the log file?

**Comment by lesjokolat** [comment]
found this on ethminer may work for nsf:

ethminer -G -F http://yourpool 2>&1 | tee output.log

**Comment by Alekseisu** [comment]
> found this on ethminer may work for nsf:
> 
> ethminer -G -F http://yourpool 2>&1 | tee output.log

It doesn't work that way!

**Comment by Alekseisu** [comment]
What is the "--syslog" flag for?

**Comment by lesjokolat** [comment]
look in miner help

./nsfminer --help then pick sections review. They have explanations of various commands

then use command
./nsfminer -H (section you like)

**Comment by Alekseisu** [comment]
> look in miner help
> 
> ./nsfminer --help then pick sections review. They have explanations of various commands
> 
> then use command
> ./nsfminer -H (section you like)

This is exactly what I did! There is a "--syslog" flag, but I don't know how it works !?

**Comment by jean-m-cyr** [comment]
The --syslog flag was originally meant to remove the timestamp prefix on console messages directed to syslog, since syslog entries aromatically get timestamped. In nsfminer  console messages are not timestamped, the only thing it does is turn on the --nocolor option..

**Comment by Alekseisu** [comment]
> The --syslog flag was originally meant to remove the timestamp prefix on console messages directed to syslog, since syslog entries aromatically get timestamped. In nsfminer console messages are not timestamped, the only thing it does is turn on the --nocolor option..

How do I enable the log file?
