### ISSUE TITLE
AMD OpenCL binary kernel for ellesmere (RX580)

### ISSUE THREAD

**Issue by Ed-Yang** [no-fee-ethereum-mining/nsfminer#138]
The ellesmere binary kernel is not found in nsfminer/libcl/kernels/bin.

If I change to Makefile to build ellesmere and run with "--cl-bin" flag, it got zero hash rate.

**Comment by jean-m-cyr** [comment]
nfsminer is able to load binary kernels designed for it, but none are available as of yet. The old Ethminer binary kernels don't work.
