### ISSUE TITLE
Building issue

### ISSUE THREAD

**Issue by neektoo** [no-fee-ethereum-mining/nsfminer#139]
2 days that i'm trying to build the sources.

Everything seems installed and build seems find during first hour, hunter, openssl, boost... i have correct 2017 VS and SDK... but at the very end i have Error: could not load cache

When i restart script it gives :

**********************************************************************
** Visual Studio 2017 MSBuild Command Prompt
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
-- [cable ] Cable 0.2.14 initialized
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- [cable ] Configurations: Release;RelWithDebInfo
-- [hunter] Calculating Toolchain-SHA1
-- [hunter] Calculating Config-SHA1
-- [hunter] HUNTER_ROOT: C:/.hunter
-- [hunter] [ Hunter-ID: 7d73237 | Toolchain-ID: ff9707f | Config-ID: 117b6b1 ]
-- [hunter] BOOST_ROOT: C:/.hunter/_Base/7d73237/ff9707f/117b6b1/Install (ver.: 1.75.0)
-- [hunter] BOOST_ROOT: C:/.hunter/_Base/7d73237/ff9707f/117b6b1/Install (ver.: 1.75.0)
-- [hunter] BOOST_ROOT: C:/.hunter/_Base/7d73237/ff9707f/117b6b1/Install (ver.: 1.75.0)
-- [hunter] BOOST_ROOT: C:/.hunter/_Base/7d73237/ff9707f/117b6b1/Install (ver.: 1.75.0)
CMake Warning (dev) at CMakeLists.txt:75 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable Boost_ROOT is set to:

    C:/.hunter/_Base/7d73237/ff9707f/117b6b1/Install

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Boost version: 1.75.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   thread
-- [hunter] JSONCPP_ROOT: C:/.hunter/_Base/7d73237/ff9707f/117b6b1/Install (ver.: 1.8.0)
CMake Warning (dev) at CMakeLists.txt:78 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable jsoncpp_ROOT is set to:

    C:/.hunter/_Base/7d73237/ff9707f/117b6b1/Install

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- [hunter] ETHASH_ROOT: C:/.hunter/_Base/7d73237/ff9707f/117b6b1/Install (ver.: 0.5.0)
CMake Warning (dev) at CMakeLists.txt:81 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable ethash_ROOT is set to:

    C:/.hunter/_Base/7d73237/ff9707f/117b6b1/Install

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

----------------------------------------------------------------------------
-- CMake 3.20.0-rc3
-- Build  / Windows
----------------------------------------------------------------- components
-- ETHASHCL         Build OpenCL components                      ON
-- ETHASHCUDA       Build CUDA components                        ON
-- ETHASHCPU        Build CPU components (only for development)  OFF
-- ETHDBUS          Build D-Bus components                       OFF
-- APICORE          Build API Server components                  ON
-- BINKERN          Install AMD binary kernels                   OFF
-- DEVBUILD         Build with dev logging                       OFF
----------------------------------------------------------------------------

-- [hunter] OPENSSL_ROOT: C:/.hunter/_Base/7d73237/ff9707f/117b6b1/Install (ver.: 1.1.1i)
CMake Warning (dev) at libpool/CMakeLists.txt:19 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable OpenSSL_ROOT is set to:

    C:/.hunter/_Base/7d73237/ff9707f/117b6b1/Install

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- [hunter] OPENCL_ROOT: C:/.hunter/_Base/7d73237/ff9707f/117b6b1/Install (ver.: 2.1-p3)
CMake Warning (dev) at libcl/CMakeLists.txt:32 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable OpenCL_ROOT is set to:

    C:/.hunter/_Base/7d73237/ff9707f/117b6b1/Install

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- [hunter] BOOST_ROOT: C:/.hunter/_Base/7d73237/ff9707f/117b6b1/Install (ver.: 1.75.0)
-- [hunter] BOOST_ROOT: C:/.hunter/_Base/7d73237/ff9707f/117b6b1/Install (ver.: 1.75.0)
CMake Warning (dev) at nsfminer/CMakeLists.txt:25 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable Boost_ROOT is set to:

    C:/.hunter/_Base/7d73237/ff9707f/117b6b1/Install

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Boost version: 1.75.0
-- Found the following Boost libraries:
--   program_options
-- Configuring done
-- Generating done
-- Build files have been written to: C:/C/nsfminer-1.3.8/nsfminer/build
Error: could not load cache

Never had so much troubles to build something

**Comment by jean-m-cyr** [comment]
Can't help with build issues.

**Comment by thecodecentral** [comment]
If you are using the Windows specific script provided by the doc,

```
rem For CUDA 9.x pass also `-T v140`
cmake -G "Visual Studio 15 2017 Win64" -H. -Bbuild -DETHASHCL=ON -DETHASHCUDA=ON -DAPICORE=ON ..
cd "build\"
cmake --build . --config Release --target package
```

Try remove the `cd "build\"` line.
