### ISSUE TITLE
Metrics stability 

### ISSUE THREAD

**Issue by 1rabbit** [no-fee-ethereum-mining/nsfminer#14]
When running on windows 10 with a 3070 and 1060, I get unstable measurements :

`<unknown> 0:28 A27 78.83 Mh - cu0 58.31, cu1 20.52
 <unknown> Job: a93df220 eu1.ethermine.org:5555
 <unknown> Job: 47f354a3 eu1.ethermine.org:5555
 <unknown> 0:28 A27 75.12 Mh - cu0 54.36, cu1 20.76
 <unknown> Job: 2a45d2c0 eu1.ethermine.org:5555
 <unknown> 0:28 A27 65.57 Mh - cu0 46.52, cu1 19.05
 <unknown> Job: 82099566 eu1.ethermine.org:5555
 <unknown> Job: 3f994337 eu1.ethermine.org:5555
 <unknown> 0:29 A27 85.13 Mh - cu0 62.27, cu1 22.86
 <unknown> Job: 194c58df eu1.ethermine.org:5555
 <unknown> Job: 686bfe46 eu1.ethermine.org:5555 `

**Comment by jean-m-cyr** [comment]
To readable format
```
<unknown> 0:28 A27 78.83 Mh - cu0 58.31, cu1 20.52 
<unknown> Job: a93df220 eu1.ethermine.org:5555 
<unknown> Job: 47f354a3 eu1.ethermine.org:5555 
<unknown> 0:28 A27 75.12 Mh - cu0 54.36, cu1 20.76 
<unknown> Job: 2a45d2c0 eu1.ethermine.org:5555 
<unknown> 0:28 A27 65.57 Mh - cu0 46.52, cu1 19.05 
<unknown> Job: 82099566 eu1.ethermine.org:5555 
<unknown> Job: 3f994337 eu1.ethermine.org:5555 
<unknown> 0:29 A27 85.13 Mh - cu0 62.27, cu1 22.86 
<unknown> Job: 194c58df eu1.ethermine.org:5555 
<unknown> Job: 686bfe46 eu1.ethermine.org:5555
```
Looks like you GPUs may be throttling. Those are actual hash counts accurately counted in the GPUs.

**Comment by dogmoosefern** [comment]
I get similar hash count jumping on windows 10 as 1rabbit is showing. I believe it has something to do with windows 10 (v1.2.3) because on the linux version (v1.2.3 as well) the hash count is stable. Some change between ethminer and nsfminer has affected performance in windows, below is a comparison between the latest ethminer master branch and nsfminer v1.2.3

ethminer
![ethminer](https://user-images.githubusercontent.com/77853374/105616045-cf501700-5d88-11eb-8a3d-9b09c34bc729.png)

nsfminer
![nsfminer](https://user-images.githubusercontent.com/77853374/105616058-e989f500-5d88-11eb-807c-8a73eddcb5ca.png)

**Comment by jean-m-cyr** [comment]
Yes, nsfminer is different from Ethminer as it implements fast abort on Nvidia which significantly reduces job switch time. I'm surprised at the difference between Linux and Windows build. I don't run windows though...

**Comment by dogmoosefern** [comment]
I'm happy to help test on windows 10 with a 3080 and 3060 ti if you'd like. I don't really know cuda but know enough to get the right dependencies to build from source.

In addition to the difference in consistent CUDA usage between ethminer and nsfminer, I just noticed the screenshot is also showing cpu work being done when nsfminer is running. I wonder if that's the bottleneck in keeping the gpu loaded?

**Comment by jean-m-cyr** [comment]
Ethminer CPU usage should be near 0.

**Comment by jean-m-cyr** [comment]
BTW. If you can build from source I'd be happy to put up some dev build branches with diagnostics if you would help with testing.

**Comment by dogmoosefern** [comment]
Yeah I can build from source with the branch you want. Just ping me when you want me to test and what you want to log. Should be able to respond within 1.5 days or so most of the time.

**Comment by mih0** [comment]
![screenshot](https://user-images.githubusercontent.com/30499778/106350895-59e4c900-62e9-11eb-842a-e822ff379a2e.png)
all 1080 ti

**Comment by kylhuk** [comment]
Mine is jumping quite a bit, too, using a Nvidia RTX 3090
```
 <unknown> 0:17 A31 91.25 Mh - cu0 91.25
 <unknown> Job: 7e1f5a4e eu1.ethermine.org:4444
 <unknown> 0:17 A31 109.72 Mh - cu0 109.72
 <unknown> Job: c73cedc1 eu1.ethermine.org:4444
 <unknown> 0:17 A31 114.49 Mh - cu0 114.49
 <unknown> Job: 37ef1e6d eu1.ethermine.org:4444
 <unknown> 0:17 A31 114.58 Mh - cu0 114.58
 <unknown> Job: d8eef4a8 eu1.ethermine.org:4444
 <unknown> Job: 6dcd3c5a eu1.ethermine.org:4444
 <unknown> 0:18 A31 104.44 Mh - cu0 104.44
 <unknown> Job: eee6480f eu1.ethermine.org:4444
 <unknown> 0:18 A31 111.70 Mh - cu0 111.70
 <unknown> Job: 4fee761b eu1.ethermine.org:4444
 <unknown> 0:18 A31 112.12 Mh - cu0 112.12
 <unknown> Job: bb7c5d23 eu1.ethermine.org:4444
 <unknown> 0:18 A31 117.65 Mh - cu0 117.65
 <unknown> Job: fea3022a eu1.ethermine.org:4444
 <unknown> Job: fefc778e eu1.ethermine.org:4444
 <unknown> 0:18 A31 107.26 Mh - cu0 107.26
```

How about you average the speed, let's say, over a minute? So you wouldn't have jumps and the speed would be quite accurate.

Also happy to help with my 3090, just let me know

And thanks a lot @jean-m-cyr for your contributions to this project. Very much appreciated.

**Comment by jean-m-cyr** [comment]
Those are real hashes, counted at the GPUs. Averaging would only mask a real problem. There should not be that much variation period. Unfortunately, my skills and test environment lean heavily towards Linux.

**Comment by selop** [comment]
I don't think this is a real issue. I checked metrics in Windows Task Manager vs GPU-Z. 
GPU-Z shows 100% constant GPU load. I think this is a UI flaw in Windows. 

![3060ti-win](https://user-images.githubusercontent.com/5173254/107264632-7b5d5780-6a43-11eb-8f37-5889dab06960.PNG)

**Comment by nunogia** [comment]
I see same issue.
Only to add that, if i open 2 nsfminer each one with only 1 card the problem almost disappears, only slight variance on each one (as expected).

**Comment by Jorge-Moreira** [comment]
> ink this is a UI flaw in Windows.

I don't know if we can say that is a window UI flaw. Somehow before the GPU load on windows task manager (ethminer) wasn't with this kind of load spikes.

It could be about @jean-m-cyr said here: https://github.com/no-fee-ethereum-mining/nsfminer/issues/14#issuecomment-766402958

I'll be glad to help testing a possible fix for this.

**Comment by TBloop** [comment]
I just got my 3070 today and it's happening to me too. T-Rex and PhoenixMiner are quite steady, maybe variance no more then 1Mh/s. I really wanted to use nsfminer since I hate those stinkin' fees, but with this variance I'll have to switch to T-rex :-(. I dont think my GFX card is throttling. 

If there is a fix for this I would love to hear about it. Are there any other decent ETH miners without a fee?! I would have thought there would have been many of them!

![chrome_2021-02-16_21-55-37](https://user-images.githubusercontent.com/72537849/108150174-3a4bef80-70a2-11eb-88bb-3ae3cff958e5.png)

**Comment by selop** [comment]
@TBloop You are running your card at stock settings and thus getting mediocre results. This has nothing to do with nsfminer. Research some proper overclock settings (core clock down, memory clock up) and set them up with e.g. MSI Afterburner.

**Comment by TBloop** [comment]
I have overclocked my card and while I'm getting better hash rates, they still are fluctuating a lot. It seems to happen no matter what OC settings I use.
![chrome_2021-02-17_17-43-29](https://user-images.githubusercontent.com/72537849/108277607-afbdcb80-7147-11eb-928d-e170d343b24e.png)
 This doesn't happen in T-Rex.

**Comment by kolba** [comment]
@TBloop to have an ideal test, make sure you only have a single monitor and its connected to your onboard graphics output. This way you will minimize any use of the mining GPU by the OS. For me it can swing around 20 MH/s while i have some other things open on the desktop.

**Comment by TBloop** [comment]
Honestly, I just switched to T-Rex. I dont think it's an issue with my software. It does fluctuate when I watch things like videos for instance, but when idle, T-Rex is quite stable, while nsfminer unfortunately is not.

**Comment by kolba** [comment]
yeah, fair enough. i suppose the main reason for using ethminer or nsfminer is for the open source thing and not performance or features
