### ISSUE TITLE
/lib64/libc.so.6: version `GLIBC_2.18' not found (Full static build) 

### ISSUE THREAD

**Issue by itcwork** [no-fee-ethereum-mining/nsfminer#140]
Hello, Can somebody please help me compile nsfminer for linux with full static build libraries? I own more linux platforms and most of them,they give me the following error: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./nsfminer) ,including GLIBC 2.25. So I need somehow to compile the miner with all libraries embeded (libc.so.6,libstdc++,libresolv etc.) . Your help would be very appreciated

**Comment by jean-m-cyr** [comment]
Looks like no one can. Closing
