### ISSUE TITLE
Use board name rather than architecture for AMD

### ISSUE THREAD

**Issue by minerjed** [no-fee-ethereum-mining/nsfminer#142]
**Describe the bug**
Wondering if a bug was introduced when the change was implemented to use the board name rather than architecture for AMD.  Just shows <unknown> where I would expect board name.  

**To Reproduce**
Run with AMD Vega 56 

**Expected behavior**
Would expect <unknown> to show the board name.  Just guessing.

**Screenshots (Optional)**
cl-0  Job: ecbdebb4 Solution: 0x907d781cf6fadceb
 <unknown> **Accepted 179 ms. eth-us-east1.nanopool.org:9999
 <unknown> Job: cefed0f5 eth-us-east1.nanopool.org:9999
 <unknown> 6:33 A74 31.38 Mh - cl0 31.38
 <unknown> Job: 1bd89a3a eth-us-east1.nanopool.org:9999

**Environment (please complete the following information):**
- Operating System: Windows 10]
- Hardware: ADM Vega 56
- NSFMiner v1.3.8
- Ethminer options used: nsfminer.exe -R -G -P stratum1+tcp://0x1b8d6FFB1d6a75c62e85bEd76B1548eCD230c666@eth-us-east1.nanopool.org:9999/GPU1/xxxxx%%40xxxx.net

**Comment by jean-m-cyr** [comment]
Not sure what you mean? In the log text you posted above, where to you expect the board name will appear?

**Comment by grenelt** [comment]
I think he wishes something like this:

**gfx901** Job: ecbdebb4 Solution: 0x907d781cf6fadceb
**Accepted 179 ms. eth-us-east1.nanopool.org:9999
Job: cefed0f5 eth-us-east1.nanopool.org:9999
6:33 A74 31.38 Mh - **gfx901** 31.38
Job: 1bd89a3a eth-us-east1.nanopool.org:9999

Or so:

**AMD Vega 56 [0]** Job: ecbdebb4 Solution: 0x907d781cf6fadceb
**Accepted 179 ms. eth-us-east1.nanopool.org:9999
Job: cefed0f5 eth-us-east1.nanopool.org:9999
6:33 A74 31.38 Mh - **AMD Vega 56 [0]** 31.38
Job: 1bd89a3a eth-us-east1.nanopool.org:9999

I'm not sure this is very useful, but i think, that's what he wishes...

**Comment by minerjed** [comment]
Was just wondering why <unknown> was being displayed and what was suppose to be there.  Was told on glitter that it use to display the time.  Closing this.  I agree with grenelt, not very useful.  I am looking a the code now so more to come.

**Comment by jean-m-cyr** [comment]
The removal of the timestamp was intentional.
