### ISSUE TITLE
Cosmetic Change to output

### ISSUE THREAD

**Issue by minerjed** [no-fee-ethereum-mining/nsfminer#144]
In PoolManager.cpp I would like to suggest that you change to the following just so the <unknown> text in the miner output does not confuse anyone.

void PoolManager::setClientHandlers()
{
    dev::setThreadName("pool");                                               /*  add this line new line */
    p_client->onConnected([&]() {
        {
            cnote << "Established connection to " << m_selectedHost;
            m_connectionAttempt = 0;

**Comment by jean-m-cyr** [comment]
Presently the message is
`miner Established connection to eth-us-east.flexpool.io:4444`
How is that confusing?

**Comment by minerjed** [comment]
This is on windows 10, outputs <unknown> since the output is not identified.  Not sure how it outputs on Linux.

 

Old output



New output

**Comment by igoralebar** [comment]
I think they meant this 
![image](https://user-images.githubusercontent.com/78835491/111667877-32f53e80-8826-11eb-9ba8-79e01a50e7ab.png)

**Comment by minerjed** [comment]
Before
![pic1](https://user-images.githubusercontent.com/42452856/111670148-e55cdf80-87ed-11eb-8559-fc96e30de358.jpg)


After
![pic2](https://user-images.githubusercontent.com/42452856/111670275-09202580-87ee-11eb-808f-fbcddd78d9aa.jpg)

**Comment by minerjed** [comment]
Like I said it just cosmetic...

**Comment by jean-m-cyr** [comment]
Ah! A Windows thing. I don't run Windows so it was not obvious what you meant. For consistency though, I would use 'miner' rather than 'pool'.

**Comment by minerjed** [comment]
Miner sounds good.  Just <unknown> made me think that was an error or something was not configured correctly.  Thanks.

**Comment by grenelt** [comment]
Cosmetic, but much butter... ;)

**Comment by jean-m-cyr** [comment]
Fixed in master

**Comment by Wingblur** [comment]
this doesn't seem to have made it into the master I just downloaded.
