### ISSUE TITLE
3090 performance

### ISSUE THREAD

**Issue by 3djc** [no-fee-ethereum-mining/nsfminer#145]
While performance (hashrate) seems to be somewhat close to other miners (trex, gminer) for 3060ti or 3070, it seems lower for 3090

![image](https://user-images.githubusercontent.com/5167938/111745415-d416e000-888c-11eb-964d-65f217e11967.png)
![image](https://user-images.githubusercontent.com/5167938/111745026-5e127900-888c-11eb-9ce3-bf220b64ea3e.png)
![image](https://user-images.githubusercontent.com/5167938/111745613-222be380-888d-11eb-8465-ca389980cda5.png)

- Operating System: HiveOS
- Hardware : MSI 3090
- NSFminer 1.3.8

I haven't done it yet, but I can probably set a linux compilation environment if that can help for tests

**Comment by jean-m-cyr** [comment]
I don't have any of the said GPUs. This is a personal project I've made public so others might benefit, but I can't provide universal support for things I don't have or use, namely Windows and a great many GPUs.

**Comment by dedizones** [comment]
You have to take on Trex the value  remove the 1% fee you will have the real hashrate / result, to Gminer it is the same withdraw 0.65%

My 3070 (TREX) is 61.50Mhs: 61.50 - 1% = 60.88Mhs

My real hash => 60.88Mhs (in Trex wihout fee)

NSFMiner:  60.87Mhs

![image](https://user-images.githubusercontent.com/58809062/111920543-dac17500-8a8f-11eb-9ebd-9e5e81c300ea.png)

I noticed that we need to increase the WATT of the cards in HiveOS:
Trex 120w
nsfminer 125 / 128w

**Comment by jean-m-cyr** [comment]
I'm curious. I thought Nvidia had crippled 3060s for mining?

**Comment by dedizones** [comment]
> I'm curious. I thought Nvidia had crippled 3060s for mining?

Yes only "3060" me i have 3060TI

**Comment by if4lcon** [comment]
They released a beta driver for developers and it did unlock the limitation on eth mining but you must install the gpu on the motherboard directly and plug it to monitor or dummy hdmi

**Comment by jean-m-cyr** [comment]
Ah!. So it must require PCIe 3.1 features unsupported in risers?

**Comment by if4lcon** [comment]
unfortunately you can't use it with risers right now I hope someone can fix this issue

**Comment by HugoPoi** [comment]
_I'm a noob but_
@dedizones :
> You have to take on Trex the value remove the 1% fee you will have the real hashrate / result, to Gminer it is the same withdraw 0.65%
> 
> My 3070 (TREX) is 61.50Mhs: 61.50 - 1% = 60.88Mhs
> 
> My real hash => 60.88Mhs (in Trex wihout fee)

If the hashrate include fee : so the full hash rate should be near of nsfminer
If the hashrate doesn't include fee, then it's worse so it's 61.5 + 1% === nsfminer

Or I'm missing something.

**Comment by dedizones** [comment]
> _I'm a noob but_
> @dedizones :
> 
> > You have to take on Trex the value remove the 1% fee you will have the real hashrate / result, to Gminer it is the same withdraw 0.65%
> > My 3070 (TREX) is 61.50Mhs: 61.50 - 1% = 60.88Mhs
> > My real hash => 60.88Mhs (in Trex wihout fee)
> 
> If the hashrate include fee : so the full hash rate should be near of nsfminer
> If the hashrate doesn't include fee, then it's worse so it's 61.5 + 1% === nsfminer
> 
> Or I'm missing something.

each software mine for X seconds for them, I believe T-Rex 90 seconds per hour after yes it offers you 61Mhs for you because it has optimized the nvidia kernel, but during the time you mine for developer fees, you are disconnected of the pool and therefore you also lose money ... especially the pplns pool.

After according to my tests the two are the same, as @ jean-m-cyr said, he is the only one to develop and in addition he shares his personal project to us, I would have helped him but I am not DEVOOPS
I can only test its builds under nvidia.

Be careful, I never said that NFSMiner was better, I said it was the same as the others.

**Comment by if4lcon** [comment]
> > _I'm a noob but_
> > @dedizones :
> > > You have to take on Trex the value remove the 1% fee you will have the real hashrate / result, to Gminer it is the same withdraw 0.65%
> > > My 3070 (TREX) is 61.50Mhs: 61.50 - 1% = 60.88Mhs
> > > My real hash => 60.88Mhs (in Trex wihout fee)
> > 
> > 
> > If the hashrate include fee : so the full hash rate should be near of nsfminer
> > If the hashrate doesn't include fee, then it's worse so it's 61.5 + 1% === nsfminer
> > Or I'm missing something.
> 
> each software mine for X seconds for them, I believe T-Rex 90 seconds per hour after yes it offers you 61Mhs for you because it has optimized the nvidia kernel, but during the time you mine for developer fees, you are disconnected of the pool and therefore you also lose money ... especially the pplns pool.
> 
> After according to my tests the two are the same, as @ jean-m-cyr said, he is the only one to develop and in addition he shares his personal project to us, I would have helped him but I am not DEVOOPS
> I can only test its builds under nvidia.
> 
> Be careful, I never said that NFSMiner was better, I said it was the same as the others.

I have used Gminer and I think it's more stable on Nvidia GPUs , NSFMiner with AMD works very well .. I like open source and I support @jean-m-cyr and that's why I use NSFMiner .. even though I'm getting inconsistent hashrate on Nvidia

**Comment by buzzard192** [comment]
> Ah!. So it must require PCIe 3.1 features unsupported on risers?

It requires the card to be connected by either 8 or 16 PCIe lanes. Most risers for mining are only 1 lane. Also, the slot must be at least PCIe 3.0.

**Comment by 3djc** [comment]
> You have to take on Trex the value remove the 1% fee you will have the real hashrate / result, to Gminer it is the same withdraw 0.65%
> 
> My 3070 (TREX) is 61.50Mhs: 61.50 - 1% = 60.88Mhs
> 
> My real hash => 60.88Mhs (in Trex wihout fee)
> 
> NSFMiner: 60.87Mhs
> 
> ![image](https://user-images.githubusercontent.com/58809062/111920543-dac17500-8a8f-11eb-9ebd-9e5e81c300ea.png)
> 
> I noticed that we need to increase the WATT of the cards in HiveOS:
> Trex 120w
> nsfminer 125 / 128w

As I said 3060ti/3070´are fine, 3090 however has a much bigger gap

**Comment by wwzh2015** [comment]
> I'm curious. I thought Nvidia had crippled 3060s for mining?

It's a so greate work thanks!
