### ISSUE TITLE
System with both AMD and Nvidia cards

### ISSUE THREAD

**Issue by Ed-Yang** [no-fee-ethereum-mining/nsfminer#147]
I have a rig with two Nvidia cards and one AMD cards.  If I run the nsfminer with -G flag,
it will use all of these three cards as OpenCL cards.

I wonder how to run one AMD card with OpenCL kernel and two Nvidia cards with CUDA ?

nsfminer -G --list-devices
 Id Pci Id       Type Name                          CL    Total Memory 
--- ------------ ---- ----------------------------- ----  ------------ 
  0 0000:01:00.0 Gpu  GeForce GTX 1060 6GB          Yes        5.94 GB 
  1 0000:0b:00.0 Gpu  Radeon RX 580 Series          Yes        3.72 GB 
  2 0000:0d:00.0 Gpu  GeForce GTX 1060 6GB          Yes        5.94 GB 

./nsfminer/nsfminer -U --list-devices
 Id Pci Id       Type Name                          CUDA SM   Total Memory 
--- ------------ ---- ----------------------------- ---- ---  ------------ 
  0 0000:01:00.0 Gpu  GeForce GTX 1060 6GB          Yes  6.1       5.94 GB 
  1 0000:0d:00.0 Gpu  GeForce GTX 1060 6GB          Yes  6.1       5.94 GB

**Comment by jean-m-cyr** [comment]
Don't use -U. nsfminer will default to using CUDA for Nvidia and OCL for AMD.
