### ISSUE TITLE
Cable should be included in the source tarball

### ISSUE THREAD

**Issue by iyanmv** [no-fee-ethereum-mining/nsfminer#148]
**Describe the bug**
Building from source will always fail because `cable` is not included in the tarball. This doesn't happen to people cloning the repo with git and using `--recurse-submodules`.

**To Reproduce**
1. Download [the latest source tarball](https://github.com/no-fee-ethereum-mining/nsfminer/archive/refs/tags/v1.3.9.tar.gz)
2. Uncompress, create build folder and try to compile following building instructions
```
cd nsfminer-1.3.9
mkdir build && cd build
cmake ..
```

**Expected behavior**
It works.

**Environment (please complete the following information):**
- Operating System: GNU/Linux

**Comment by jean-m-cyr** [comment]
The instruction at [Building from source](https://github.com/no-fee-ethereum-mining/nsfminer/blob/master/docs/BUILD.md#linux)

**Comment by jean-m-cyr** [comment]
Easier to just clone the repo.
