### ISSUE TITLE
No Temp and Fan readings with --HWMON 2

### ISSUE THREAD

**Issue by efrasyad** [no-fee-ethereum-mining/nsfminer#15]
**Describe the bug**
Running with --HWMON 2 but no temperature and fan reading

<unknown> 12:25 A2188 200.78 Mh - cu0 90.38 0C 0% A1130, cu1 110.40 0C 0% A1058
<unknown> Job: cae9d672 eu1.ethermine.org:5555
<unknown> 12:25 A2188 208.05 Mh - cu0 108.24 0C 0% A1130, cu1 99.81 0C 0% A1058
<unknown> Job: 67f18c5d eu1.ethermine.org:5555
<unknown> 12:25 A2188 195.50 Mh - cu0 99.74 0C 0% A1130, cu1 95.77 0C 0% A1058
<unknown> Job: f2deb2ec eu1.ethermine.org:5555
<unknown> Job: 68704e7e eu1.ethermine.org:5555
<unknown> 12:25 A2188 177.34 Mh - cu0 92.27 0C 0% A1130, cu1 85.07 0C 0% A1058
<unknown> Job: b45a5008 eu1.ethermine.org:5555
<unknown> Job: 87a69ea0 eu1.ethermine.org:5555
<unknown> 12:25 A2188 209.98 Mh - cu0 98.60 0C 0% A1130, cu1 111.37 0C 0% A1058
<unknown> Job: 977f6c24 eu1.ethermine.org:5555
<unknown> 12:25 A2188 198.66 Mh - cu0 98.53 0C 0% A1130, cu1 100.13 0C 0% A1058

**Expected behavior**
Expect to see temperature and fan readings

**Environment (please complete the following information):**
- Operating System: Windows 10 20H2
- Hardware: RTX 3080
- Ethminer Version: nsfminer 1.2.2
- Ethminer options used: --HWMON 2 -v 2 

Thank you for your great work and keeping this project alive.

**Comment by jean-m-cyr** [comment]
Under Linux at least you need to run as root for --HWMON 2

**Comment by efrasyad** [comment]
Hi @jean-m-cyr, I'm using windows10 and tried running command prompt as administrator but still nothing.

**Comment by efrasyad** [comment]
I didn't see it earlier, but I saw this when it started
```
miner 3rd Party: MSVC 19.0.24245.0, CUDA 11.0, Boost 1.75.0, OpenSSL 1.1.1i
 miner 3rd Party: CLI11 1.8.0, Ethash 0.5.0
 miner Failed to obtain all required NVML function pointers
 miner NVIDIA hardware monitoring disabled
 miner Configured pool eu1.ethermine.org:5555
 <unknown> Selected pool eu1.ethermine.org:5555
 <unknown> Stratum mode : Stratum
```

**Comment by jean-m-cyr** [comment]
Yeah, there seem to be many issues with 30XX GPUs. Unfortunately I can't help. I don't have on.

**Comment by jean-m-cyr** [comment]
Additional info regarding this problem at https://github.com/ethereum-mining/ethminer/issues/2087

**Comment by parasyte** [comment]
Same problem on RTX 2080 Ti. It appears to be an API issue, not hardware. I don't think there is anything that I can do with info in that thread; looks like it needs a code change according to https://github.com/ethereum-mining/ethminer/issues/2087#issuecomment-741898645

> Recent releases of NVML.dll have removed API call `nvmlInit` and replaced the function call with `nvmlInit_v2`. Possibly other API interfaces have been dropped/renamed.

https://github.com/no-fee-ethereum-mining/nsfminer/blob/86ab74290623f617a29db2c336f836167f5d086b/libhwmon/wrapnvml.cpp#L64

**Comment by i-p-17** [comment]
For me issue was solved after rebuilding and changing:

> libhwmon/wrapnvml.cpp

`41 #define libnvidia_ml "%WINDIR%/NVIDIA Corporation/NVSMI/nvml.dll"`

to

`41 #define libnvidia_ml "%WINDIR%/System32/nvml.dll"`

I am using Nvidia GTX 1660TI (mobile).
