### ISSUE TITLE
Memory temperature 3080/3090

### ISSUE THREAD

**Issue by akelagit** [no-fee-ethereum-mining/nsfminer#150]
Can add monitor sensor temperature on 3080/3090 and add it in libapi to miner_getstatdetail ?

method in NVMLAPI nvmlReturn_t nvmlDeviceGetFieldValues ( nvmlDevice_t device, int  valuesCount, nvmlFieldValue_t* values ) 

#define NVML_FI_DEV_MEMORY_TEMP 82
Memory temperature for the device.

**Comment by p4rma** [comment]
Yes that would be great.

**Comment by jean-m-cyr** [comment]
PR #157 merged to master. Untested under Windows.

**Comment by akelagit** [comment]
I modified ApiServer.cpp, add TempMem in column
`<< "<th class=right>TempMem</th>"`
`_ret << "<td class=right>" << device["hardware"]["sensors"][3].asString() << "</td>";`

build in Windows 10 and nsfminer dont show temperature memory
![dontTempMem](https://user-images.githubusercontent.com/74584013/112585382-8285cc80-8e1b-11eb-9312-7511284d26c6.jpg)

**Comment by gap370** [comment]
The temperature is 0 for my 3090s. I am in Ubuntu. Is it for any particular driver version? Thanks!

**Comment by akelagit** [comment]
in hwinfo64 show temperature memory. may be need use nvapi for it?
![hwinfo](https://user-images.githubusercontent.com/74584013/112743896-c7913680-8fb4-11eb-8832-2d222e0102e1.jpg)

**Comment by nendonerd** [comment]
hwinfo and gpuz don’t use nvapi to get temps. I’ve run nvapispy to see if both utilities continuously call nvapi to get monitoring metrics, the answer is no. With nvapi you can only get core temp as NvU32, which is 32bit unsigned integer, without any decimal points.

**Comment by akelagit** [comment]
hwinfo use for it i2c bus.I have not found how exactly this is done.

**Comment by jquiros2** [comment]
Possibly related feature request:  https://forums.developer.nvidia.com/t/request-gpu-memory-junction-temperature-via-nvidia-smi-or-nvml-api/168346/92
