### ISSUE TITLE
add command line option to run nsfminer on selected GPU cards

### ISSUE THREAD

**Issue by Ed-Yang** [no-fee-ethereum-mining/nsfminer#155]
Provide the option to run nsfminer on specific GPU(s), so if some of GPU(s) run abnormal, we could
slow down or restart only the fault GPU(s) not all of the GPU(s) belonged to the miner.

ie.  add options like, --cu-devices, --cl-devices.

Thanks in advance.

**Comment by jean-m-cyr** [comment]
The option you are looking for is --devices
