### ISSUE TITLE
performance decrease after patch "don't split DAG unecessarilly"

### ISSUE THREAD

**Issue by Ed-Yang** [no-fee-ethereum-mining/nsfminer#158]
Tested on AMD RX580, if after apply the patch, hashrate decrease about 2Mh/s (from 28.5 to 26.5).

It seems use two dags perform better than one ??

**Comment by jean-m-cyr** [comment]
Makes not difference on Vega or 5700, but will at --cl-split option

**Comment by jean-m-cyr** [comment]
Commit 069d51d adds --cl-split option to force split DAG

**Comment by Ed-Yang** [comment]
If no difference on Vega or 5700 but decrease on rx580, maybe the default should be split and add option "--cl-no-split" ?
