### ISSUE TITLE
Problems with a rig with 6 or more 3070 GPU's

### ISSUE THREAD

**Issue by monsteroid** [no-fee-ethereum-mining/nsfminer#159]
Hi everyone,

if I try to mine with 8 x Asus 3070 GPU's using nsfminer, I am always getting the message CUDA Illegal Memory Access Error. After the DAG's are loaded, sometimes the program stuck or start mining using some of the cards but not all of them. After I stop the programm with CTRL + C, I am getting the error messages.

First I thought, there is a problem with my hardware, but than I tried Phoenix 5.5c and everything worked well. 

Is this a known issue? Should I use a special option? I tried with --seq with nsfminer version 1.3.10 but still got the same error.

I have to say, I am a newbie in this area.

**Environment
- Windows 10
- 8 x RTX Asus Dual 3070
- nsfminer 1.3.8 (until 1.3.10)

**Comment by jean-m-cyr** [comment]
Can you post a copy of the full console log, from start to error?

**Comment by monsteroid** [comment]
I tried to write out the log:

[log.txt](https://github.com/no-fee-ethereum-mining/nsfminer/files/6216067/log.txt)

here is the screenshot from Phoenix:

![Phoenix](https://user-images.githubusercontent.com/81412501/112728952-fc0be080-8f29-11eb-8c2c-29e204f865fd.PNG)

I start nsfminer without any overclocking with following command:

nsfminer -U -P stratum+tcp://user.worker:x@europe.ethash-hub.miningpoolhub.com:20535 --devices 1 2 3 4 5 6 7 8

If I start Phoenixminer, I don't get any errors and the program starts mining. I can't use nsfminer...

**Comment by wwzh2015** [comment]
> nsfminer -U -P stratum+tcp://user.worker:[x@europe.ethash-hub.miningpoolhub.com](mailto:x@europe.ethash-hub.miningpoolhub.com):20535 --devices 1 2 3 4 5 6 7 8

The exactly format is "nsfminer.exe -P stratum1+tcp://0xe0a5a240f268b3f20a274e0fecebeb525f80242f.wwzh@eth.f2pool.com:668t8"

That is the "-U" and "--devices 1 2 3 4 5 6 7 8"?

**Comment by monsteroid** [comment]
It depens on pool. My pool is using username.worker format. I thought the parameter -U is for Nvidia cards..
I have one GPU with 4GB and can't mine with it. It is for windows GUI. That's why the --devices parameter.

I tried the new version 1.3.12 of nsfminer. Sadly, still getting the same error. This time the error says Line 318. Sometimes it works, but one gpu (everytime random) is giving an error. 
I would really like to use nsfminer for mining. Am I the only one having this problem? Should I change my system from windows to ubuntu? Would it make a difference?

**Comment by dedizones** [comment]
489 badshare .... ??

You have a problem, and it does not bother you to send bad actions and dirty the networks ...
Review your OC already regardless of your mining software

**Comment by Minerx117** [comment]
also having issiue with 5x3070 1x3060ti rig compared to ethminer with cuda 11.2 ethminer runs well..

ethminer with cuda11.2 support
https://github.com/Minerx117/ethminer/releases

**Comment by grenelt** [comment]
Because i have a very similar error with a bunch of RX5700 with 8GB system RAM:

Please make sure Windows has enough virtual memory at stake. I use a manual configuration with 16384 minimum and 32768 maximum for 5 videocards. I didn't test if lower values also work.

I can't pin down if this is a flaw of nsfminer or a problem with the windows memory allocation.
