### ISSUE TITLE
Any hope of adding something to limit mining intensity?

### ISSUE THREAD

**Issue by Lutzy** [no-fee-ethereum-mining/nsfminer#162]
**Is your feature request related to a problem? Please describe.**
So one thing I've noticed in Linux is that when I was using an AMD card, specifically the 6900 XT, I could mine full throttle and experience no reduction in performance in the desktop environment. Hell, I could even fire up League of Legends in wine and get 80 FPS. With my 3090 and the Nvidia drivers, while mining I get hiccups all over the place in the desktop. It'd be nice to be able to go full-throttle while not actively using the desktop, and reserving a little wiggle room when the PC is being actively used.

**Describe the solution you'd like**
A startup parameter that limits GPU utilization to some threshold.

**Comment by jean-m-cyr** [comment]
No plans.
