### ISSUE TITLE
No Accepted Shares Issue on RTX 3070

### ISSUE THREAD

**Issue by MOVZX** [no-fee-ethereum-mining/nsfminer#17]
**Describe the bug**
Tried to mine with RTX 3070 on NiceHash, it's givine me Rejected Shares (rejected reason: 1 Share above target).

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/3374397/105622035-38469600-5e40-11eb-87d7-f7050be4347e.png)

**Environment (please complete the following information):**
- Operating System: Windows 10
- Hardware:  RTX 3070
- nsfminer version: 1.2.3
- nsfminer options used: nsfminer.exe --cuda --pool stratum2+tcp://3Lqzke2pgnsDUgTgHZb3dkFyvqKgGwdFpv.Test@daggerhashimoto.eu.nicehash.com:3353 --HWMON 2

**Comment by MOVZX** [comment]
Tried to mine on Ethermine too, no Accepted Shares at all.

![image](https://user-images.githubusercontent.com/3374397/105622153-6a0c2c80-5e41-11eb-991f-6047e02af02d.png)

**Comment by MOVZX** [comment]
Working fine on T-Rex, so it's not my GPU/system.

![image](https://user-images.githubusercontent.com/3374397/105622254-8c527a00-5e42-11eb-944e-ad6b729e8bbe.png)

No issue with Phoenix Miner too.

![image](https://user-images.githubusercontent.com/3374397/105622291-e5221280-5e42-11eb-87ae-f65872e594e9.png)

**Comment by jean-m-cyr** [comment]
Unfortunately can't help. Don't have any 30XX cards.

**Comment by jean-m-cyr** [comment]
I'll look into the nicehash issue next. Odd that it would generate rejected shares for Nicehash but none for Ethermine.
It'd be good to know the difficulty level shown at startup for Ethermine, it should be 4.0 GH

**Comment by MOVZX** [comment]
It's working now, I've just updated to v1.2.4. I can now mine on NiceHash.
