### ISSUE TITLE
Random Crashes

### ISSUE THREAD

**Issue by bufothefrog** [no-fee-ethereum-mining/nsfminer#172]
Hello, I am having an issue where the application will randomly crash about every other night. It doesn't seem to have a log that I can check for errors

**Comment by jean-m-cyr** [comment]
Not much we can do without more details. A console log at minimum.

**Comment by bufothefrog** [comment]
I'll relaunch it with logging on windows via `nsfminer.exe "arguments" >nsfminer.txt` for now. Is there any better way to do this or should this be sufficient?

**Comment by bufothefrog** [comment]
Okay, it crashed again. Here is the log output as it failed:
 [93mminer [0mSocket read failed: The network connection was aborted by the local system
 [97mminer [0mDisconnected from eth-us-west.flexpool.io:5555
 [97mminer [0mNo connection. Suspend mining ...
 [97mminer [0mSelected pool eth-us-west.flexpool.io:5555
 [93mminer [0mCould not resolve host eth-us-west.flexpool.io, The requested name is valid, but no data of the requested type was found
 [97mminer [0mDisconnected from eth-us-west.flexpool.io:5555
 [97mminer [0mNo connection. Suspend mining ...
 [97mminer [0mSelected pool eth-us-west.flexpool.io:5555
 [93mminer [0mCould not resolve host eth-us-west.flexpool.io, The requested name is valid, but no data of the requested type was found
 [97mminer [0mDisconnected from eth-us-west.flexpool.io:5555
 [97mminer [0mNo connection. Suspend mining ...
 [97mminer [0mSelected pool eth-us-west.flexpool.io:5555
 [93mminer [0mCould not resolve host eth-us-west.flexpool.io, The requested name is valid, but no data of the requested type was found
 [97mminer [0mDisconnected from eth-us-west.flexpool.io:5555
 [97mminer [0mNo connection. Suspend mining ...
 [97mminer [0mNo more connections to try. Exiting...
 [97mminer [0mShutting down miners...

**Comment by bufothefrog** [comment]
It seems to have closed because of internet issues, but I'll run another test to see if this is whats actually causing it. In the meantime, is there any way to have it keep attempting to reconnect?

**Comment by Ed-Yang** [comment]
try to pull the latest code and add these options:

--retry-max 0 --retry-delay 3

**Comment by jean-m-cyr** [comment]
So, problem solved... I think?
closing
