### ISSUE TITLE
Confused about status of this project vs ethminer

### ISSUE THREAD

**Issue by lostmsu** [no-fee-ethereum-mining/nsfminer#175]
This looks like it was originally the fork of ethminer (BTW, why does it not look like one on GitHub), created because ethminer was no longer maintained.

But now @jean-m-cyr appears to be able to commit to the original repository also.

[Google trends](https://trends.google.com/trends/explore?geo=US&q=ethminer,nsfminer) shows search volume for nsfminer to be negligible in comparison. What I am getting to is why not simply move the development back to ethminer repository?

**Comment by jean-m-cyr** [comment]
Because it takes a second contributor to commit anything to Ethminer. There is no one left willing and able to do that for the Ethminer repo.
