### ISSUE TITLE
No OpenCL Platforms found - AMD GPU Driver Issue

### ISSUE THREAD

**Issue by aaron13223** [no-fee-ethereum-mining/nsfminer#182]
Hey,

Just tested this out on Windows, mining with Nvidia works but it shows "No OpenCL Platforms found" for the AMD GPU. I looked it up and it seems to be an issue with ETHMiner itself which requires older AMD Drivers. Might be worth looking into if you can fix it. Thanks a lot.

Note: I've the Adrenalin 2020 Edition 21.3.1 drivers installed.

**Comment by wwzh2015** [comment]
I have the same problem！ I have link nsfminer.exe to APP SDK3.0（opencl 2.0）

**Comment by jean-m-cyr** [comment]
If it's for Windows I can't help.

**Comment by aaron13223** [comment]
@jean-m-cyr hahaha okay. Thanks for the help!
