### ISSUE TITLE
"OpenCL 1.1 Mesa 20.3.5 not supported"

### ISSUE THREAD

**Issue by bufothefrog** [no-fee-ethereum-mining/nsfminer#185]
Hello I am getting this output on Fedora 33 with a 5700xt:

`15:08:30 cl-0  OpenCL OpenCL 1.1 Mesa 20.3.5 not supported, but platform Clover might work nevertheless. USE AT OWN RISK!`
`15:08:30 cl-0  Using Pci : ����WU (OpenCL 1.1 Mesa 20.3.5) Memory : 8.00 GB`
`15:08:40 cl-0  Required GPU mem: Total 4.24 GB, Cache 66.75 MB, DAG 4.17 GB, Miscellaneous 60.00 B`
`15:08:40 cl-0  OpenCL kernel build log:`
`fatal error: cannot open file '/usr/lib64/clc//gfx1010-amdgcn-mesa-mesa3d.bc': No such file or directory
15:08:40 cl-0`
`OpenCL kernel build error (-11):`
`clBuildProgram`

**Comment by jean-m-cyr** [comment]
OpenCL 1.1 is not supported.
