### ISSUE TITLE
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by chenjy1** [no-fee-ethereum-mining/nsfminer#188]
Hi, I meet the error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found
OS: Debian 
Cuda: Cuda compilation tools, release 11.1, V11.1.74
GPU: Tesla V100 *4
how can I solve this problem?

**Comment by jean-m-cyr** [comment]
I run Ubuntu and whatever mmp-os uses. No idea on Debian.

**Comment by Ed-Yang** [comment]
Try this:

sudo apt-get  install libc6-dev
