### ISSUE TITLE
API returns HTML instead of JSON

### ISSUE THREAD

**Issue by phaked** [no-fee-ethereum-mining/nsfminer#197]
I just tinkered with the API using python and the request package from pip. However, no matter what GET request I send, I receive HTML docs instead of a json strings. I checked the current implementation of ApiConnection::onRecvSocketDataCompleted in ApiServer.cpp. It seems that any HTTP GET request, even if it contains json payload, is matched in line 589:

```c++
if (regex_search(m_message, http_matches, http_pattern, regex_constants::match_default))
```
Thus, we never reach the else case where the jsonrpc processing takes place.

**Comment by jean-m-cyr** [comment]
Correct, we don't look inside html requests.
