### ISSUE TITLE
Porting nsfminer to ravencoin

### ISSUE THREAD

**Issue by jstkdng** [no-fee-ethereum-mining/nsfminer#200]
The current open source miner for ravencoin (kawpowminer) is based on old ethminer. Since this is an updated etminer I wanted to know if it was possible to add support for ravencoin on nsfminer.

**Comment by jean-m-cyr** [comment]
Why not use kapowminer if it already supports ravencoin?

**Comment by jstkdng** [comment]
kawpowminer's opencl performance is bad, I think due to it being based on old ethminer as old ethminer also has reduced eth performance on opencl compared to nsfminer (at least for me).
On teamredminer my gpu can reach 20 Mh/s but on kawpowminer it only reaches 4Mh/s.

**Comment by jean-m-cyr** [comment]
You are using AMD gpus. trminer uses highly optimized binary kernels that openCL can't match.

**Comment by jstkdng** [comment]
nsfminer can match trm's eth performance though.

**Comment by jean-m-cyr** [comment]
Not at all. Trminer on vega makes 50MH/S at lower power than nsfminer at much lower HR. On 5700XT about the same hash rate, but nsfminer uses more power. Personally I use trminer on both of my AMD GPUs. Best HR/PWR ratio!

**Comment by jstkdng** [comment]
oh, you mean hashes per watt, I was just looking at the hashrate. At least on my rtx rigs nsfminer manages to reach trex's performance (hash/watt).

**Comment by jean-m-cyr** [comment]
What model GPUs are we talking about?

**Comment by jstkdng** [comment]
I have 3 rtx 3070s, 2 rtx 3080s and a 5600XT.
The 3070s reach 60 at 130w and the 3080s reach 100 on 230w

**Comment by jean-m-cyr** [comment]
Trminer does not support Nvidia, so apples and oranges. My 5700XT gets the same hash rate under trminer and nsfminer. Trminer doesn't do much for Navi in terms of hash rate but reduces the power consumption a little.

**Comment by grenelt** [comment]
I tried trminer for windows with my rig with 5 Navi 10 cards - i can't get it working with more than 3 cards, the 4th or 5th card crashes while generatig DAG - but it's not a power problem (about 1500 W for 5 cards), ethminer and nsfminer work, also with generating DAG for all cards at the same time.
With only 2 RX5700 trminer reaches 55+ MH/s and nsfminer is at about 53+ MH/s with the same cards. So there is a difference with the A/B mode thing, but also with stability and compatibility.
