### ISSUE TITLE
Getting No response received in 2 seconds nicehash pool

### ISSUE THREAD

**Issue by gilvbp** [no-fee-ethereum-mining/nsfminer#201]
runing on linux, nsfminer -P stratum2+tcp://mybitconwalletaddress.worker2@daggerhashimoto.usa.nicehash.com:3353 i´m getting 

10:59:54 miner nsfminer 1.3.12-18+commit.2d15c08d (No stinkin' fees edition)
10:59:54 miner Copyright 2021 Jean M. Cyr, Licensed under the terms
10:59:54 miner  of the GNU General Public License Version 3
10:59:54 miner https://github.com/no-fee-ethereum-mining/nsfminer
10:59:54 miner Build: linux/release/gnu
10:59:54 miner 3rd Party: GCC 10.2.0, CUDA 11.3, Boost 1.75.0
10:59:54 miner 3rd Party: OpenSSL 1.1.1j, Ethash 0.5.0
10:59:54 miner Running as user: gil
10:59:54 miner Configured pool daggerhashimoto.usa.nicehash.com:3353
10:59:54 miner Selected pool daggerhashimoto.usa.nicehash.com:3353
10:59:57 miner No response received in 2 seconds.
10:59:57 miner Disconnected from daggerhashimoto.usa.nicehash.com:3353
10:59:57 miner No connection. Suspend mining ...
10:59:57 miner Selected pool daggerhashimoto.usa.nicehash.com:3353
10:59:59 miner 0:00 A0 0.00 h - 
11:00:00 miner No response received in 2 seconds.
11:00:00 miner Disconnected from daggerhashimoto.usa.nicehash.com:3353
11:00:00 miner No connection. Suspend mining ...
11:00:00 miner Selected pool daggerhashimoto.usa.nicehash.com:3353
11:00:03 miner No response received in 2 seconds.
11:00:03 miner Disconnected from daggerhashimoto.usa.nicehash.com:3353
11:00:03 miner No connection. Suspend mining ...
11:00:03 miner No more connections to try. Exiting...

Could anyone help?

**Comment by jean-m-cyr** [comment]
The following parameters work for me!

-P stratum2+tcp://1Lgd9h9g2xHHkXTMu4u8LmNdk1W6br12x.miner0@daggerhashimoto.usa.nicehash.com:3353

**Comment by gilvbp** [comment]
It was my Asus  Router AI Protection! thanks!
