### ISSUE TITLE
CUDA error on RTX 3060 - Linux Debian

### ISSUE THREAD

**Issue by RBouhl** [no-fee-ethereum-mining/nsfminer#211]
I'm trying to install and run nsfminer on a Geforce RTX 3060. I followed the build instruction for Linux and nsfminer did build.
However this is what happens when I try to benchmark :

$./nsfminer -M 100000

09:07:05 miner nsfminer 1.3.13-7+commit.999fed84 (No stinkin' fees edition)
09:07:05 miner Copyright 2021 Jean M. Cyr, Licensed under the terms
09:07:05 miner  of the GNU General Public License Version 3
09:07:05 miner https://github.com/no-fee-ethereum-mining/nsfminer
09:07:05 miner Build: linux/release/gnu
09:07:05 miner 3rd Party: GCC 8.3.0, CUDA 11.2, Boost 1.75.0
09:07:05 miner 3rd Party: OpenSSL 1.1.1j, Ethash 0.5.0
09:07:05 miner Running as user: remi
No OpenCL platforms found
09:07:05 miner Selected pool localhost:0
09:07:05 miner Established connection to localhost:0
09:07:05 miner Spinning up miners...
09:07:05 cu-0  Using Pci 0000:01:00.0: Graphics Device (Compute 8.6) Memory : 11.77 GB
09:07:05 sim   Epoch : 3 Difficulty : 4.29 Gh
09:07:05 sim   Job: c43dff77 blk: 100000 localhost:0
09:07:06 cu-0  Required GPU mem: Total 1.04 GB, Cache 16.37 MB, DAG 1.02 GB, Miscellaneous 56.00 B
09:07:06 cu-0  **Unexpected error CUDA error in func set_constants at line 104 invalid device symbol on CUDA device 0000:01:00.0**
09:07:06 cu-0  Mining suspended ...

I have the following version of cuda : 

```
$dpkg -l | grep cuda

ii  libcuda1:amd64                            460.67-1~bpo10+1             
ii  libcudart11.0:amd64                       11.2.146~11.2.1-2~bpo10+1    
ii  libnvidia-tesla-460-cuda1:amd64           460.32.03-2~bpo10+1          
ii  nvidia-cuda-dev:amd64                     11.2.1-2~bpo10+1             
ii  nvidia-cuda-gdb                           11.2.135~11.2.1-2~bpo10+1    
ii  nvidia-cuda-toolkit                       11.2.1-2~bpo10+1             
ii  nvidia-cuda-toolkit-doc                   11.2.1-2~bpo10+1            
```

**Comment by jean-m-cyr** [comment]
No idea! I don't have a tesla GPU to test with.

**Comment by VoltaVX** [comment]
I have the same error, I'm believing that using any CUDA version over 11.2 is the problem. I'm using CUDA 11.3 and I get this problem

**Comment by edurenye** [comment]
I have the RTX 3060 with CUDA 11.2 and I don't get this error, however the hash-rate is really low, most of the time around 21 MH/s I was getting better results with the RTX 2060 which points that something is wrong.

**Comment by lerasah** [comment]
> I have the RTX 3060 with CUDA 11.2 and I don't get this error, however the hash-rate is really low, most of the time around 21 MH/s I was getting better results with the RTX 2060 which points that something is wrong.

RTX 3060 is very troublesome.. should be connected to either a PCIe x8 or x16 slot. Should have 14.05 drivers installed.. should be connected to a display output (or atleast a dummy HDMI plug).. if none of these primary requirements are met, fix them before filing a bug.

**Comment by edurenye** [comment]
Hi @lerasah, thanks for your answer.
My RTX 3060 is connected to a PCIe x16, has a display output, but regarding the driver, I have driver version: 460.80, I can't find any version numbered 14.05 and that does not seem to follow the Nvidia drivers numeration. Where do I find this driver?

**Comment by lerasah** [comment]
> Hi @lerasah, thanks for your answer.
> My RTX 3060 is connected to a PCIe x16, has a display output, but regarding the driver, I have driver version: 460.80, I can't find any version numbered 14.05 and that does not seem to follow the Nvidia drivers numeration. Where do I find this driver?

Extremely sorry.. its 470.05

Use at your own risk. Happy Mining
- https://drive.google.com/file/d/1kL03Fp_dMYLtvyGt2g97shSXZcTk-TJU/view?usp=sharing
- https://mega.nz/file/O0J0wTbL#4g277f8BC7GjxFmgoAFV4K6dMgOqFFtb8tEdTI0jHqQ

**Comment by edurenye** [comment]
This driver is for Windows :disappointed:

**Comment by Titaniumtown** [comment]
I know other people who use nvidia report this issue as well.
