### ISSUE TITLE
Reconnecting after connection loss

### ISSUE THREAD

**Issue by sruPL** [no-fee-ethereum-mining/nsfminer#216]
Is there any command that I am missing or chance to add auto-reconnect for nsfminer? From what I've seen it tries to reconnect 3 times within a short timespan. My internet is very unstable and it dc's on average for like a minute once per day or so. So far I had to re-launch it manually each time, contrary to other mining software attempting reconnect every minute or in some time intervals continuously. Thanks in advance.

**Comment by b4rt1911** [comment]
--retry-delay=2 --retry-max=0

or https://w-shadow.com/blog/2009/03/04/restart-on-crash/
