### ISSUE TITLE
Add support ETCHASH !

### ISSUE THREAD

**Issue by dedizones** [no-fee-ethereum-mining/nsfminer#223]
Hello, I wanted to try ETC, and I notice that it does not work.
Is it possible to add the protocol please?

**Comment by jean-m-cyr** [comment]
Would require that I include the Ethash repo, which I do not control, and modify it. So not a high priority.

**Comment by dedizones** [comment]
OK many tks, ;)

**Comment by joequant** [comment]
FYI this is a discussion on this topic in ethereum-mining/ethminer#2080

What they do is to just compile with an alternative version of etchash.  Getting it to work with both ethash and etchash is a bit tricky.

**Comment by Titaniumtown** [comment]
Anyone who's interested, test: https://github.com/Titaniumtown/nsfminer/tree/etchash and see if that works.

**Comment by codeholic** [comment]
@Titaniumtown Why don't you open a merge request?
