### ISSUE TITLE
low hashrate rx580

### ISSUE THREAD

**Issue by chamalz** [no-fee-ethereum-mining/nsfminer#229]
my rx580 hashrate in other minig software is 30Mhs but in nsfminer is 27 MHS 
my os : win 10

**Comment by Mosccc** [comment]
Same here.

**Comment by chamalz** [comment]
any solution?

**Comment by jimmystewpot** [comment]
What other miners are giving you higher hash rates, on what operating system and with what release version?

**Comment by chamalz** [comment]
PhoenixMiner4.9c give 30 mh/s hash rate 
os : windows 10

**Comment by jimmystewpot** [comment]
I can confirm that this is the case with my test rig.

On Ubuntu 20.04 and Windows 10 I see a drop in mining performance when compared to ethminer using opencl without binary kernel etc in ethminer.
* I've tried with and without split-dag.
* Same driver versions in both cases
