### ISSUE TITLE
Radeon VII slow hashrate.

### ISSUE THREAD

**Issue by lesjokolat** [no-fee-ethereum-mining/nsfminer#23]
On ububntu 18.04.5

I get a warning message

 miner Build: linux/release/gnu
 miner 3rd Party: GCC 7.5.0, Boost 1.75.0, OpenSSL 1.1.1i
 miner 3rd Party: Ethash 0.5.0
Unrecognized platform Portable Computing Language

Hashrate is about 46MH which is about half expected.

Clinfo if it helps:

Number of platforms                               2
  Platform Name                                   Portable Computing Language
  Platform Vendor                                 The pocl project
  Platform Version                                OpenCL 1.2 pocl 1.1 None+Asserts, LLVM 6.0.0, SPIR, SLEEF, DISTRO, POCL_DEBUG
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd
  Platform Extensions function suffix             POCL

  Platform Name                                   AMD Accelerated Parallel Processing
  Platform Vendor                                 Advanced Micro Devices, Inc.
  Platform Version                                OpenCL 2.1 AMD-APP (3180.7)
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd cl_amd_event_callback cl_amd_offline_devices 
  Platform Host timer resolution                  1ns
  Platform Extensions function suffix             AMD

  Platform Name                                   Portable Computing Language
Number of devices                                 0

  Platform Name                                   AMD Accelerated Parallel Processing
Number of devices                                 1
  Device Name                                     gfx906
  Device Vendor                                   Advanced Micro Devices, Inc.
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 2.0 AMD-APP (3180.7)
  Driver Version                                  3180.7 (PAL,HSAIL)
  Device OpenCL C Version                         OpenCL C 2.0 
  Device Type                                     GPU
  Device Board Name (AMD)                         AMD Radeon VII
  Device Topology (AMD)                           PCI-E, 07:00.0
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               60
  SIMD per compute unit (AMD)                     4
  SIMD width (AMD)                                16
  SIMD instruction width (AMD)                    1
  Max clock frequency                             1803MHz
  Graphics IP (AMD)                               9.6
  Device Partition                                (core)
    Max number of sub-devices                     60
    Supported partition types                     None
  Max work item dimensions                        3
  Max work item sizes                             1024x1024x1024
  Max work group size                             256
  Preferred work group size (AMD)                 256
  Max work group size (AMD)                       1024
  Preferred work group size multiple              64
  Wavefront width (AMD)                           64

thanks

**Comment by jean-m-cyr** [comment]
How slow?

**Comment by lesjokolat** [comment]
Hi thanks for looking at this. Its at around 46MH now. but typically should be 88 or so regular no overclocking.

**Comment by jean-m-cyr** [comment]
I doubt it will help, but does --cu-streams 4 --cu-block 256 make any difference?

**Comment by lesjokolat** [comment]
hi i tried both each and in combination but were not able to use tehm.

Error: unrecognised option

**Comment by smefa** [comment]
I also get exactly half the hashrate with my rtx 3070 compared to other miners. Tried --cu-streams 4 --cu-block 256 but it did not do any difference.

**Comment by waitforeit** [comment]
Not that it's super helpful, but also adding in with the same issue.. two Win 10 rigs, both with new 3070's (one MSI one Gigabyte), both getting half the hash rate (or less) using nsfminer than using other miners.

**Comment by lesjokolat** [comment]
If they are not found it uses a generic?

**Comment by lesjokolat** [comment]
Hi I am unsure how to quantify it myself.
What I do know.
Other mining apps do have a more normal mining speed hashrate range on same PC and GPU.
I reinstalled AMD linux driver in case it was a install issue but all seems ok. as well as open CL. I used PAL and not legacy option.

If i can provide any further output to assist happy to. regards and thanks

**Comment by Artem-B** [comment]
@lesjokolat Radeon would use OpenCL, not CUDA, so `--cu*` arguments will not work.  Try running with ` -G --cl-work 256`

@smefa try using OpenCL mode. It gives me noticeably better results than CUDA on rtx3080.

**Comment by lesjokolat** [comment]
@Artem-B 

Hi i gave it a try.

-G --cl-work 256
-G --cl-work 128
-G --cl-work 64

all were around 46MH tops no luck.

**Comment by nn47nn** [comment]
also half hashrate on my 3080 - 55mh
--cu-streams 4 --cu-block 256 no change
builds ethereum appveyor №37485839 gives me 94 mh

**Comment by Minerx117** [comment]
i have have tested every release of nsfminer on RTX2080 RTX3060ti and RX5700XT all are getting around 30-40% lower hashrate compared to all other mining applications..

**Comment by jean-m-cyr** [comment]
Couple of issues here, Nvidia or AMD? Linux or Windows. I don't do Windows so I can't hep there, as for hash rates on AMD, specially for Vega, no miner beats TeamRed on hash rate and power. On Linux, we match TR for Navi GPUs and they don't support NV.

**Comment by jean-m-cyr** [comment]
Contemplating whether or not to even claim support for Windows. I honestly can' test under Windows and am uncomfortable with even providing pre-built images for it.

**Comment by Minerx117** [comment]
yes Amd and Nvidia.. 5700xt and 3060ti also tested on rtx2080 to confirm all test down under windows i don't use linux..

**Comment by gpiez** [comment]
I had some difficulty building for Windows, but other than that, it seems to run fine.
55 MH with a RX5700 (AMD, OpenCL)
62 MH with a RTX3070 (Nvidia, Cuda)
Default parameters otherwise. Unfortunately I don't have a 3080 to test with :-)

**Comment by parasyte** [comment]
FWIW I have tuned my GPUs on Windows and currently running with:

- RTX 3090: 114.5 MH/s @ 280 W
- RTX 2080 Ti: 53.2 MH/s @ 142 W

I was able to get an RX 5700 XT up to 66 MH/s at about 110 W, but it was creating invalid shares. Had to tune it down to the 55 MH/s range. I'm only able to get around 50 MH/s on Linux with the same hardware, and almost any tuning I do is unstable and causes crashes (instability is not nsfminer's fault).

**Comment by Minerx117** [comment]
v1.3.4 and v1.3.5 are working at correct speeds now..

**Comment by lesjokolat** [comment]
hi still having issues now its this wont mine:

 miner nsfminer 1.3.5+commit.811f00e5 (No stinkin' fees edition)
 miner Copyright 2021 Jean M. Cyr, Licensed under the terms
 miner  of the GNU General Public License Version 3
 miner https://github.com/no-fee-ethereum-mining/nsfminer
 miner Build: linux/release/gnu
 miner 3rd Party: GCC 7.5.0, Boost 1.75.0
 miner 3rd Party: OpenSSL 1.1.1i, Ethash 0.5.0
 miner Configured pool eth.digipools.org:3102
 miner Configured pool :0
 miner Selected pool :0
terminate called after throwing an instance of 'boost::wrapexcept<boost::system::system_error>'
  what():  Invalid argument
Aborted (core dumped)

**Comment by Minerx117** [comment]
> I had some difficulty building for Windows, but other than that, it seems to run fine.
> 55 MH with a RX5700 (AMD, OpenCL)
> 62 MH with a RTX3070 (Nvidia, Cuda)
> Default parameters otherwise. Unfortunately I don't have a 3080 to test with :-)

my 5700xts are only getting 42mhs what drivers are you using? i have memory timing modded  and geting 55mhs in other apps but not this one atm..

**Comment by Minerx117** [comment]
updating to latest amd21.2.2 driver fixed the amd hashrate for my 9x5700xt rig all cards now hashing at 55mhs 3060ti (361.40) at 61mhs all my of been driver related problems for me

**Comment by SimonBrazell** [comment]
This is still an issue, I'm seeing hash rates of 27MH/s reported by nsfminer on a Nvidia 1080ti running on Windows 10. Should be closer to 45MH/s.
