### ISSUE TITLE
Network errors suspending mining

### ISSUE THREAD

**Issue by SuperNovaa41** [no-fee-ethereum-mining/nsfminer#232]
I know this is a feature, however often times ISPs can be a bit unstable, and losing a connection for a couple minutes means stopping mining for the next x amount of hours until you realize. Many other miners just continue to ping for a request and then begin mining again, which is a far better approach than immediately suspending the miner.

**Comment by benjaminbenito** [comment]
You can see at this link all the option : https://github.com/no-fee-ethereum-mining/nsfminer/blob/master/docs/Options.md

I think add : 

  --retry-max arg (=0)         Set number of reconnection retries to same pool.
                               Set to 0 for infinite retries.
  --work-timeout arg (=3600)    If no new work received from pool after this 
                               amount of time the connection is dropped. Value 
                               expressed in seconds.
  --response-timeout arg (=3600)  If no response from pool to a stratum message 
                               after this amount of time the connection is 
                               dropped
