### ISSUE TITLE
Hashrate report doesn't work on Ethermine

### ISSUE THREAD

**Issue by br3w0r** [no-fee-ethereum-mining/nsfminer#233]

**Comment by Conzar** [comment]
Have you tried:
```  --report-hashrate```

**Comment by igoralebar** [comment]
or simply -R

**Comment by benjaminbenito** [comment]
Just add -R .
I use this in my .bat script in Ethermine this work well.
![image](https://user-images.githubusercontent.com/61283886/120207878-3a28c780-c22d-11eb-9ae8-c5a6a95c3403.png)
