### ISSUE TITLE
/home/grey/nsfminer/libcl/CLMiner.cpp:13:10: fatal error: ethash/ethash.hpp: No such file or directory

### ISSUE THREAD

**Issue by greysilly7** [no-fee-ethereum-mining/nsfminer#234]
When I ran ``sudo make install`` I keep getting this

grey@<RedactedMyName>-Desktop:~/nsfminer/build$ sudo make install
make[1]: Entering directory '/home/grey/nsfminer/build'
make[2]: Entering directory '/home/grey/nsfminer/build'
Scanning dependencies of target nsfminer-buildinfo-git
make[2]: Leaving directory '/home/grey/nsfminer/build'
make[2]: Entering directory '/home/grey/nsfminer/build'
make[2]: Leaving directory '/home/grey/nsfminer/build'
[  0%] Built target nsfminer-buildinfo-git
make[2]: Entering directory '/home/grey/nsfminer/build'
[  2%] Updating nsfminer-buildinfo:
       Project Version:  1.3.13-13+commit.aa47722b (prerelease)
       System Name:      linux
       System Processor: x86_64
       Compiler ID:      gnu
       Compiler Version: 10.2.0
       Build Type:       release
       Git Info:         1.3.13 13 aa47722b7c59763c2ee7b8d614745c84749b2bac
       Timestamp:        2021-05-12T18:03:21
Scanning dependencies of target nsfminer-buildinfo
make[2]: Leaving directory '/home/grey/nsfminer/build'
make[2]: Entering directory '/home/grey/nsfminer/build'
[  5%] Building C object CMakeFiles/nsfminer-buildinfo.dir/nsfminer/buildinfo.c.o
[  8%] Linking C static library nsfminer/libnsfminer-buildinfo.a
make[2]: Leaving directory '/home/grey/nsfminer/build'
[  8%] Built target nsfminer-buildinfo
make[2]: Entering directory '/home/grey/nsfminer/build'
Scanning dependencies of target dev
make[2]: Leaving directory '/home/grey/nsfminer/build'
make[2]: Entering directory '/home/grey/nsfminer/build'
[ 10%] Building CXX object libdev/CMakeFiles/dev.dir/CommonData.cpp.o
[ 13%] Building CXX object libdev/CMakeFiles/dev.dir/FixedHash.cpp.o
[ 16%] Building CXX object libdev/CMakeFiles/dev.dir/Log.cpp.o
[ 18%] Building CXX object libdev/CMakeFiles/dev.dir/Worker.cpp.o
[ 21%] Linking CXX static library libdev.a
make[2]: Leaving directory '/home/grey/nsfminer/build'
[ 21%] Built target dev
make[2]: Entering directory '/home/grey/nsfminer/build'
Scanning dependencies of target hwmon
make[2]: Leaving directory '/home/grey/nsfminer/build'
make[2]: Entering directory '/home/grey/nsfminer/build'
[ 24%] Building CXX object libhwmon/CMakeFiles/hwmon.dir/wraphelper.cpp.o
[ 27%] Building CXX object libhwmon/CMakeFiles/hwmon.dir/wrapnvml.cpp.o
[ 29%] Building CXX object libhwmon/CMakeFiles/hwmon.dir/wrapadl.cpp.o
[ 32%] Building CXX object libhwmon/CMakeFiles/hwmon.dir/wrapamdsysfs.cpp.o
[ 35%] Linking CXX static library libhwmon.a
make[2]: Leaving directory '/home/grey/nsfminer/build'
[ 35%] Built target hwmon
make[2]: Entering directory '/home/grey/nsfminer/build'
[ 37%] Generating OpenCL Kernel Byte Array
Scanning dependencies of target cl
make[2]: Leaving directory '/home/grey/nsfminer/build'
make[2]: Entering directory '/home/grey/nsfminer/build'
[ 40%] Building CXX object libcl/CMakeFiles/cl.dir/CLMiner.cpp.o
/home/grey/nsfminer/libcl/CLMiner.cpp:13:10: fatal error: ethash/ethash.hpp: No such file or directory
   13 | #include <ethash/ethash.hpp>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [libcl/CMakeFiles/cl.dir/build.make:67: libcl/CMakeFiles/cl.dir/CLMiner.cpp.o] Error 1
make[2]: Leaving directory '/home/grey/nsfminer/build'
make[1]: *** [CMakeFiles/Makefile2:522: libcl/CMakeFiles/cl.dir/all] Error 2
make[1]: Leaving directory '/home/grey/nsfminer/build'
make: *** [Makefile:152: all] Error 2

**Comment by coffnix** [comment]
same error here after enable opencl support (cuda disabled):

cmake .. -DETHASHCUDA=OFF -DETHASHCL=ON ; make

[ 70%] Generating OpenCL Kernel Byte Array
Scanning dependencies of target cl
[ 72%] Building CXX object libcl/CMakeFiles/cl.dir/CLMiner.cpp.o
/home/coffnix/nsfminer/libcl/CLMiner.cpp:13:10: fatal error: ethash/ethash.hpp: No such file or directory
   13 | #include <ethash/ethash.hpp>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [libcl/CMakeFiles/cl.dir/build.make:86: libcl/CMakeFiles/cl.dir/CLMiner.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:541: libcl/CMakeFiles/cl.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 75%] Linking CXX static library libpool.a
[ 75%] Built target pool
make: *** [Makefile:171: all] Error 2

**Comment by coffnix** [comment]
solved after move all files from ethash/include/ethash to ethash directory

**Comment by greysilly7** [comment]
i see

**Comment by mitchweaver** [comment]
> solved after move all files from ethash/include/ethash to ethash directory

```
# bug: https://github.com/no-fee-ethereum-mining/nsfminer/issues/234
cp -rf ../ethash/include/ethash/* ../ethash/
```
thanks

**Comment by jean-m-cyr** [comment]
Fixed now
