### ISSUE TITLE
Using hunter_config() to build with the latest ethash (0.6.0)

### ISSUE THREAD

**Issue by fbzhong** [no-fee-ethereum-mining/nsfminer#236]
Hi,

I'd like to suggest using the following config to build with the latest ethash (0.6.0) package instead of copy src into git:

Add the following text into **cmake/config.cmake**:
```cmake
hunter_config(ethash URL "https://github.com/chfast/ethash/archive/refs/tags/v0.6.0.tar.gz" SHA1 "4bfa26b389d1f89a60053de04b2a29feab20f67b" VERSION "0.6.0")
```

Enjoy the latest ethash lib.

**Comment by jean-m-cyr** [comment]
That is what was done previously. However I need Ethash modifications.
