### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by xgnom666x** [no-fee-ethereum-mining/nsfminer#24]
I beg your pardon right away, but, probably, I am not writing in the correct format. I have not yet fully learned how to work with github correctly.
https://github.com/no-fee-ethereum-mining/nsfminer/blob/170dd7cb67cd245dc4214472f3ca27d45763b667/nsfminer/main.cpp#L400
help-ext --> help-module

PS.and sorry for my english.

**Comment by jean-m-cyr** [comment]
Thanks
