### ISSUE TITLE
GPU device count starts from 0 or 1?

### ISSUE THREAD

**Issue by Shashank066** [no-fee-ethereum-mining/nsfminer#247]
I get "gpu 1" overclocking error in nsfminer. Don't know if the 1st gpu is labelled as "gpu 0" or "gpu 1".

**Comment by igoralebar** [comment]
if it's so easy to test, why make an issue?

**Comment by Shashank066** [comment]
I tried to test it by reducing overclock on both gpus, but still got the overclocking error. Sorry, but don't know how to test it, so asked.

**Comment by pouyalj** [comment]
Starts from 0

**Comment by Shashank066** [comment]
> Starts from 0

Thank you.
