### ISSUE TITLE
freezes on startup

### ISSUE THREAD

**Issue by Zaqsnaider** [no-fee-ethereum-mining/nsfminer#26]
Freezes at startup always in the same place.

![1](https://user-images.githubusercontent.com/42960166/105814665-cb0f3e00-5fc2-11eb-94aa-f369ad03ae8e.jpg)

If you click use the previous version of the console, it works with unreadable characters.

![2](https://user-images.githubusercontent.com/42960166/105834570-b7bc9c80-5fdb-11eb-8ca9-23cdaf2ff2c0.jpg)

- Operating System:  Windows 10 LTSC, ver.1809
- Hardware RX588, 488, 478
- Version nsf1.2.5
- options used
nsfminer -R -P stratum1+ssl://xxxx.Green@eu1.ethermine.org:5555 --exit --tstop=69 --tstart=55 --verbosity 2

**Comment by jean-m-cyr** [comment]
Not sure what you mean by previous version of the console? Try the --no-color option.

**Comment by Zaqsnaider** [comment]
I meant it.

![mengaktifkan-fitur-baru-command-prompt-3](https://user-images.githubusercontent.com/42960166/105991313-ae533300-60b4-11eb-8d0e-c48f0fa13f56.jpg)

Thanks. --no-color helped.
