### ISSUE TITLE
Windows Defender flags nsfminer_1.3.13-windows_10-opencl.zip as Trojan:Script/Oneeva.a!ml

### ISSUE THREAD

**Issue by heston88** [no-fee-ethereum-mining/nsfminer#261]
I tried downloading nsfminer_1.3.13-windows_10-opencl.zip in Windows 10 but Windows Defender flags it as a Trojan and removes it. Could this just be a false positive?

**Comment by UselessGuru** [comment]
>  Could this just be a false positive?

Yes. Most miners are detected as malicious of some sort (unfortunately). There is even a petition on this issue:
https://www.change.org/p/microsoft-stop-microsoft-s-discriminatory-policy

**Comment by heston88** [comment]
From my experience with other miners (TeamRedMiner and Pheonix), Windows Defender lists them as a low threat and just PUAs (Potentially Unwanted Applications) Coin Miners. I can easily ignore that but in this case it's listed as a high threat and a trojan. For what it's worth, I submitted it to virustotal.com and it's only coming up as a coin miner which is expected.
