### ISSUE TITLE
Windows Defender blocking latest release

### ISSUE THREAD

**Issue by sruPL** [no-fee-ethereum-mining/nsfminer#266]
Aight, of course I trust the source and I allowed it, but just heads up for Jean Cyr and everyone else, Windows Defender is going bonkers about the latest release, insta-removes it and blocks (Windows CUDA zip download).

**Comment by jean-m-cyr** [comment]
I consider it a badge of honor

**Comment by Titaniumtown** [comment]
Sounds like a Windows Defender issue. Take the issue up with them.

**Comment by AlgoNetwork** [comment]
overclocking configuration changed to zero after use nsfminer. I don't know why.
Nvidia 3060.

**Comment by Titaniumtown** [comment]
What does that have to do with this issue?

**Comment by Alexdotdot** [comment]
Same but with McAfee
