### ISSUE TITLE
Issue with getwork mode

### ISSUE THREAD

**Issue by Starl33** [no-fee-ethereum-mining/nsfminer#268]
I am getting the following error while trying to run the miner in getwork mode using eth-proxy:

"A connect request was made on an already connected socket"

"No more IP addresses to try for host: 10.10.10.10"

I am using port 8080 on the eth-proxy system for listening.

ethminer works flawlessly without any issues with the same config.

I am using the below config to connect the miner with the eth-proxy:
**nsfminer.exe -U -P getwork://10.10.10.10:8080 -R --getwork-recheck 200 --api-bind 0.0.0.0:8113**

**Comment by jean-m-cyr** [comment]
I don't have a full node or proxy where I can test getwork.

**Comment by Starl33** [comment]
If you are interested, I can provide you the link for the proxy. It can be tested on a single system with 127.0.0.1:8080 (Miner & proxy running on one system itself).
