### ISSUE TITLE
Duplicate solution from same and also different card for the same job

### ISSUE THREAD

**Issue by efrasyad** [no-fee-ethereum-mining/nsfminer#27]
**Describe the bug**
Solution submit by same and also different card

**To Reproduce**
1. Run nsfminer
2. wait until card solution for same job

 <unknown> Job: e6838894 eu1.ethermine.org:5555
 cu-1  Job: e6838894 Solution: 0x92c7845fa5172574
 <unknown> **Accepted  23 ms. eu1.ethermine.org:5555
 <unknown> Job: be491e7c eu1.ethermine.org:5555
 cu-1  Job: e6838894 Solution: 0x92c7845fb7bd6a78
 <unknown> **Accepted  23 ms. eu1.ethermine.org:5555

 <unknown> Job: 43439155 eu1.ethermine.org:5555
 <unknown> Job: 07b1d4ca eu1.ethermine.org:5555
 cu-0  Job: 43439155 Solution: 0xc7645de178f80e16
 <unknown> **Accepted  23 ms. eu1.ethermine.org:5555
 cu-0  Job: 07b1d4ca Solution: 0x5a1881ef66725c23
 <unknown> **Accepted  22 ms. eu1.ethermine.org:5555
 cu-1  Job: 07b1d4ca Solution: 0xda1881ef6a3bfa15
 <unknown> **Accepted  23 ms. eu1.ethermine.org:5555

<unknown> Job: 6a00c8d6 eu1.ethermine.org:5555
 cu-0  Job: 6a00c8d6 Solution: 0x85661461215e6145
 <unknown> **Accepted  23 ms. eu1.ethermine.org:5555
 <unknown> Job: e5ddad79 eu1.ethermine.org:5555
 cu-1  Job: 6a00c8d6 Solution: 0x056614612e09ae00
 <unknown> **Accepted  23 ms. eu1.ethermine.org:5555

**Expected behavior**
Card should move on to next job if either card submit solution or solution already accepted

**Screenshots (Optional)**

**Environment (please complete the following information):**
- Operating System: Windows 10
- Hardware: RTX 3080
- Ethminer Version: 1.2.5
- Ethminer options used:  -U --HWMON 2 -v 2 --display-interval 60 --exit

**Additional context**

**Comment by jean-m-cyr** [comment]
Your assumptions are incorrect. Since the network difficulty is much higher than the pool's difficulty level, it is quite normal for many valid solutions to be submitted for the same job, this will go on till the poll receives a solution from a miner that meets the network difficulty level. Besides, how would the miner 'move on to the next job', it can't do that till the pool provides it!
