### ISSUE TITLE
Overclocking Feature request

### ISSUE THREAD

**Issue by samfishersam** [no-fee-ethereum-mining/nsfminer#278]
Heya everyone on this project :)

Been playing around with nsfminer for a bit today and was wondering if there were any plans to introduce an overclocking utility into the miner, as part of launch flags maybe?  I have mining profiles on afterburner but voltage locking doesn't seem to be working well, and past testing with other miners with built in OC capabilities have shown me that it's far more consistent to OC from the miner than afterburner.  Probably involves a lot of work tho!

**Comment by jean-m-cyr** [comment]
No such plan.
