### ISSUE TITLE
Not building on latest git

### ISSUE THREAD

**Issue by joolzg** [no-fee-ethereum-mining/nsfminer#279]
Followed instructions and get this
[ 56%] Building NVCC (Device) object libcuda/CMakeFiles/cuda.dir/cuda_generated_ethash_cuda_miner_kernel.cu.o
nvcc fatal   : Value 'c++17' is not defined for option 'std'
CMake Error at cuda_generated_ethash_cuda_miner_kernel.cu.o.Release.cmake:220 (message):
  Error generating
  /home/encoder/src/nsfminer/build/libcuda/CMakeFiles/cuda.dir//./cuda_generated_ethash_cuda_miner_kernel.cu.o

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Any ideas?

**Comment by GXKe** [comment]
Building NVCC (Device) object libcuda/CMakeFiles/cuda.dir/Release/cuda_generated_ethash_cuda_miner_kernel.cu.obj
  nvcc fatal   : nvcc cannot find a supported version of Microsoft Visual Studio. Only the versions between 2017 and 20
  19 (inclusive) are supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check;
   however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at yo
  ur own risk.
  CMake Error at cuda_generated_ethash_cuda_miner_kernel.cu.obj.Release.cmake:220 (message):
    Error generating
    C:/Users/Administrator/nsfminer/build/libcuda/CMakeFiles/cuda.dir//Release/cuda_generated_ethash_cuda_miner_kernel.
  cu.obj


C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: “cmd.exe”已 退出，
代码为 1。 [C:\Users\Administrator\nsfminer\build\libcuda\cuda.vcxproj]



PS C:\Users\Administrator> nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:32_Central_Daylight_Time_2017
Cuda compilation tools, release 9.0, V9.0.176

**Comment by GXKe** [comment]
Encountered the same problem under windows

**Comment by jean-m-cyr** [comment]
Likely caused by the outdated version of nvcc.

**Comment by joolzg** [comment]
This is the version installed with the lastest drivers, what version did you build with.

Also a note in "building" about minimal versions would be a good addition to stop these kind of posts.

**Comment by joolzg** [comment]
OK now installing 11.3, it compiles but now

16:46:33 miner nsfminer 1.3.14+commit.3bbc66f3 (No stinkin' fees edition)
16:46:33 miner Copyright 2021 Jean M. Cyr, Licensed under the terms
16:46:33 miner  of the GNU General Public License Version 3
16:46:33 miner https://github.com/no-fee-ethereum-mining/nsfminer
16:46:33 miner Build: linux/release/gnu
16:46:33 miner 3rd Party: GCC 9.3.0, Boost 1.76.0
16:46:33 miner 3rd Party: OpenSSL 1.1.1j  16 Feb 2021
16:46:33 miner Running as user: encoder
16:46:33 miner CUDA Error : unknown error


nvidia-smi 
Sat Jul 10 16:47:33 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 465.19.01    CUDA Version: 11.3     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0  On |                  N/A |
| N/A   50C    P8    10W /  N/A |    978MiB /  5936MiB |      5%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

**Comment by joolzg** [comment]
Works now with the new update from Nvidia
