### ISSUE TITLE
Fail to compile during boost phase with hunter in ppc64le architecture

### ISSUE THREAD

**Issue by viniciusferrao** [no-fee-ethereum-mining/nsfminer#30]
**Describe the bug**
There's no way to compile the software since CMake fails to consume it's own compiled boost library by Hunter.

**To Reproduce**
1. Just compile with default options 
2. Wait
3. See the error message

**Expected behavior**
Able to compile and run the software

**Screenshots (Optional)**
```
[100%] Completed 'Boost-thread'
[100%] Built target Boost-thread
-- [hunter] Build step successful (dir: /root/.hunter/_Base/7d73237/71e08c5/634d400/Build/Boost/__thread)
-- [hunter] Cache saved: /root/.hunter/_Base/Cache/raw/62c2f8b6b66364732e7928c7256b0fcc4fe5f84c.tar.bz2
CMake Error at /root/.hunter/_Base/Download/Hunter/0.23.289/7d73237/Unpacked/cmake/find/FindBoost.cmake:1273 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.75.0

  Boost include path:
  /root/.hunter/_Base/7d73237/71e08c5/634d400/Install/include

  Could not find the following static Boost libraries:

          boost_system
          boost_filesystem
          boost_thread

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  /root/.hunter/_Base/7d73237/71e08c5/634d400/Install/lib/cmake/Boost/BoostConfig.cmake:51 (find_package)
  CMakeLists.txt:61 (find_package)



[hunter ** INTERNAL **] Library not exists: Boost_SYSTEM_LIBRARY_DEBUG-NOTFOUND
[hunter ** INTERNAL **] [Directory:/root/.hunter/_Base/7d73237/71e08c5/634d400/Install/lib/cmake/Boost]

------------------------------ ERROR -----------------------------
    https://hunter.readthedocs.io/en/latest/reference/errors/error.internal.html
------------------------------------------------------------------

CMake Error at /root/.hunter/_Base/Download/Hunter/0.23.289/7d73237/Unpacked/cmake/modules/hunter_error_page.cmake:12 (message):
Call Stack (most recent call first):
  /root/.hunter/_Base/Download/Hunter/0.23.289/7d73237/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_error_page)
  /root/.hunter/_Base/7d73237/71e08c5/634d400/Install/lib/cmake/Boost/BoostConfig.cmake:99 (hunter_internal_error)
  CMakeLists.txt:61 (find_package)


CMake Error at CMakeLists.txt:61 (find_package):
  Found package configuration file:

    /root/.hunter/_Base/7d73237/71e08c5/634d400/Install/lib/cmake/Boost/BoostConfig.cmake

  but it set Boost_FOUND to FALSE so package "Boost" is considered to be NOT
  FOUND.


-- Configuring incomplete, errors occurred!
See also "/root/nsfminer/build/CMakeFiles/CMakeOutput.log".

```

**Environment (please complete the following information):**
- Operating System: RHEL 8.3
- Hardware: IBM AC922 Power9 (ppc64le)
- Ethminer Version: master
- Ethminer options used: N/A

**Additional context**
This may be a Hunter problem to be honest, but I don't know how to properly debug it.

**Comment by jean-m-cyr** [comment]
Neither do I, since I don't have a PPC platform.

**Comment by viniciusferrao** [comment]
I can try to solve it myself and report back @jean-m-cyr but there's any insight or a tip of what I should be looking for? Right now I'm trying with older releases of Hunter to see if it's a boost issue tiered to the latest version.

**Comment by jean-m-cyr** [comment]
It is more likely a cmake issue. On older versions of Linux I had to manually upgrade cmake.

**Comment by viniciusferrao** [comment]
I thought that too @jean-m-cyr but I really don't know. RHEL 8.3 ships with CMake 3.11 which is dated, RHEL 8.4 will ship with 3.18 but it's not released yet.

With the shipped CMake release there's no way to even start the compilation, Hunter seems to require CMake 3.12 at minimum. So I've tried two paths:

* Installed CMake with snapd (snapcraft) and this output was generated using CMake 3.19 from snapd.
* I tried compiling CMake 3.19 by myself but the same issue happened.

I still think it may be a Hunter issue, perhaps I'll post it there. In a effort to prove this I tried to compile the software with Hunter disabled. It was a pain. But I was able to compile `nsfminer` but the link editing process failed since systemwide jsoncpp does not provide an static library.

**Comment by jean-m-cyr** [comment]
BTW. That looks like a very interesting system! Would be cool to support it.

**Comment by viniciusferrao** [comment]
Hi @jean-m-cyr yeah it's a cool machine! I would not mess with Docker right now because Docker isn't supported on RHEL due to it's issues with podman, and it would not work on ppc64le either.

I have another machine with RHEL 8.3 but it's x86_64. I tried to compile `nsfminer` and it failed too, during the link editing process. I'll open another issue for that one. The conclusion is that something is wrong because my machine is ppc64le. It's no OS related during the Hunter phase.

I'll follow the Hunter bug report guide and report there, so we can further investigate the issue here.

**Comment by jean-m-cyr** [comment]
I assume this can be closed?

**Comment by jean-m-cyr** [comment]
Yes, I see hunter has accepted the bug. Closing for now.

**Comment by viniciusferrao** [comment]
@jean-m-cyr Can you take a look at my comments on https://github.com/no-fee-ethereum-mining/nsfminer/pull/59? I'm trying to understand what was wrong so I can fix.
