### ISSUE TITLE
"tls12" is still shown in docs

### ISSUE THREAD

**Issue by parasyte** [no-fee-ethereum-mining/nsfminer#35]
References to `tls12` are still mentioned in [the docs](https://github.com/no-fee-ethereum-mining/nsfminer/tree/4c9fcd4131fbfdd28bf61cad1a826e2a1e9d93c8/docs). It was removed as part of https://github.com/no-fee-ethereum-mining/nsfminer/commit/4c9fcd4131fbfdd28bf61cad1a826e2a1e9d93c8

**Comment by jean-m-cyr** [comment]
fixed by PR #43
