### ISSUE TITLE
Error: locale::facet::_S_create_c_locale name not valid; if LC_ environment variables aren't set

### ISSUE THREAD

**Issue by viniciusferrao** [no-fee-ethereum-mining/nsfminer#38]
**Describe the bug**
`nsfminer` fails to launch on RHEL systems if LC_* environment variables aren't defined.

**To Reproduce**
1. Compile `nsfminer` on RHEL8
2. Check if LC_ALL is unset
3. Try to run the software
4. Be greeted with: `Error: locale::facet::_S_create_c_locale name not valid`
5. Software quits

**Expected behavior**
Run the software even without properly locales. It should not be relevant at all. Just fallback to LC_ALL=C?

**Environment (please complete the following information):**
- Operating System: Red Hat Enterprise Linux 8.3
- Hardware: IBM Power9 AC922
- Ethminer Version: Master
- Ethminer options used: Doesn't matter.

**Additional context**
A workaround can be made just setting LC_ALL; for example: `export LC_ALL="en_US.UTF-8"`

**Comment by jean-m-cyr** [comment]
Fixed by PR#42
