### ISSUE TITLE
Does not show temperature and fan speed(nvidia) (version nsfminer 1.2.5-17+commit.fd9fd811)

### ISSUE THREAD

**Issue by xgnom666x** [no-fee-ethereum-mining/nsfminer#46]
Does not show temperature and fan speed

**Screenshots (Optional)**
![nsf](https://user-images.githubusercontent.com/41507042/106394675-d32a0c00-640e-11eb-883f-b32db5b973d6.jpg)

**Environment (please complete the following information):**
- Operating System: 
  HiveOs(Ubuntu 18.04, Driver Version: 460.32.03,  CUDA Version: 11.2
- GTX 1070
- Version nsfminer 1.2.5-17+commit.fd9fd811
./nsfminer --report-hashrate --api-port 3334 --HWMON 2 --cuda -P stratum2+tcp://32pWYbjdAS9wvheMbep765SiN7tCCZLN4X.1070x3@daggerhashimoto.eu.nicehash.com:3353 --response-timeout 180 --eval --verbosity 2 --cu-streams 2

version nsfminer 1.2.5-14+commit.4c9fcd41 - displays normally 

Update:
version nsfminer 1.2.5-14+commit.4c9fcd41
After generating a new dag, when switching from one coin to another (eg.nicehash, switching zil to ethereum), all solutions are incorrect.

**Comment by jean-m-cyr** [comment]
Fixed by PR #50
