### ISSUE TITLE
No AMD device and no reported hashrate

### ISSUE THREAD

**Issue by krutru** [no-fee-ethereum-mining/nsfminer#47]
Thank you for your continued work on ethminer, I have just been testing this on Windows 10 with Nvidia and AMD cards. The first issue I came across was it was not finding the AMD card and I found a fix here:

https://github.com/ethereum-mining/ethminer/issues/2001#issuecomment-662288143

The other issue I have found is, it is not reporting hash rate to the pool and the following fixed the issue for me:

`nsfminer **--report-hashrate --farm-recheck 500** -P stratum1+ssl://.....`

Hope this helps someone

**Comment by jean-m-cyr** [comment]
--farm-recheck has no effect when using stratum. Are you using getwork protocol?

**Comment by jean-m-cyr** [comment]
For those not seeing AMD GPUs: ethereum-mining/ethminer#2001 (comment)
