### ISSUE TITLE
High CPU load

### ISSUE THREAD

**Issue by Zaqsnaider** [no-fee-ethereum-mining/nsfminer#48]
Hello. I found a high jumping load on the CPU.
- Operating System: Windows 10
- Hardware 3*GTX1070 & 2*GTX1060
- NSFminer Version 1.2.5 & 1.3.0
![1](https://user-images.githubusercontent.com/42960166/106500175-9293c680-64d2-11eb-8d3e-a2ebe8c15e9e.jpg)
![2](https://user-images.githubusercontent.com/42960166/106500183-958eb700-64d2-11eb-8223-a4e180d79efb.jpg)
![3](https://user-images.githubusercontent.com/42960166/106500188-96bfe400-64d2-11eb-9845-d34032855349.jpg)

**Comment by jean-m-cyr** [comment]
Believed fixed, reopen if not
