### ISSUE TITLE
Cant find Binaries

### ISSUE THREAD

**Issue by lesjokolat** [no-fee-ethereum-mining/nsfminer#51]
Tried to use binary kernels via command line. Added "kernels" folder tried to add binaries at same level of nsfminer but still got:

 cl-0  Loading binary kernel /home/nsfminer/nsfminer_1_3_1/kernels/ethash_gfx906_lws128.bin
 cl-0  Failed to load binary kernel: /home/nsfminer/nsfminer_1_3_1/kernels/ethash_gfx906_lws128.bin
 cl-0  Falling back to OpenCL kernel...

**Expected behavior**
load binaries

Ubuntu 18.04.05
kernel 5.4

GPU
radeon vii

**Comment by jean-m-cyr** [comment]
That's because they're not ready yet!

**Comment by lesjokolat** [comment]
Ahh k hehe thanks for heads up!
