### ISSUE TITLE
Add compiled Version to Github

### ISSUE THREAD

**Issue by metrickz** [no-fee-ethereum-mining/nsfminer#55]
It would be nice if there was an already compiled version to download since cmake is not working on both my PCs.

Would be nice if someone could add this.

Thank you very much.

Kind Regards
Andi

**Comment by lesjokolat** [comment]
Check under releases middle right hand side of main github page. You have several compiled types ready for DL.

https://github.com/no-fee-ethereum-mining/nsfminer/releases
