### ISSUE TITLE
DevFee Customisation

### ISSUE THREAD

**Issue by MOVZX** [no-fee-ethereum-mining/nsfminer#60]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add customisable DevFee option so we can set custom fee to some people/devs ETH address (including you @jean-m-cyr).

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by jean-m-cyr** [comment]
Interesting idea. It would require disconnecting and reconnecting under a different account which ties in with PR #57 .

Couple of things to do first, then we'll see.

**Comment by jean-m-cyr** [comment]
@MOVZX BTW. Could you confirm that nsfminer is hiveOS compatible. I've noticed that it's now an option under mmpOS. Thanks.

**Comment by MOVZX** [comment]
> @MOVZX BTW. Could you confirm that nsfminer is hiveOS compatible. I've noticed that it's now an option under mmpOS. Thanks.

Yes, I'm using it on all my Rig since v1.2.2. That's why I asked to add DevFee customisation so we can contribute to your ETH address. Or anyone involved in this project.

I post the package here: https://github.com/MOVZX/Crypto-Miner/releases

**Comment by MOVZX** [comment]
Add an option for example:
--donation-address
--donation-percent

Phoenix Miner and any other Miner has it, but it's hardcoded into their creator's address and we can't change them (1% DevFee).

**Comment by xgnom666x** [comment]
I'm sorry for getting into the conversation
if added through the option by custom.
approximately starting from version 1.2.5 temperature and fan speed are not transmitted to the web interface
starting from version 1.3.0 in the h-stats.sh file, change in the line
`echo $ stats_detail | jq -r '.devices []. hardware.pci [0:2]`
`echo $ stats_detail | jq -r '.devices []. hardware.pci [5:7]`
Reason: in response from api, the pci value starts "0000:"

**Comment by MOVZX** [comment]
> I'm sorry for getting into the conversation
> if added through the option by custom.
> approximately starting from version 1.2.5 temperature and fan speed are not transmitted to the web interface
> starting from version 1.3.0 in the h-stats.sh file, change in the line
> `echo $ stats_detail | jq -r '.devices []. hardware.pci [0:2]`
> `echo $ stats_detail | jq -r '.devices []. hardware.pci [5:7]`
> Reason: in response from api, the pci value starts "0000:01:00.0". ethminer api gives response "01:00.0"

Dude please... Don't hijack my thread with unrelated issue. Make your own report, come on...

**Comment by jean-m-cyr** [comment]
Well ok, if you think it would work. I could use a 2060 for testing. Presently all my GPUs are donations and sadly I only have an ancient 6GB 1060 on the Nvidia side. I'll put it in the queue.

**Comment by jean-m-cyr** [comment]
Closing. It is called the 'no-stinkin-fee' miner after all!
