### ISSUE TITLE
Epoch resetting to 0: DAG back to 1GB, then crashing

### ISSUE THREAD

**Issue by image28** [no-fee-ethereum-mining/nsfminer#64]
**Epoch resetting to 0: DAG back to 1GB, then crashing**
```
 cl-0  Job: 9ec43d1d Solution: 0x6f65e2000126385b
 miner Job: 7983feb2 daggerhashimoto.usa.nicehash.com:3353
 miner **Accepted 206 ms. daggerhashimoto.usa.nicehash.com:3353
 miner Epoch : 393 Difficulty : 644.25 Mh
 miner Job: ea6890d2 daggerhashimoto.usa.nicehash.com:3353
 miner Extranonce set to 574b32
 miner Epoch : 0 Difficulty : 644.25 Mh
 miner Job: e279f095 daggerhashimoto.usa.nicehash.com:3353
 cl-0  Using 4.13 GB out of 7.98 GB GPU memory
 cl-0  Loading binary kernel /home/image/nsfminer/build/nsfminer/kernels/ethash_gfx1012_lws256.bin
 cl-0  Failed to load binary kernel: /home/image/nsfminer/build/nsfminer/kernels/ethash_gfx1012_lws256.bin
 cl-0  Falling back to OpenCL kernel...
./start_miner.sh: line 1: 549313 Segmentation fault      (core dumped) ./nsfminer --devices 1 --cl-work 256 --cl-bin --nocolor -R --display-interval 60 --eval --pool stratum2+tcp://*******.******@daggerhashimoto.usa.nicehash.com:3353
```

**To Reproduce**
Run miner on AMD RX 550 TX Gpu 8gb with launch command
./nsfminer --devices 1 --cl-work 256 --cl-bin --nocolor -R --display-interval 60 --eval --pool stratum2+tcp://wallet.worker@daggerhashimoto.usa.nicehash.com:3353
for some time, several hours...

DAG starts at epoch 393 (currently/ruffly) 

**System**
Linux archlinux 5.10.11-arch1-1 #1 SMP PREEMPT Wed, 27 Jan 2021 13:53:16 +0000 x86_64 GNU/Linux
Advanced Micro Devices, Inc. [AMD/ATI] Navi 14 [Radeon RX 5500/5500M / Pro 5500M] (rev c5)

**nsfminer clone log ref**
```
0000000000000000000000000000000000000000 b3d4e15805ac0d44ea0b7817cb576df50de85ce8 image28 <*****@************> 1612587626 +1300  clone: from https://github.com/no-fee-ethereum-mining/nsfminer.git
```

**nsfminer compiled**

```
mkdir -p build &&
cd build &&
cmake .. -DETHASHCL=ON -DETHASHCUDA=OFF -DAPICORE=OFF -DBINKERN=ON -DUSE_SYS_OPENCL=OFF -DHUNTER_ENABLED=ON &&
make -j 23
```

**Comment by jean-m-cyr** [comment]
Though the --bin is supported, no binary kernels are included yet. That doesn't explain the crash though.

**Comment by image28** [comment]
Working on compiling the kernel myself, just removed hunter in an attempt to get libethash compiled as a shared lib.  Narrowing, got a few extra mh/s in a debugging build by using my system's libs for a few things. Had to remove hunter to compile ethash(c++) from here [chfast/ethash](https://github.com/chfast/ethash), to get it to build a so file correctly, and a lot of renaming ( would break cross platform support ).

Was still randomly crashing, but not resetting the DAG anymore to my knowledge ( when I go out I logout, and leave it in the background so no log of last crash ).

Running with gdb seems to prevent both errors from happening.

I'm also looking at linking it to a minimal stratum type client for running on a xeon phi.
Which would allow me to narrow it right down to the CL code, if that's the issue.[https://github.com/image28/netcat-stratum-client](url)

**Comment by image28** [comment]
Result of a gdb backtrace, all of the libraries didn't have debugging enabled, not sure if libamdocl64.so is open source or has debugging symbols yet. ( In case it helps, had crashes on nvidia cards too, may have been completely unrelated.

`#0  0x00007ffff784f508 in __memmove_sse2_unaligned_erms ()
   from /usr/lib/libc.so.6
#1  0x00007fffec72b22c in ?? () from /usr/lib/libamdocl64.so
#2  0x00007fffec74c7b8 in ?? () from /usr/lib/libamdocl64.so
#3  0x00007fffec74e9c4 in ?? () from /usr/lib/libamdocl64.so
#4  0x00007fffec74ed01 in ?? () from /usr/lib/libamdocl64.so
#5  0x00007fffec71a401 in ?? () from /usr/lib/libamdocl64.so
#6  0x00007fffec4b7724 in ?? () from /usr/lib/libamdocl64.so
#7  0x00007fffec4b84cd in ?? () from /usr/lib/libamdocl64.so
#8  0x00007fffec3f03f6 in ?? () from /usr/lib/libamdocl64.so
#9  0x00007fffec49d00f in ?? () from /usr/lib/libamdocl64.so
#10 0x00007ffff7e913e9 in start_thread () from /usr/lib/libpthread.so.0
#11 0x00007ffff78a6293 in clone () from /usr/lib/libc.so.6`

**Comment by jean-m-cyr** [comment]
Seems to work now
```
 miner nsfminer 1.3.4 (No stinkin' fees edition)
 miner Copyright 2021 Jean M. Cyr, Licensed under the terms
 miner  of the GNU General Public License Version 3
 miner https://github.com/no-fee-ethereum-mining/nsfminer
 miner Build: linux/release/gnu
 miner 3rd Party: GCC 9.3.0, CUDA 11.2, Boost 1.75.0
 miner 3rd Party: OpenSSL 1.1.1i, Ethash 0.5.0
 miner Configured pool daggerhashimoto.usa.nicehash.com:3353
 miner Selected pool daggerhashimoto.usa.nicehash.com:3353
 miner Connection remotely closed by daggerhashimoto.usa.nicehash.com
 miner Stratum mode : EthereumStratum/1.0.0 (NiceHash)
 miner Established connection to daggerhashimoto.usa.nicehash.com:3353
 miner Spinning up miners...
 cu-0  Using Pci 0000:05:00.0: GeForce GTX 1060 6GB (Compute 6.1) Memory : 5.94 GB
 cl-1  Using Pci 0000:08:00.0: gfx900 (OpenCL 2.0 AMD-APP (3180.7)) Memory : 7.98 GB
 cl-2  Using Pci 0000:0b:00.0: gfx1010 (OpenCL 2.0 AMD-APP (3180.7)) Memory : 7.98 GB
 miner Extranonce set to 10508a
 miner Authorized worker 1Lgd9h9g2xHHkXTMu4u8LmNdk1W6br12x.mine0
 miner Epoch : 394 Difficulty : 1.42 Gh
 miner Job: 0c1722e5 daggerhashimoto.usa.nicehash.com:3353
 cl-1  Using 4.14 GB out of 7.98 GB GPU memory
 miner Job: 37293c32 daggerhashimoto.usa.nicehash.com:3353
 cl-2  Using 4.14 GB out of 7.98 GB GPU memory
 cu-0  Using 4.14 GB out of 5.94 GB GPU memory
 cl-1  4.08 GB of DAG data generated in 4.0 seconds
 cl-2  4.08 GB of DAG data generated in 6.6 seconds
 miner 0:00 A0 0.00 h - cu0 0.00, cl1 0.00, cl2 0.00
 miner 0:00 A0 10.77 Mh - cu0 0.00, cl1 8.15, cl2 2.61
 miner 0:00 A0 77.88 Mh - cu0 0.00, cl1 27.78, cl2 50.10
 miner 0:00 A0 77.55 Mh - cu0 0.00, cl1 27.51, cl2 50.05
 miner Job: 1312a357 daggerhashimoto.usa.nicehash.com:3353
 miner Job: 6828bdd9 daggerhashimoto.usa.nicehash.com:3353
 cl-2  Job: 6828bdd9 Solution: 0x10508a80069de0bd
 miner **Accepted  73 ms. daggerhashimoto.usa.nicehash.com:3353
 cu-0  5.94 GB of DAG data generated in 25.9 seconds
 miner 0:00 A1 77.51 Mh - cu0 0.01, cl1 27.44, cl2 50.05
 miner Job: eed86263 daggerhashimoto.usa.nicehash.com:3353
 miner Job: 3ba0dbe0 daggerhashimoto.usa.nicehash.com:3353
 miner 0:00 A1 93.90 Mh - cu0 16.33, cl1 27.53, cl2 50.05
 miner 0:00 A1 93.90 Mh - cu0 16.32, cl1 27.52, cl2 50.06
 miner 0:00 A1 93.81 Mh - cu0 16.32, cl1 27.44, cl2 50.05
 miner Extranonce set to 3838b0
 miner Job: e54ffdab daggerhashimoto.usa.nicehash.com:3353
 miner Job: c8a91ea6 daggerhashimoto.usa.nicehash.com:3353
 cl-1  Job: c8a91ea6 Solution: 0x3838b040027f6b74
 miner **Accepted  71 ms. daggerhashimoto.usa.nicehash.com:3353
 miner Job: 7520a829 daggerhashimoto.usa.nicehash.com:3353
 miner Job: d9928a6e daggerhashimoto.usa.nicehash.com:3353
 miner 0:00 A2 93.86 Mh - cu0 16.32, cl1 27.47, cl2 50.06
 cl-1  Job: d9928a6e Solution: 0x3838b040082ab902
 miner **Accepted  70 ms. daggerhashimoto.usa.nicehash.com:3353
 miner 0:00 A3 93.80 Mh - cu0 16.31, cl1 27.43, cl2 50.06
 cu-0  Job: d9928a6e Solution: 0x3838b000068ee722
 miner **Accepted  96 ms. daggerhashimoto.usa.nicehash.com:3353
 miner Job: 30f4e95d daggerhashimoto.usa.nicehash.com:3353
^C
 main  Got interrupt ...
 main  Disconnected from daggerhashimoto.usa.nicehash.com:3353
 main  Shutting down miners...
 main  Terminated!
```
