### ISSUE TITLE
Interdependencies between folders

### ISSUE THREAD

**Issue by deguzasad** [no-fee-ethereum-mining/nsfminer#65]
Typically in CMake every `add_library` creates a library that can be built on its own. Its dependencies are typically specified with `target_link_libraries` and the dependency graph is usually acyclic. Unfortunately, CMake doesn't force the absence of cycles, which makes them hard to spot and keep in check.

Currently there are dependency cycles between different folders of the project. For example, `libpool` depends on `libeth`
https://github.com/no-fee-ethereum-mining/nsfminer/blob/b3d4e15805ac0d44ea0b7817cb576df50de85ce8/libpool/PoolManager.h#L17
https://github.com/no-fee-ethereum-mining/nsfminer/blob/b3d4e15805ac0d44ea0b7817cb576df50de85ce8/libpool/PoolManager.cpp#L32
And `libeth` depends in `libpool`
https://github.com/no-fee-ethereum-mining/nsfminer/blob/b3d4e15805ac0d44ea0b7817cb576df50de85ce8/libeth/Farm.cpp#L24
https://github.com/no-fee-ethereum-mining/nsfminer/blob/b3d4e15805ac0d44ea0b7817cb576df50de85ce8/libeth/Farm.cpp#L479

Is this a bug and folders should form a DAG, or is it intended and anything can basically depend on anything?

**Comment by jean-m-cyr** [comment]
Well, let's see.

The poolmanager object certainly depends on the the farm object and vice versa. It;s good that cmake handles the cycle without recursing infinitely. Not sure how it could be restructured.

**Comment by jean-m-cyr** [comment]
No work is expected here. Closing
