### ISSUE TITLE
[Q] Device enumeration

### ISSUE THREAD

**Issue by RainbowMiner** [no-fee-ethereum-mining/nsfminer#67]
Hi,

would you be so kind and explain, how the enumeration of GPUs in the `--devices` argument works on mixed rigs, with AMD, NVIDIA (plus maybe Onboard Intel). 

Example:
```
 Id Pci Id       Type Name                          CUDA SM  CL    Total Memory
--- ------------ ---- ----------------------------- ---- --- ----  ------------
  0 0000:01:00.0 Gpu  Radeon R9 390                          Yes        8.00 GB
  1 0000:02:00.0 Gpu  GeForce GTX 1070              Yes  6.1            8.00 GB
  2 0000:03:00.0 Gpu  GeForce GTX 1070              Yes  6.1            8.00 GB
  3 0000:05:00.0 Gpu  GeForce GTX 1070              Yes  6.1            8.00 GB
  4 0000:07:00.0 Gpu  Radeon R9 200                          Yes        4.00 GB
  5 0000:08:00.0 Gpu  GeForce GTX 1070              Yes  6.1            8.00 GB
  6 0000:09:00.0 Gpu  Radeon R9 390                          Yes        8.00 GB
  7 Intel GPU 0.0Gpu  Intel(R) HD Graphics 610               Yes        3.16 GB
```

If I want to launch nsfminer for AMD only, do I set `--opencl --devices 0,4,6` or do I use `--opencl --devices 0,1,2` or different?

If I want to launch nsfminer for that one R9 200 AMD only, do I set `--opencl --devices 4` or do I use `--opencl --devices 1` or different?

Same for if I want to launch for Nvidia only, do I set `--cuda --devices 1,2,3,5` or do I use `--cuda --devices 0,1,2,3` or different? 

Thank you for an explanation in advance!

Regards,
RBM

**Comment by jean-m-cyr** [comment]
To run Nvidia you could use the -U option, but that's not your question.

Yes, use the Id number listed in the --list-devices results, as --devices indices, but be aware that the labelling of those devices will show up with different indices once the miner is running. For example if you chose 2 AMD GPUs, say 2 and 4, they will always show up as cl-0 and cl-1 in the console log.
