### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by xgnom666x** [no-fee-ethereum-mining/nsfminer#71]
May I ask: will the hashrate on 10 ** series video cards stop decreasing, if the dag is split on nvidia?
The question came from here https://github.com/ethereum-mining/ethminer/pull/1977#issuecomment-603312164

**Comment by dogmoosefern** [comment]
A NVIDIA response says they don't believe software optimization can fix the TLB vs DAG size issue. 
[https://forums.developer.nvidia.com/t/blockchain-drivers/110847/14](url)
> Because the TLB is a fixed capacity hardware resource, and the ETH algorithm accesses the DAG randomly, we don’t believe there are any software optimizations that could reduce the TLB miss rate.

**Comment by jean-m-cyr** [comment]
No, the split DAG algorithm was tried on Nvidia at the time it became necessary for AMD. It had no impact on this particular issue.
