### ISSUE TITLE
Hashrate not reported to ethermine pool

### ISSUE THREAD

**Issue by Anze-** [no-fee-ethereum-mining/nsfminer#74]
Using CUDA 11, RTX3070, arch linux latest stable kernel.

The local Hashrate is not reported to the ethermine ETH pool, stays at 0 all the time.

Moreover, local Hashrate happens to be around 59MH/s, against a pool-measured Hashrate of about 51 Mh/s.

**Comment by viniciusferrao** [comment]
Did you pass -R on the command line?

**Comment by Anze-** [comment]
ouch! sorry  @viniciusferrao, my bad, thought that was on by default!
...for anyone who needs to know more use the extended help function:

`nsfminer -H misc`
