### ISSUE TITLE
GDDRX5 timing - ETHLargementPill 

### ISSUE THREAD

**Issue by peperunas** [no-fee-ethereum-mining/nsfminer#75]
Hello! First of all, great job!

I am not sure if it is possible (or maybe already implemented) but it would be great if the project would implement a solution similar to the one adopted by the ETHlargementPill. As far as I know, other closed source mining software implemented it.

I apologize if this has been asked previously (I have searched in the closed issues and I couldn't find anything related).

Thank you very much for your work!

**Comment by jean-m-cyr** [comment]
I have no idea what the ETHlargementPill is or does?

**Comment by peperunas** [comment]
It is not clear to me what the ETHLargementPill is actually implemented but, allegedly, it increases the hashrate of the NVIDIA 10xx GPU series of about 30%. It seems that modifies the memory timings of the GPUs.

**Comment by gap370** [comment]
download ethlargementpill here: https://github.com/Virosa/ETHlargementPill
just use tmux to run sudo ./OhGodAnETHlargementPill-r2
it boosts hashrate on GDDRX5 cards I think
