### ISSUE TITLE
Hash rate decreased on version 1.3.3

### ISSUE THREAD

**Issue by Zaqsnaider** [no-fee-ethereum-mining/nsfminer#76]
Hello.
On my 8gb polaris, the hash rate decreased on version 1.3.3.
On 1.3.2, the speed was 121,8.

Windows 10, RX 488.

![1](https://user-images.githubusercontent.com/42960166/107605412-2b99ae80-6c44-11eb-8d9d-0cce38ced10d.jpg)

**Comment by sfornengo** [comment]
Same for me, it fails connecting to eu1.ethermine.org:5555 and spends time regularly reconnecting on eu1.ethermine.org:4444

**Comment by Zaqsnaider** [comment]
I confirm that it selects 4444 out of several pools.

**Comment by jean-m-cyr** [comment]
In order to get a secure connection to work you must specify stratum+ssl// or stratums:// as the pool address.
```
miner@miner0:~/nsfminer/build$ nsfminer/nsfminer -P stratums://0x96815EB373aD89F1a5822f08c8F0f6b72d102583.mine0@eu1.ethermine.org:5555
 miner nsfminer 1.3.4 (No stinkin' fees edition)
 miner Copyright 2021 Jean M. Cyr, Licensed under the terms
 miner  of the GNU General Public License Version 3
 miner https://github.com/no-fee-ethereum-mining/nsfminer
 miner Build: linux/release/gnu
 miner 3rd Party: GCC 9.3.0, CUDA 11.2, Boost 1.75.0
 miner 3rd Party: OpenSSL 1.1.1i, Ethash 0.5.0
 miner Configured pool eu1.ethermine.org:5555
 miner Selected pool eu1.ethermine.org:5555
 miner Negotiation of EthereumStratum/2.0.0 failed. Trying another ...
 miner Stratum mode : EthereumStratum/1.0.0 (NiceHash)
 miner Established connection to eu1.ethermine.org:5555
 miner Spinning up miners...
 cu-0  Using Pci 0000:05:00.0: GeForce GTX 1060 6GB (Compute 6.1) Memory : 5.94 GB
 cl-1  Using Pci 0000:08:00.0: gfx900 (OpenCL 2.0 AMD-APP (3180.7)) Memory : 7.98 GB
 cl-2  Using Pci 0000:0b:00.0: gfx1010 (OpenCL 2.0 AMD-APP (3180.7)) Memory : 7.98 GB
 miner Extranonce set to 9e0e
 miner Authorized worker 0x96815EB373aD89F1a5822f08c8F0f6b72d102583.mine0
 miner Epoch : 395 Difficulty : 4.29 Gh
 miner Job: 83768a79 eu1.ethermine.org:5555
 cl-2  Using 4.15 GB out of 7.98 GB GPU memory
 cl-1  Using 4.15 GB out of 7.98 GB GPU memory
 miner Job: 64e45896 eu1.ethermine.org:5555
 cu-0  Using 4.15 GB out of 5.94 GB GPU memory
 cl-1  4.09 GB of DAG data generated in 4.0 seconds
 cl-2  4.09 GB of DAG data generated in 6.6 seconds
 miner Job: 7d4fb16e eu1.ethermine.org:5555
 miner 0:00 A0 0.00 h - cu0 0.00, cl1 0.00, cl2 0.00
 miner Job: 79d0db5b eu1.ethermine.org:5555
 miner Job: 9ebbfe97 eu1.ethermine.org:5555
 miner Job: ca831507 eu1.ethermine.org:5555
 miner Job: 6ba20b5c eu1.ethermine.org:5555
 miner 0:00 A0 10.84 Mh - cu0 0.00, cl1 8.21, cl2 2.64
 miner Job: 67107060 eu1.ethermine.org:5555
 miner Job: 89abd279 eu1.ethermine.org:5555
 miner 0:00 A0 77.58 Mh - cu0 0.00, cl1 27.48, cl2 50.10
 miner Job: f8e7e6e2 eu1.ethermine.org:5555
 miner Job: 4517c9d2 eu1.ethermine.org:5555
 miner 0:00 A0 77.57 Mh - cu0 0.00, cl1 27.51, cl2 50.06
 miner Job: 13e25d83 eu1.ethermine.org:5555
 miner Job: 991b2296 eu1.ethermine.org:5555
 cl-2  Job: 13e25d83 Solution: 0x9e0e800001e2d952
 miner **Accepted  22 ms. eu1.ethermine.org:5555
 miner Job: 28d8986f eu1.ethermine.org:5555
 miner 0:00 A1 77.50 Mh - cu0 0.00, cl1 27.44, cl2 50.06
 cu-0  5.94 GB of DAG data generated in 26.6 seconds
 miner Job: 672e22d5 eu1.ethermine.org:5555
 miner Job: 40da9666 eu1.ethermine.org:5555
 miner 0:00 A1 77.56 Mh - cu0 0.01, cl1 27.50, cl2 50.05
 miner Job: e4c0c9fd eu1.ethermine.org:5555
 miner Job: 26a1f624 eu1.ethermine.org:5555
 miner 0:00 A1 93.81 Mh - cu0 16.28, cl1 27.48, cl2 50.05
 miner Job: 54b07e3c eu1.ethermine.org:5555
 miner 0:00 A1 93.80 Mh - cu0 16.28, cl1 27.47, cl2 50.05
 miner Job: 136caa7d eu1.ethermine.org:5555
 miner 0:00 A1 93.86 Mh - cu0 16.28, cl1 27.52, cl2 50.05
 miner Job: 5347315a eu1.ethermine.org:5555
^C
 main  Got interrupt ...
 miner Disconnected from eu1.ethermine.org:5555
 miner Shutting down miners...
 main  Terminated!
```

**Comment by Zaqsnaider** [comment]
I have the same command line. Only the version differs - 1.3.1 gives more speed than 1.3.4 and does not select 5555 from several pools.

nsfminer -R -P stratum1+ssl://xxxxx.Grut@eu1.ethermine.org:5555 stratum1+tcp://xxxxx.Grut@eu1.ethermine.org:4444 stratum1+tcp://xxxxx.Grut@eu1.ethermine.org:14444 --exit --tstop=69 --tstart=55 --verbosity 2 --nocolor --multi

 miner nsfminer 1.3.4 (No stinkin' fees edition)
 miner Copyright 2021 Jean M. Cyr, Licensed under the terms
 miner  of the GNU General Public License Version 3
 miner https://github.com/no-fee-ethereum-mining/nsfminer
 miner Build: windows/release/msvc
 miner 3rd Party: MSVC 19.16.27045.0, Boost 1.75.0
 miner 3rd Party: OpenSSL 1.1.1i, Ethash 0.5.0
 miner No CUDA driver found
 miner Configured pool eu1.ethermine.org:5555
 miner Configured pool eu1.ethermine.org:4444
 miner Configured pool eu1.ethermine.org:14444
 <unknown> Selected pool eu1.ethermine.org:4444
 <unknown> Stratum mode : Eth-Proxy compatible
 <unknown> Established connection to eu1.ethermine.org:4444
 <unknown> Spinning up miners...
 cl-0  Using Pci 0000:01:00.0: Ellesmere (OpenCL 2.0 AMD-APP (3075.12)) Memory : 8.00 GB
 cl-1  Using Pci 0000:02:00.0: Ellesmere (OpenCL 2.0 AMD-APP (3075.12)) Memory : 8.00 GB
 cl-2  Using Pci 0000:03:00.0: Ellesmere (OpenCL 2.0 AMD-APP (3075.12)) Memory : 8.00 GB
 cl-3  Using Pci 0000:05:00.0: Ellesmere (OpenCL 2.0 AMD-APP (3075.12)) Memory : 8.00 GB
 <unknown> Epoch : 395 Difficulty : 4.00 Gh
 <unknown> Job: 3b688cf5 blk: 11856530 eu1.ethermine.org:4444
 cl-2  Using 4.15 GB out of 8.00 GB GPU memory
 cl-1  Using 4.15 GB out of 8.00 GB GPU memory
 cl-3  Using 4.15 GB out of 8.00 GB GPU memory
 cl-0  Using 4.15 GB out of 8.00 GB GPU memory
 <unknown> Job: e72813bc blk: 11856531 eu1.ethermine.org:4444
 cl-3  4.09 GB of DAG data generated in 16.5 seconds
 cl-2  4.09 GB of DAG data generated in 19.7 seconds
 cl-0  4.09 GB of DAG data generated in 27.5 seconds
 cl-1  4.09 GB of DAG data generated in 31.8 seconds
 <unknown> 0:00 A0 0.00 h - cl0 0.00 44C 34% A0
 <unknown> 0:00 A0 0.00 h - cl1 0.00 28C 16% A0
 <unknown> 0:00 A0 0.00 h - cl2 0.00 47C 35% A0
 <unknown> 0:00 A0 0.00 h - cl3 0.00 63C 34% A0
 <unknown> Job: e3b70117 blk: 11856531 eu1.ethermine.org:4444
 <unknown> Job: 4d658011 blk: 11856532 eu1.ethermine.org:4444
 <unknown> Job: a014adee blk: 11856532 eu1.ethermine.org:4444
 <unknown> Job: d24e2a9f blk: 11856532 eu1.ethermine.org:4444
 <unknown> Job: 5ab68062 blk: 11856532 eu1.ethermine.org:4444
 <unknown> Job: 15d66218 blk: 11856533 eu1.ethermine.org:4444
 <unknown> Job: 202d7d84 blk: 11856533 eu1.ethermine.org:4444
 <unknown> 0:00 A0 22.80 Mh - cl0 3.28 45C 35% A0
 <unknown> 0:00 A0 22.80 Mh - cl1 0.65 30C 16% A0
 <unknown> 0:00 A0 22.80 Mh - cl2 9.06 48C 35% A0
 <unknown> 0:00 A0 22.80 Mh - cl3 9.81 63C 34% A0
 <unknown> Job: badb38a9 blk: 11856533 eu1.ethermine.org:4444
 <unknown> Job: 9d5c11f7 blk: 11856533 eu1.ethermine.org:4444
 <unknown> 0:00 A0 108.52 Mh - cl0 27.69 45C 35% A0
 <unknown> 0:00 A0 108.52 Mh - cl1 26.44 31C 17% A0
 <unknown> 0:00 A0 108.52 Mh - cl2 27.73 48C 35% A0
 <unknown> 0:00 A0 108.52 Mh - cl3 26.65 64C 34% A0
 <unknown> Job: b795241e blk: 11856533 eu1.ethermine.org:4444
 <unknown> 0:00 A0 108.10 Mh - cl0 27.25 46C 35% A0
 <unknown> 0:00 A0 108.10 Mh - cl1 26.41 32C 18% A0
 <unknown> 0:00 A0 108.10 Mh - cl2 27.48 48C 35% A0
 <unknown> 0:00 A0 108.10 Mh - cl3 26.96 64C 34% A0
 <unknown> Job: 3a100962 blk: 11856533 eu1.ethermine.org:4444
 <unknown> 0:00 A0 108.56 Mh - cl0 27.25 46C 35% A0
 <unknown> 0:00 A0 108.56 Mh - cl1 26.41 32C 18% A0
 <unknown> 0:00 A0 108.56 Mh - cl2 27.94 48C 35% A0
 <unknown> 0:00 A0 108.56 Mh - cl3 26.96 65C 34% A0






 miner nsfminer 1.3.1 (No stinkin' fees edition)
 miner Copyright 2021 Jean M. Cyr, Licensed under the terms
 miner  of the GNU General Public License Version 3
 miner https://github.com/no-fee-ethereum-mining/nsfminer
 miner Build: windows/release/msvc
 miner 3rd Party: MSVC 19.16.27045.0, Boost 1.75.0
 miner 3rd Party: OpenSSL 1.1.1i, Ethash 0.5.0
 miner No CUDA driver found
 miner Configured pool eu1.ethermine.org:5555
 miner Configured pool eu1.ethermine.org:4444
 miner Configured pool eu1.ethermine.org:14444
 <unknown> Selected pool eu1.ethermine.org:5555
 <unknown> Stratum mode : Eth-Proxy compatible
 <unknown> Established connection to eu1.ethermine.org:5555
 <unknown> Spinning up miners...
 cl-0  Using Pci 0000:01:00.0: Ellesmere (OpenCL 2.0 AMD-APP (3075.12)) Memory : 8.00 GB
 cl-1  Using Pci 0000:02:00.0: Ellesmere (OpenCL 2.0 AMD-APP (3075.12)) Memory : 8.00 GB
 cl-2  Using Pci 0000:03:00.0: Ellesmere (OpenCL 2.0 AMD-APP (3075.12)) Memory : 8.00 GB
 cl-3  Using Pci 0000:05:00.0: Ellesmere (OpenCL 2.0 AMD-APP (3075.12)) Memory : 8.00 GB
 <unknown> Epoch : 395 Difficulty : 4.00 Gh
 <unknown> Job: cea84120 blk: 11856544 eu1.ethermine.org:5555
 cl-1  Using 4.15 GB out of 8.00 GB GPU memory
 cl-0  Using 4.15 GB out of 8.00 GB GPU memory
 cl-2  Using 4.15 GB out of 8.00 GB GPU memory
 cl-3  Using 4.15 GB out of 8.00 GB GPU memory
 <unknown> Job: b1351945 blk: 11856544 eu1.ethermine.org:5555
 cl-1  4.09 GB of DAG data generated in 11.7 seconds
 cl-0  4.09 GB of DAG data generated in 14.1 seconds
 cl-2  4.09 GB of DAG data generated in 18.0 seconds
 cl-3  4.09 GB of DAG data generated in 21.5 seconds
 <unknown> 0:00 A0 0.00 h - cl0 0.00 47C 35% A0
 <unknown> 0:00 A0 0.00 h - cl1 0.00 35C 17% A0
 <unknown> 0:00 A0 0.00 h - cl2 0.00 48C 34% A0
 <unknown> 0:00 A0 0.00 h - cl3 0.00 63C 33% A0
 <unknown> Job: c80e61c3 blk: 11856544 eu1.ethermine.org:5555
 <unknown> Job: b6590144 blk: 11856544 eu1.ethermine.org:5555
 <unknown> Job: f1f7f29e blk: 11856544 eu1.ethermine.org:5555
 <unknown> Job: fab640c2 blk: 11856544 eu1.ethermine.org:5555
 <unknown> Job: 93d1beb8 blk: 11856544 eu1.ethermine.org:5555
 <unknown> Job: 87435e91 blk: 11856545 eu1.ethermine.org:5555
 <unknown> Job: 33098c65 blk: 11856545 eu1.ethermine.org:5555
 <unknown> Job: c8f84336 blk: 11856546 eu1.ethermine.org:5555
 <unknown> Job: 86f83e41 blk: 11856546 eu1.ethermine.org:5555
 <unknown> Job: 1ceab44c blk: 11856546 eu1.ethermine.org:5555
 <unknown> Job: 6dbc20d7 blk: 11856546 eu1.ethermine.org:5555
 <unknown> 0:00 A0 22.62 Mh - cl0 8.04 47C 36% A0
 <unknown> 0:00 A0 22.62 Mh - cl1 10.60 35C 18% A0
 <unknown> 0:00 A0 22.62 Mh - cl2 3.93 49C 35% A0
 <unknown> 0:00 A0 22.62 Mh - cl3 0.05 65C 34% A0
 <unknown> Job: c7cbe4d9 blk: 11856546 eu1.ethermine.org:5555
 <unknown> 0:00 A0 121.78 Mh - cl0 30.59 48C 36% A0
 <unknown> 0:00 A0 121.78 Mh - cl1 30.02 36C 18% A0
 <unknown> 0:00 A0 121.78 Mh - cl2 30.62 49C 35% A0
 <unknown> 0:00 A0 121.78 Mh - cl3 30.56 66C 35% A0
 <unknown> Job: 009abe7f blk: 11856547 eu1.ethermine.org:5555
 <unknown> Job: 710b331b blk: 11856547 eu1.ethermine.org:5555
 cl-3  Job: 710b331b Solution: 0x79ac496f21a605fb
 <unknown> **Accepted  38 ms. eu1.ethermine.org:5555
 <unknown> Job: c2a3faa4 blk: 11856547 eu1.ethermine.org:5555
 cl-0  Job: c2a3faa4 Solution: 0x5ef574dd071f39a5
 <unknown> **Accepted  39 ms. eu1.ethermine.org:5555
 <unknown> 0:00 A2 121.77 Mh - cl0 30.53 48C 36% A1
 <unknown> 0:00 A2 121.77 Mh - cl1 30.18 36C 18% A0
 <unknown> 0:00 A2 121.77 Mh - cl2 30.55 49C 35% A0
 <unknown> 0:00 A2 121.77 Mh - cl3 30.50 66C 35% A1
