### ISSUE TITLE
cu-1  Unexpected error CUDA error in func dev::eth::CUDAMiner::initEpoch at line 101 out of memory on CUDA device 0000:02:00.0     

### ISSUE THREAD

**Issue by cseew99** [no-fee-ethereum-mining/nsfminer#78]
**Describe the bug**
Only 1 of 4 detected cards will initialize and run properly.
Error message:

- cu-0  Using Pci 0000:01:00.0: GeForce RTX 3070 (Compute 8.6) Memory : 8.00 
- cu-1  Using Pci 0000:02:00.0: GeForce RTX 3070 (Compute 8.6) Memory : 8.00 
- cu-2  Using Pci 0000:03:00.0: GeForce RTX 3070 (Compute 8.6) Memory : 8.00 
- cu-3  Using Pci 0000:04:00.0: GeForce RTX 3070 (Compute 8.6) Memory : 8.00 
- ...
- cu-0  Using 4.14 GB out of 8.00 GB GPU memory                                                                                                        
- cu-1  Unexpected error CUDA error in func dev::eth::CUDAMiner::initEpoch at line 101 out of memory on CUDA device 0000:02:00.0     
- cu-1  Mining suspended ...       
- cu-2  Unexpected error CUDA error in func dev::eth::CUDAMiner::initEpoch at line 101 out of memory on CUDA device 0000:03:00.0                      
- cu-2  Mining suspended 
- cu-3  Unexpected error CUDA error in func dev::eth::CUDAMiner::initEpoch at line 101 out of memory on CUDA device 0000:04:00.0                       
- cu-3  Mining suspended ...  `

**To Reproduce**
Run miner with nvidia 30 series cards? I came across this miner from the issues in ethminer that were talking about the same issue.

**Expected behavior**
Normal mining behavior

**Environment (please complete the following information):**
- Operating System: Windows 10
- Hardware: RTX 3070
- nsfminer Version: v1.3.3

**Additional context**
Admittedly, I am unsure of the true source of this problem I'm running into, so I would greatly appreciate any insight.

**Comment by jean-m-cyr** [comment]
I think version 1.3.4 (head code) will solve this issue.
