### ISSUE TITLE
How to enhance hashrate? 

### ISSUE THREAD

**Issue by gap370** [no-fee-ethereum-mining/nsfminer#82]
My setting: Ubuntu 20.04, cuda 11.2, GTX 1080ti

I run:
nsfminer -P stratum2+tcp://XXXXX.XXXX@daggerhashimoto.usa.nicehash.com:3353 -U --cu-block 256 --cu-streams 4 -R --HWMON 2

I can only have ~32MH/s, but in the whattomine, it's about 40MH/s. Is there anything that I can do to increase the hash rate? Thanks!

![Screenshot from 2021-02-14 01-51-01](https://user-images.githubusercontent.com/14858037/107871451-53b52780-6e67-11eb-948c-be8019590da7.png)

**Comment by kloklojul** [comment]
not really something to do with nsfminer but did you OC your memory? They usually also show the overclocking settings they used to get the hashrate that they are predicting.

**Comment by jean-m-cyr** [comment]
The figures shown at Whattomine are for 'tuned' GPU's... meaning overclocked and/or voltage adjusted.

**Comment by gap370** [comment]
running with ethlargementpill makes me get to ~44MH/s with 230W
dowload here https://github.com/Virosa/ETHlargementPill
chmod +x OhGodAnETHlargementPill-r2
sudo ./OhGodAnETHlargementPill-r2 
[keep it running with screen or tmux]

**Comment by Titaniumtown** [comment]
What is "ethlargementpill"? It seems to be closed source with only binaries available and no further information on their github.

**Comment by gap370** [comment]
I am not so sure either. There are a lot of debate about it, but it definitely works on my 1080ti.

**Comment by Titaniumtown** [comment]
I wouldn't take the risk and use it lol.
