### ISSUE TITLE
Unexpected error CUDA error in func initEpoch at line 137 invalid argument on CUDA device 0000:01:00.0

### ISSUE THREAD

**Issue by gap370** [no-fee-ethereum-mining/nsfminer#84]
**Describe the bug**
After mining for some time, the mining becomes suspended.
cu-0  Unexpected error CUDA error in func initEpoch at line 137 invalid argument on CUDA device 0000:01:00.0
cu-0  Mining suspended ...

**To Reproduce**
it happen after running for some time.

**Expected behavior**
After that it's not mining any more. I need to rerun.

**Screenshots (Optional)**
![Screenshot from 2021-02-14 17-14-20](https://user-images.githubusercontent.com/14858037/107892045-22307080-6ee8-11eb-8145-ca1cfabb2b6a.png)

**Environment (please complete the following information):**
- Operating System: Ubuntu 20.04
- Hardware: 1080Ti, cuda 11.2
- Ethminer Version: 1.3.4
- Ethminer options: nsfminer -P stratum2+tcp://XXX.XXX@daggerhashimoto.usa.nicehash.com:3353 -U --cu-block 256 --cu-streams 4 -R --HWMON 2 --nocolor

**Comment by jean-m-cyr** [comment]
Ah, epoch zero! Wonder which coin nicehash is mining at epoch zero? Good clue as to why it crashes though!

**Comment by gap370** [comment]
epoch 0 also triggers SIGSEGV error.
![Screenshot from 2021-02-14 22-21-03](https://user-images.githubusercontent.com/14858037/107905046-32117a00-6f13-11eb-85c7-4806d466cb95.png)

**Comment by jean-m-cyr** [comment]
This should be fixed by PR #86. Reopen if not so.
