### ISSUE TITLE
Got unknown method [mining.set_difficulty] from pool

### ISSUE THREAD

**Issue by DATL4G** [no-fee-ethereum-mining/nsfminer#88]
Same issue with [ethminer](https://github.com/ethereum-mining/ethminer/issues/2156)

**Comment by jean-m-cyr** [comment]
You are trying to connect to a stratum2 pool. You need to use the stratum2+tcp:// in your pool URL. Alternatively, you can use stratum:// and have nsfminer auto detect the stratum protocol.
