### ISSUE TITLE
CUDA: Shared Video Memory

### ISSUE THREAD

**Issue by Mariuspersen** [no-fee-ethereum-mining/nsfminer#89]
**Is your feature request related to a problem? Please describe.**
In my system there is currently a 3090 and a Quadro K2200.
Unfortunatly the K2200 doesn't have enough ram to currently mine. However with Ethminer it was able to mine on the K2200 because of shared video memory via CUDA. 

**Describe the solution you'd like**
Same feature as Ethminer with shared video memory when using CUDA

**Describe alternatives you've considered**
Well Ethminer, but it doesn't like the Ampere card, giving me a 
```
Unexpected error CUDA error in func set_constants at line 124 invalid device symbol on CUDA device #2126
```
error

**Additional context**
There might be something I missed in the build documentation or a build flag I missed, sorry if I did.

**Comment by jean-m-cyr** [comment]
I'm not sure what you mean by 'shared video memory'? If you're refering to the 'light cache on host' feature, it was primarilly intended to extend the life of 4GB GPUs a little past the DAG size limitations. I thought that time had passed. I know only the NV 1050 to be configured at 4GB of memory.

**Comment by Mariuspersen** [comment]
I was under the impression that it was somerthing related to CUDA, that CUDA devices can share memory from a pool. Considering 4GB VRAM graphics cards are still pretty common, it might be a nice feature to have if you are willing to implement it.

**Comment by jean-m-cyr** [comment]
Ethminer did something like that? I don't think so!
