### ISSUE TITLE
AMD RX 6800 / RX 6800 XT Support

### ISSUE THREAD

**Issue by MOVZX** [no-fee-ethereum-mining/nsfminer#9]
AMD RX 6800 / RX 6800 XT is not supported, I tried both on Windows and on GNU/Linux (Hive OS).

**Comment by jean-m-cyr** [comment]
I don't have one. Any idea what I'm missing?

**Comment by jean-m-cyr** [comment]
@MOVX Opencl bindings upgraded to 2.2 in release builds. Does that help?

**Comment by MOVZX** [comment]
![image](https://user-images.githubusercontent.com/3374397/105564871-ab73dd80-5d56-11eb-9bf6-0c4e575f40d9.png)

Still can not detect RX 6800.

**Comment by jean-m-cyr** [comment]
Just released version 1.2.4 has opencl enumeration diagnostics that might tell us why.

**Comment by jean-m-cyr** [comment]
@MOVZX Dunno! Seems to recognize it just fine!
```
oot@hog:/tmp# ./nsfminer --list-devices
 Id Pci Id    Type Name                          CUDA SM  CL    Total Memory  Cl Max Alloc  Cl Max W.Grp
--- --------- ---- ----------------------------- ---- --- ----  ------------  ------------  ------------
  0 03:00.0   Gpu  gfx1030                                Yes       15.98 GB
  1 05:00.0   Gpu  GeForce RTX 3060 Ti           Yes  8.6 Yes        7.80 GB
  2 09:00.0   Gpu  gfx900                                 Yes        7.98 GB
  3 0c:00.0   Gpu  gfx1010                                Yes        7.98 GB
```

**Comment by MOVZX** [comment]
> --list-devices

![image](https://user-images.githubusercontent.com/3374397/106287213-1a7e9400-6279-11eb-9b0b-e4caf3e222e7.png)

**Comment by parasyte** [comment]
FWIW, I have the same problem on Windows with an RX 5700 XT. Planning to try Linux later this week...

**Comment by yobowl1** [comment]
I have had this issue as well.

I have solved it using a registry edit described in this post for Ethminer: https://github.com/ethereum-mining/ethminer/issues/2001

**Comment by parasyte** [comment]
Good to know, thank you! And it does fix the issue. @jean-m-cyr This should at least be documented.
