### ISSUE TITLE
Does nsfminer have multiple gpu function to choose from? 

### ISSUE THREAD

**Issue by gap370** [no-fee-ethereum-mining/nsfminer#91]
I am wondering whether there is a --cu-devices argument that we can use for multiple gpu mining. like it did in ethminer. Thanks a lot!

**Comment by jean-m-cyr** [comment]
In nsfminer we do not distinguish between AMD and NV when it comes to device numbers. You can use the --devices parameter the same way you used --cu-devices or --cl-devices in Ethminer.
