### ISSUE TITLE
Effective hash rate

### ISSUE THREAD

**Issue by SpeedeMiner** [no-fee-ethereum-mining/nsfminer#93]
**Describe the bug**
When starting mining with the display of the effective hash rate, at first it showed correctly. But in the morning he began to show incorrectly.

**To Reproduce**
1. start mining with the --verbosity 4
2. Wait 10+ hour

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/79132469/108157202-6308cf00-710c-11eb-8c88-1554e533a08b.png)

**Environment (please complete the following information):**
- Operating System: [e.g. Windows 10]
- Hardware [e.g. RTX 3070]
- Nsfminer Version [v1.3.4]
- Nsfminer options used  -R -U -P stratum+ssl://*@eu1.ethermine.org:5555 --api-bind 192.168.1.15:3333 --retry-delay 5 --retry-max 0 --verbosity 4 --exit

**Comment by jean-m-cyr** [comment]
Yes, that's normal. As noted in the help info, effective hash rate calculation does not work with stratum2 pools where the difficulty can vary.

**Comment by SpeedeMiner** [comment]
On ethermine stratum has 4.0gh difficulty and it's not change.

**Comment by SpeedeMiner** [comment]
![Uploading IMG_20210217_235354_605.jpg…]()

**Comment by jean-m-cyr** [comment]
Ah, interresting. If you use stratum+ssl:// you get a stratum 1 connection. If you use stratums:// you get a stratum 2 connection!

So, that's not the problem. Re-opening the ticket.

**Comment by SpeedeMiner** [comment]
I noticed that it works correctly until a reconnection occurs due to a change in the public IP address

**Comment by jean-m-cyr** [comment]
Ok, finally got this working. Commit 0e7fef73
