### ISSUE TITLE
Reopen #76: hashrate decreased since 1.3.3

### ISSUE THREAD

**Issue by sfornengo** [no-fee-ethereum-mining/nsfminer#94]
Since version 1.3.3 nfsminer never connects on 5555, always 4444.
Of course I double check my stratums syntax... and it works good with version 1.3.2
Even worse, it regurlarly resumes mining after a failover timeout leading to poor hashrate.
Here is the console output: 

 miner nsfminer 1.3.5+commit.811f00e5 (No stinkin' fees edition)
 miner Copyright 2021 Jean M. Cyr, Licensed under the terms
 miner  of the GNU General Public License Version 3                                                                                                                                                                      
 miner https://github.com/no-fee-ethereum-mining/nsfminer                                                                                                                                                                
 miner Build: linux/release/gnu                                                                                                                                                                                          
 miner 3rd Party: GCC 9.3.0, CUDA 11.2, Boost 1.75.0                                                                                                                                                                     
 miner 3rd Party: OpenSSL 1.1.1i, Ethash 0.5.0                                                                                                                                                                           
 miner Configured pool eu1.ethermine.org:5555
 miner Configured pool eu1.ethermine.org:4444
 miner Configured pool eu1.ethermine.org:14444
 miner Selected pool eu1.ethermine.org:4444
 miner Negotiation of EthereumStratum/2.0.0 failed. Trying another ...
 miner Stratum mode : EthereumStratum/1.0.0 (NiceHash)
 miner Established connection to eu1.ethermine.org:4444
 miner Spinning up miners...
 miner Extranonce set to 39a5
 cu-0  Using Pci 0000:01:00.0: GeForce GTX 1070 (Compute 6.1) Memory : 7.93 GB
 miner Authorized worker 0x...
 miner Epoch : 395 Difficulty : 4.29 Gh
 miner Job: a3831196 eu1.ethermine.org:4444
 miner Job: f7717319 eu1.ethermine.org:4444
 cu-0  Required GPU mem: Total 4.15 GB, Cache 65.37 MB, DAG 4.09 GB, Miscellaneous 56.00 B
 miner Job: a670b8c3 eu1.ethermine.org:4444
 miner Job: b6e42a02 eu1.ethermine.org:4444
 miner 0:00 A0 0.00 h - cu0 0.00 58C 79%
 miner Job: e4154cf3 eu1.ethermine.org:4444
 miner Job: 9d77ad47 eu1.ethermine.org:4444
 miner 0:00 A0 0.00 h - cu0 0.00 68C 78%
 miner Job: feff3faa eu1.ethermine.org:4444
 miner Job: d9301364 eu1.ethermine.org:4444
 cu-0  4.09 GB of DAG data generated in 20.5 seconds
 miner Job: d61230a1 eu1.ethermine.org:4444
 miner 0:00 A0 0.00 h - cu0 0.00 70C 78%
 miner Job: f697eb7e eu1.ethermine.org:4444
 miner Job: e5383694 eu1.ethermine.org:4444
 miner Job: e6557851 eu1.ethermine.org:4444
 miner Job: 7350d160 eu1.ethermine.org:4444
 miner Job: f96ce074 eu1.ethermine.org:4444
 miner Job: 053ca386 eu1.ethermine.org:4444
 miner 0:00 A0 23.69 Mh - cu0 23.69 71C 78%
 miner Job: 6c9e87af eu1.ethermine.org:4444
 miner Job: 3819de5d eu1.ethermine.org:4444
 miner 0:00 A0 23.81 Mh - cu0 23.81 71C 78%
 miner Job: a7993d64 eu1.ethermine.org:4444
 miner Job: 5ace72b3 eu1.ethermine.org:4444
 miner Job: 09cfcdf3 eu1.ethermine.org:4444
 miner Job: a8cf001b eu1.ethermine.org:4444
 miner Job: 31d76b3d eu1.ethermine.org:4444
 miner Job: 80029ee8 eu1.ethermine.org:4444
 miner 0:01 A0 23.69 Mh - cu0 23.69 72C 78%
 miner Failover timeout reached, retrying connection to primary pool
 miner Disconnected from eu1.ethermine.org:4444
 miner No connection. Suspend mining ...
 miner Selected pool eu1.ethermine.org:4444
 miner Stratum mode : EthereumStratum/1.0.0 (NiceHash)
 miner Established connection to eu1.ethermine.org:4444
 miner Resume mining ...
 miner Extranonce set to a7d4
 miner Authorized worker 0x...
 miner Job: 80029ee8 eu1.ethermine.org:4444
 miner Job: 4706173e eu1.ethermine.org:4444
 miner Job: ffbd51c3 eu1.ethermine.org:4444
 miner Job: a0333011 eu1.ethermine.org:4444
 miner Job: 5a2874b3 eu1.ethermine.org:4444
 miner 0:01 A0 23.68 Mh - cu0 23.68 69C 75%
 miner Job: 619641de eu1.ethermine.org:4444

**Comment by SpeedeMiner** [comment]
On auto not work properly stratum. On windows i write manually stratum+ssl and it works with 5555

**Comment by sfornengo** [comment]
On ubuntu 20.04, neither work with stratums nor stratum+ssl on eu1.ethermine.org:5555
Only stratum on eu1.ethermine.org:4444
And then annoying failover timeout always resumes mining...

**Comment by jean-m-cyr** [comment]
Try this. Works for me!
```
miner@miner0[192.168.1.133]~/nsfminer/build nsfminer/nsfminer -U -P stratums://0x2ceCE0c3BeE218Cb78fFE19FD77Fbb3caa0F6e86.miner0@eu1.ethermine.org:5555
 miner nsfminer 1.3.5 (No stinkin' fees edition)
 miner Copyright 2021 Jean M. Cyr, Licensed under the terms
 miner  of the GNU General Public License Version 3
 miner https://github.com/no-fee-ethereum-mining/nsfminer
 miner Build: linux/release/gnu
 miner 3rd Party: GCC 9.3.0, CUDA 11.2, Boost 1.75.0
 miner 3rd Party: OpenSSL 1.1.1i, Ethash 0.5.0
 miner Configured pool eu1.ethermine.org:5555
 miner Selected pool eu1.ethermine.org:5555
 miner Negotiation of EthereumStratum/2.0.0 failed. Trying another ...
 miner Stratum mode : EthereumStratum/1.0.0 (NiceHash)
 miner Established connection to eu1.ethermine.org:5555
 miner Spinning up miners...
 cu-0  Using Pci 0000:05:00.0: GeForce GTX 1060 6GB (Compute 6.1) Memory : 5.94 GB
 miner Extranonce set to bb02
 miner Authorized worker 0x2ceCE0c3BeE218Cb78fFE19FD77Fbb3caa0F6e86.miner0
 miner Epoch : 395 Difficulty : 4.29 Gh
 miner Job: e0b492b4 eu1.ethermine.org:5555
 miner Job: 05749594 eu1.ethermine.org:5555
 miner 0:00 A0 0.00 h - cu0 0.00
 miner Job: e6799192 eu1.ethermine.org:5555
 cu-0  Required GPU mem: Total 4.15 GB, Cache 65.37 MB, DAG 4.09 GB, Miscellaneous 56.00 B
 miner Job: dacb725d eu1.ethermine.org:5555
 miner 0:00 A0 0.00 h - cu0 0.00
 miner Job: f4b57b82 eu1.ethermine.org:5555
 miner 0:00 A0 0.00 h - cu0 0.00
 miner Job: 0b22b59a eu1.ethermine.org:5555
 miner Job: a9b57458 eu1.ethermine.org:5555
 miner Job: 6c720ed9 eu1.ethermine.org:5555
 miner Job: a9b57458 eu1.ethermine.org:5555
 miner Job: 4e01a5d0 eu1.ethermine.org:5555
 miner 0:00 A0 0.00 h - cu0 0.00
 miner Job: dc04dcf8 eu1.ethermine.org:5555
 miner Job: d12cb0a4 eu1.ethermine.org:5555
 miner 0:00 A0 0.00 h - cu0 0.00
 miner Job: c0eb339b eu1.ethermine.org:5555
 miner 0:00 A0 0.00 h - cu0 0.00
 cu-0  4.09 GB of DAG data generated in 26.6 seconds
 miner Job: 1ac84dea eu1.ethermine.org:5555
 miner 0:00 A0 7.95 Kh - cu0 7.95
 miner Job: 02b5afa7 eu1.ethermine.org:5555
 miner Job: 3bb45a0b eu1.ethermine.org:5555
 miner Job: 02b5afa7 eu1.ethermine.org:5555
 miner Job: ace0c1ff eu1.ethermine.org:5555
 miner Job: c9af602e eu1.ethermine.org:5555
 miner Job: 901d0ac0 eu1.ethermine.org:5555
 miner 0:00 A0 16.28 Mh - cu0 16.28
 miner Job: d87803c4 eu1.ethermine.org:5555
 miner 0:00 A0 16.27 Mh - cu0 16.27
 miner Job: dddb20c4 eu1.ethermine.org:5555
^C
 main  Got interrupt ...
 miner Disconnected from eu1.ethermine.org:5555
 miner Shutting down miners...
 main  Terminated!
```

**Comment by sfornengo** [comment]
Please try this too:

~/nsfminer/build nsfminer/nsfminer -U -P stratums://0x2ceCE0c3BeE218Cb78fFE19FD77Fbb3caa0F6e86.miner0@eu1.ethermine.org:5555 -P stratum://0x2ceCE0c3BeE218Cb78fFE19FD77Fbb3caa0F6e86.miner0@eu1.ethermine.org:4444

And you should see that we expect 5555 (as in 1.3.2 version) and we get directly 4444

Please stop closing bugs without a minimal feedback...
Thanks you!

**Comment by sfornengo** [comment]
And then append --failover-timeout 1:

~/nsfminer/build nsfminer/nsfminer -U --failover-timeout 1 -P stratums://0x2ceCE0c3BeE218Cb78fFE19FD77Fbb3caa0F6e86.miner0@eu1.ethermine.org:5555 -P stratum://0x2ceCE0c3BeE218Cb78fFE19FD77Fbb3caa0F6e86.miner0@eu1.ethermine.org:4444

And you should see that we expect 5555 (as in 1.3.2 version) and we get directly 4444 (in 1.3.3 to 1.3.5) and also trigger a failover timeout regularly that kills hashrate.
