### ISSUE TITLE
incorrect share after dag build

### ISSUE THREAD

**Issue by SpeedeMiner** [no-fee-ethereum-mining/nsfminer#96]
**Describe the bug**
On RTX 3070 when creating a dag file at high overclocking 8100-8200mhz, the found share are invalid. If you create a dag file at low overclocking 7800mhz and then after dag build make a high overclocking 8100-8200mhz, then there are no share are invalid.

**To Reproduce**
1. high overclocking 8100-8200mhz
2. Start mining
3. See error

**Screenshots**
![inv](https://user-images.githubusercontent.com/79132469/108201800-78045300-714a-11eb-8e62-8b5d5b292711.png)

**Environment (please complete the following information):**
- Operating System: [e.g. Windows 10]
- Hardware [e.g. RTX 3070]
- Nsfminer Version [v1.3.5]
- Nsfminer options used -R -U -P stratum+ssl://*@eu1.ethermine.org:5555 --api-bind 192.168.1.15:3333 --retry-delay 5 --retry-max 0 --verbosity 4 --exit

**Additional context**
You can make dag file creation less aggressive with checksum verification. Make a command on epoch change, exit or run a third-party script.

**Comment by jean-m-cyr** [comment]
Hmm... I see. You'd need a pre-DAG gen script to down clock, and a post DAG gen script to up clock. Protocols like stratum2 change the epoch on the fly.

**Comment by SpeedeMiner** [comment]
Yes, now i use this 
start OC.bat
SET GPU0=-setMemoryClockOffset:0,0,800
nvidiaInspector.exe %GPU0%
.\nsfminer.exe -R -U -P stratum+ssl://*@eu1.ethermine.org:5555 --api-bind 192.168.1.15:3333 --retry-delay 5 --retry-max 0 --verbosity 4 --exit

in OC.bat 
TIMEOUT /T 60
SET GPU0=-setMemoryClockOffset:0,0,1100

**Comment by SpeedeMiner** [comment]
T-rex miner 
Add ability to execute custom scripts upon certain events with new parameters: --script-start, --script-epoch-change

**Comment by kolba** [comment]
Just thought I'll extend on this idea here. So not only would it be beneficial to have DAG generated with "safe" mode, but also to support multiple epoch caching to allow multicoin mining (eg ETH+ZIL). This is similar to t-rex `--extra-dag-epoch` flag for example.
